CREATE VIEW "public"."v2_rpc_gateway_model_usage_daily" WITH (security_invoker=true) AS  SELECT usage.usage_date AS day_bucket,
    usage.model_slug AS model_id,
    route.provider_slug AS provider_id,
    'unknown'::text AS endpoint,
    usage.requests,
    usage.successful_requests AS success_requests,
    usage.failed_requests,
    (0)::bigint AS neutral_requests,
    usage.rate_limited_requests,
    (COALESCE(((meters."values" ->> 'total_tokens'::text))::numeric, (((meters."values" ->> 'input_tokens'::text))::numeric + ((meters."values" ->> 'output_tokens'::text))::numeric), (((meters."values" ->> 'input_text_tokens'::text))::numeric + ((meters."values" ->> 'output_text_tokens'::text))::numeric), (0)::numeric))::bigint AS total_tokens,
    (COALESCE(((meters."values" ->> 'input_tokens'::text))::numeric, ((meters."values" ->> 'input_text_tokens'::text))::numeric, (0)::numeric))::bigint AS input_tokens,
    (COALESCE(((meters."values" ->> 'output_tokens'::text))::numeric, ((meters."values" ->> 'output_text_tokens'::text))::numeric, (0)::numeric))::bigint AS output_tokens,
    (COALESCE(((meters."values" ->> 'reasoning_tokens'::text))::numeric, (0)::numeric))::bigint AS reasoning_tokens,
    (COALESCE(((meters."values" ->> 'input_text_tokens'::text))::numeric, (0)::numeric))::bigint AS input_text_tokens,
    (COALESCE(((meters."values" ->> 'output_text_tokens'::text))::numeric, (0)::numeric))::bigint AS output_text_tokens,
    (COALESCE(((meters."values" ->> 'input_image_tokens'::text))::numeric, (0)::numeric))::bigint AS input_image_tokens,
    (COALESCE(((meters."values" ->> 'output_image_tokens'::text))::numeric, (0)::numeric))::bigint AS output_image_tokens,
    (COALESCE(((meters."values" ->> 'input_audio_tokens'::text))::numeric, (0)::numeric))::bigint AS input_audio_tokens,
    (COALESCE(((meters."values" ->> 'output_audio_tokens'::text))::numeric, (0)::numeric))::bigint AS output_audio_tokens,
    (COALESCE(((meters."values" ->> 'input_video_tokens'::text))::numeric, (0)::numeric))::bigint AS input_video_tokens,
    (COALESCE(((meters."values" ->> 'output_video_tokens'::text))::numeric, (0)::numeric))::bigint AS output_video_tokens,
    (COALESCE(((meters."values" ->> 'image_inputs'::text))::numeric, ((meters."values" ->> 'input_images'::text))::numeric, (0)::numeric))::bigint AS image_inputs,
    (COALESCE(((meters."values" ->> 'image_outputs'::text))::numeric, ((meters."values" ->> 'output_images'::text))::numeric, (0)::numeric))::bigint AS image_outputs,
    (COALESCE(((meters."values" ->> 'audio_inputs'::text))::numeric, ((meters."values" ->> 'input_audio'::text))::numeric, (0)::numeric))::bigint AS audio_inputs,
    (COALESCE(((meters."values" ->> 'audio_outputs'::text))::numeric, ((meters."values" ->> 'output_audio'::text))::numeric, (0)::numeric))::bigint AS audio_outputs,
    (COALESCE(((meters."values" ->> 'video_inputs'::text))::numeric, ((meters."values" ->> 'input_video'::text))::numeric, (0)::numeric))::bigint AS video_inputs,
    (COALESCE(((meters."values" ->> 'video_outputs'::text))::numeric, ((meters."values" ->> 'output_video'::text))::numeric, (0)::numeric))::bigint AS video_outputs,
    (COALESCE(((meters."values" ->> 'cached_read_tokens'::text))::numeric, ((meters."values" ->> 'cached_input_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_read_tokens,
    (COALESCE(((meters."values" ->> 'cached_write_tokens'::text))::numeric, ((meters."values" ->> 'cache_write_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_write_tokens,
    (COALESCE(((meters."values" ->> 'cached_read_text_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_read_text_tokens,
    (COALESCE(((meters."values" ->> 'cached_write_text_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_write_text_tokens,
    (COALESCE(((meters."values" ->> 'cached_read_image_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_read_image_tokens,
    (COALESCE(((meters."values" ->> 'cached_write_image_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_write_image_tokens,
    (COALESCE(((meters."values" ->> 'cached_read_audio_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_read_audio_tokens,
    (COALESCE(((meters."values" ->> 'cached_write_audio_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_write_audio_tokens,
    (COALESCE(((meters."values" ->> 'cached_read_video_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_read_video_tokens,
    (COALESCE(((meters."values" ->> 'cached_write_video_tokens'::text))::numeric, (0)::numeric))::bigint AS cached_write_video_tokens,
    (0)::bigint AS total_cost_nanos,
    usage.latency_sum_ms,
    usage.latency_count AS latency_samples,
    usage.generation_sum_ms,
    usage.generation_count AS generation_samples,
    usage.throughput_sum,
    usage.throughput_count AS throughput_samples,
    usage.updated_at AS last_request_at,
    usage.updated_at AS refreshed_at,
    (COALESCE(((meters."values" ->> 'input_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS input_quad_tokens,
    (COALESCE(((meters."values" ->> 'output_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS output_quad_tokens,
    (COALESCE(((meters."values" ->> 'total_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS total_quad_tokens,
    (COALESCE(((meters."values" ->> 'cached_write_text_tokens_5m'::text))::numeric, (0)::numeric))::bigint AS cached_write_text_tokens_5m,
    (COALESCE(((meters."values" ->> 'cached_write_text_tokens_1h'::text))::numeric, (0)::numeric))::bigint AS cached_write_text_tokens_1h,
    (COALESCE(((meters."values" ->> 'text_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS text_quad_tokens,
    (COALESCE(((meters."values" ->> 'rerank_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS rerank_quad_tokens,
    (COALESCE(((meters."values" ->> 'embedding_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS embedding_quad_tokens,
    (COALESCE(((meters."values" ->> 'moderation_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS moderation_quad_tokens,
    (COALESCE(((meters."values" ->> 'ocr_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS ocr_quad_tokens,
    COALESCE(((meters."values" ->> 'image_megapixels'::text))::numeric, (0)::numeric) AS image_megapixels,
    COALESCE(((meters."values" ->> 'audio_seconds'::text))::numeric, (0)::numeric) AS audio_seconds,
    COALESCE(((meters."values" ->> 'video_pixel_seconds'::text))::numeric, (0)::numeric) AS video_pixel_seconds,
    (COALESCE(((meters."values" ->> 'input_characters'::text))::numeric, (0)::numeric))::bigint AS input_characters,
    (COALESCE(((meters."values" ->> 'output_characters'::text))::numeric, (0)::numeric))::bigint AS output_characters,
    (COALESCE(((meters."values" ->> 'total_characters'::text))::numeric, (0)::numeric))::bigint AS total_characters,
    (COALESCE(((meters."values" ->> 'embedding_tokens'::text))::numeric, (0)::numeric))::bigint AS embedding_tokens,
    COALESCE(((meters."values" ->> 'video_seconds'::text))::numeric, ((meters."values" ->> 'output_video_seconds'::text))::numeric, (0)::numeric) AS video_seconds,
    COALESCE(((meters."values" ->> 'speech_seconds'::text))::numeric, (0)::numeric) AS speech_seconds,
    COALESCE(((meters."values" ->> 'transcription_seconds'::text))::numeric, (0)::numeric) AS transcription_seconds
   FROM (((public.v2_public_usage_daily usage
     JOIN public.v2_model_provider_routes route ON (((route.provider_model_id = usage.provider_model_id) AND (COALESCE(route.is_stealth, false) = false) AND (route.routing_enabled = true) AND (route.status = ANY (ARRAY['active'::text, 'degraded'::text])) AND ((route.effective_from IS NULL) OR (route.effective_from <= now())) AND ((route.effective_to IS NULL) OR (route.effective_to > now())))))
     JOIN public.v2_models model ON (((model.model_slug = usage.model_slug) AND (model.hidden = false) AND (model.status <> 'disabled'::text))))
     LEFT JOIN LATERAL ( SELECT jsonb_object_agg(meter.meter_key, meter.quantity) AS "values"
           FROM ( SELECT v2_public_usage_daily_meters.meter_key,
                    sum(v2_public_usage_daily_meters.quantity) AS quantity
                   FROM public.v2_public_usage_daily_meters
                  WHERE (v2_public_usage_daily_meters.rollup_id = usage.rollup_id)
                  GROUP BY v2_public_usage_daily_meters.meter_key) meter) meters ON (true));

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."v2_rpc_gateway_model_usage_daily" TO "anon", "authenticated", "service_role";
