CREATE VIEW "public"."v2_request_facts_by_creator" WITH (security_invoker=true) AS  SELECT facts.request_event_id,
    facts.workspace_id,
    facts.request_id,
    facts.occurred_at,
    facts.app_id,
    facts.key_id,
    facts.endpoint,
    facts.requested_model_input,
    facts.requested_model_slug,
    facts.routed_model_slug,
    facts.provider_model_id,
    facts.status_code,
    facts.success,
    facts.error_code,
    facts.stop_reason,
    facts.tool_call_count,
    facts.structured_output_attempted,
    facts.structured_output_succeeded,
    facts.stream,
    facts.byok,
    facts.latency_ms,
    facts.time_to_first_token_ms,
    facts.generation_ms,
    facts.queue_ms,
    facts.upstream_latency_ms,
    facts.upstream_attempt_count,
    facts.throughput,
    facts.user_agent,
    facts.sdk_name,
    facts.sdk_version,
    facts.client_version,
    facts.region,
    facts.safe_metadata,
    facts.created_at,
    facts.cloudflare_colo,
    facts.internal_dispatch_ms,
    facts.gateway_total_ms,
    facts.session_id,
    facts.end_user_id,
    facts.auth_method,
    facts.native_response_id,
    facts.cost_nanos,
    facts.currency,
    facts.tool_call_succeeded,
    facts.gateway_request_id,
    facts.gateway_request_created_at,
    facts.edge_country,
    facts.edge_continent,
    facts.provider_ttft_ms,
    facts.gateway_ttft_ms,
    facts.output_speed_tps,
    facts.tpot_ms,
    facts.itl_ms,
    facts.phaseo_overhead_ms,
    facts.client_source_id,
    facts.client_source_name,
    facts.client_source_kind,
    facts.client_source_version,
    facts.client_source_detection,
    facts.service_tier_requested,
    facts.service_tier_observed,
    facts.service_tier_slug,
    keys.created_by AS key_created_by
   FROM (public.v2_request_facts facts
     JOIN public.keys keys ON (((keys.id = facts.key_id) AND (keys.workspace_id = facts.workspace_id))));

REVOKE ALL ON TABLE "public"."v2_request_facts_by_creator" FROM "service_role";

GRANT SELECT ON TABLE "public"."v2_request_facts_by_creator" TO "service_role";

REVOKE ALL ON TABLE "public"."v2_request_facts_by_creator" FROM "anon", "authenticated";
