CREATE VIEW "public"."v2_web_gateway_requests_by_creator" WITH (security_invoker=true) AS  SELECT requests.id,
    requests.created_at,
    requests.team_id,
    requests.workspace_id,
    requests.request_id,
    requests.app_id,
    requests.endpoint,
    requests.model_id,
    requests.requested_model_id,
    requests.routed_model_id,
    requests.canonical_model_id,
    requests.provider,
    requests.native_response_id,
    requests.stream,
    requests.byok,
    requests.status_code,
    requests.success,
    requests.error_code,
    requests.error_message,
    requests.latency_ms,
    requests.generation_ms,
    requests.e2e_latency_ms,
    requests.usage,
    requests.usage_total_tokens,
    requests.usage_input_tokens,
    requests.usage_output_tokens,
    requests.usage_reasoning_tokens,
    requests.usage_input_text_tokens,
    requests.usage_output_text_tokens,
    requests.usage_input_image_tokens,
    requests.usage_output_image_tokens,
    requests.usage_input_audio_tokens,
    requests.usage_output_audio_tokens,
    requests.usage_input_video_tokens,
    requests.usage_output_video_tokens,
    requests.usage_image_inputs,
    requests.usage_image_outputs,
    requests.usage_audio_inputs,
    requests.usage_audio_outputs,
    requests.usage_video_inputs,
    requests.usage_video_outputs,
    requests.usage_cached_read_tokens,
    requests.usage_cached_write_tokens,
    requests.usage_cached_read_text_tokens,
    requests.usage_cached_write_text_tokens,
    requests.usage_cached_write_text_tokens_5m,
    requests.usage_cached_write_text_tokens_1h,
    requests.usage_cached_read_image_tokens,
    requests.usage_cached_write_image_tokens,
    requests.usage_cached_read_audio_tokens,
    requests.usage_cached_write_audio_tokens,
    requests.usage_cached_read_video_tokens,
    requests.usage_cached_write_video_tokens,
    requests.usage_input_quad_tokens,
    requests.usage_output_quad_tokens,
    requests.usage_total_quad_tokens,
    requests.usage_text_quad_tokens,
    requests.usage_rerank_quad_tokens,
    requests.usage_embedding_quad_tokens,
    requests.usage_moderation_quad_tokens,
    requests.usage_ocr_quad_tokens,
    requests.usage_image_megapixels,
    requests.usage_audio_seconds,
    requests.usage_video_pixel_seconds,
    requests.usage_input_characters,
    requests.usage_output_characters,
    requests.usage_total_characters,
    requests.usage_normalized_at,
    requests.cost_nanos,
    requests.currency,
    requests.pricing_lines,
    requests.key_id,
    requests.throughput,
    requests.location,
    requests.auth_method,
    requests.oauth_client_id,
    requests.oauth_user_id,
    requests.end_user_id,
    requests.session_id,
    requests.trace_data,
    requests.provider_attempts,
    requests.stop_reason,
    requests.finish_reason,
    requests.tool_call_count,
    requests.structured_output_attempted,
    requests.structured_output_succeeded,
    requests.cloudflare_colo,
    requests.error_payload,
    requests.detail_metadata,
    requests.client_source_id,
    requests.client_source_name,
    requests.client_source_kind,
    requests.client_source_version,
    requests.client_source_detection,
    keys.created_by AS key_created_by
   FROM (public.v2_web_gateway_requests requests
     JOIN public.keys keys ON (((keys.id = requests.key_id) AND (keys.workspace_id = requests.workspace_id))));

REVOKE ALL ON TABLE "public"."v2_web_gateway_requests_by_creator" FROM "service_role";

GRANT SELECT ON TABLE "public"."v2_web_gateway_requests_by_creator" TO "service_role";

REVOKE ALL ON TABLE "public"."v2_web_gateway_requests_by_creator" FROM "anon", "authenticated";
