// Purpose: Code-first policy registry for text endpoint parameters.
// Why: Keeps param support/alias/quirk behavior explicit in code (not hidden in DB state).
// How: Exposes endpoint registries, aliases, always-supported rules, and provider overrides.

import type { Endpoint } from "@core/types";
import { resolveTextProviderParamPolicyOverride } from "@providers/textProfiles";

export type TextEndpoint = "chat.completions" | "responses" | "messages";

export type EndpointParamRegistry = {
	allowedTopLevel: Set<string>;
	keyToCanonicalParam: Record<string, string>;
};

const TEXT_ENDPOINT_REGISTRY: Record<TextEndpoint, EndpointParamRegistry> = {
	"chat.completions": {
		allowedTopLevel: new Set([
			"model",
			"system",
			"messages",
			"n",
			"documents",
			"usage",
			"reasoning",
			"reasoning_effort",
			"frequency_penalty",
			"logit_bias",
			"max_output_tokens",
			"max_completion_tokens",
			"max_tokens",
			"meta",
			"metadata",
			"echo_upstream_request",
			"debug",
			"presence_penalty",
			"seed",
			"store",
			"stream",
			"stream_options",
			"temperature",
			"tools",
			"max_tool_calls",
			"max_tools_calls",
			"parallel_tool_calls",
			"tool_choice",
			"top_k",
			"min_p",
			"repetition_penalty",
			"respond_as",
			"min_tokens",
			"custom_token_bans",
			"dynatemp_mode",
			"dynatemp_min",
			"dynatemp_max",
			"dynatemp_exponent",
			"epsilon_cutoff",
			"top_a",
			"typical_p",
			"eta_cutoff",
			"tfs",
			"smoothing_factor",
			"smoothing_curve",
			"xtc_probability",
			"xtc_threshold",
			"dry_multiplier",
			"dry_base",
			"dry_allowed_length",
			"dry_range",
			"dry_sequence_breakers",
			"ignore_eos",
			"custom_timeout",
			"allow_logging",
			"logprobs",
			"top_logprobs",
			"top_p",
			"stop",
			"response_format",
			"modalities",
			"response_modalities",
			"responseModalities",
			"image_config",
			"imageConfig",
			"thinking",
			"reasoning_split",
			"user_id",
			"user",
			"service_tier",
			"prompt_cache_key",
			"prompt_cache_retention",
			"prompt_cache_options",
			"provider_options",
			"providerOptions",
			"web_search_options",
			"webSearchOptions",
			"mcp_servers",
			"safety_identifier",
			"route",
			"session_id",
			"models",
			"plugins",
			"trace",
			"provider",
			"routing",
		]),
		keyToCanonicalParam: {
			n: "n",
			documents: "documents",
			tools: "tools",
			tool_choice: "tool_choice",
			parallel_tool_calls: "parallel_tool_calls",
			max_tool_calls: "max_tool_calls",
			max_tools_calls: "max_tool_calls",
			temperature: "temperature",
			top_p: "top_p",
			top_k: "top_k",
			min_p: "min_p",
			repetition_penalty: "repetition_penalty",
			respond_as: "respond_as",
			min_tokens: "min_tokens",
			custom_token_bans: "custom_token_bans",
			dynatemp_mode: "dynatemp_mode",
			dynatemp_min: "dynatemp_min",
			dynatemp_max: "dynatemp_max",
			dynatemp_exponent: "dynatemp_exponent",
			epsilon_cutoff: "epsilon_cutoff",
			top_a: "top_a",
			typical_p: "typical_p",
			eta_cutoff: "eta_cutoff",
			tfs: "tfs",
			smoothing_factor: "smoothing_factor",
			smoothing_curve: "smoothing_curve",
			xtc_probability: "xtc_probability",
			xtc_threshold: "xtc_threshold",
			dry_multiplier: "dry_multiplier",
			dry_base: "dry_base",
			dry_allowed_length: "dry_allowed_length",
			dry_range: "dry_range",
			dry_sequence_breakers: "dry_sequence_breakers",
			ignore_eos: "ignore_eos",
			custom_timeout: "custom_timeout",
			allow_logging: "allow_logging",
			max_tokens: "max_tokens",
			max_output_tokens: "max_tokens",
			max_completion_tokens: "max_tokens",
			stop: "stop",
			logit_bias: "logit_bias",
			seed: "seed",
			response_format: "response_format",
			modalities: "modalities",
			response_modalities: "modalities",
			responseModalities: "modalities",
			image_config: "image_config",
			imageConfig: "image_config",
			logprobs: "logprobs",
			top_logprobs: "top_logprobs",
			presence_penalty: "presence_penalty",
			frequency_penalty: "frequency_penalty",
			metadata: "metadata",
			reasoning: "reasoning",
			reasoning_effort: "reasoning.effort",
			thinking: "reasoning",
			reasoning_split: "reasoning_split",
			service_tier: "service_tier",
			prompt_cache_key: "prompt_cache_key",
			prompt_cache_retention: "prompt_cache_retention",
			prompt_cache_options: "prompt_cache_options",
			provider_options: "provider_options",
			providerOptions: "provider_options",
			web_search_options: "web_search_options",
			webSearchOptions: "web_search_options",
			mcp_servers: "mcp_servers",
			safety_identifier: "safety_identifier",
		},
	},
	responses: {
		allowedTopLevel: new Set([
			"model",
			"models",
			"input",
			"input_items",
			"messages",
			"usage",
			"conversation",
			"include",
			"instructions",
			"max_output_tokens",
			"max_completion_tokens",
			"max_tokens",
			"max_tool_calls",
			"max_tools_calls",
			"metadata",
			"plugins",
			"session_id",
			"trace",
			"parallel_tool_calls",
			"previous_response_id",
			"frequency_penalty",
			"presence_penalty",
			"prompt",
			"prompt_cache_key",
			"prompt_cache_retention",
			"prompt_cache_options",
			"provider_options",
			"providerOptions",
			"modalities",
			"response_modalities",
			"responseModalities",
			"image_config",
			"imageConfig",
			"reasoning",
			"reasoning_effort",
			"thinking",
			"reasoning_split",
			"safety_identifier",
			"service_tier",
			"store",
			"stream",
			"stream_options",
			"temperature",
			"text",
			"response_format",
			"tool_choice",
			"tools",
			"web_search_options",
			"webSearchOptions",
			"top_logprobs",
			"top_p",
			"top_k",
			"min_p",
			"truncation",
			"background",
			"user",
			"meta",
			"echo_upstream_request",
			"debug",
			"provider",
			"routing",
			"stop",
			"logit_bias",
			"logprobs",
			"seed",
		]),
		keyToCanonicalParam: {
			tools: "tools",
			tool_choice: "tool_choice",
			parallel_tool_calls: "parallel_tool_calls",
			max_tool_calls: "max_tool_calls",
			max_tools_calls: "max_tool_calls",
			temperature: "temperature",
			top_p: "top_p",
			top_k: "top_k",
			min_p: "min_p",
			max_tokens: "max_tokens",
			max_output_tokens: "max_tokens",
			max_completion_tokens: "max_tokens",
			stop: "stop",
			logit_bias: "logit_bias",
			seed: "seed",
			response_format: "response_format",
			modalities: "modalities",
			response_modalities: "modalities",
			responseModalities: "modalities",
			image_config: "image_config",
			imageConfig: "image_config",
			logprobs: "logprobs",
			top_logprobs: "top_logprobs",
			presence_penalty: "presence_penalty",
			frequency_penalty: "frequency_penalty",
			metadata: "metadata",
			reasoning: "reasoning",
			reasoning_effort: "reasoning.effort",
			thinking: "reasoning",
			reasoning_split: "reasoning_split",
			service_tier: "service_tier",
			prompt_cache_key: "prompt_cache_key",
			prompt_cache_retention: "prompt_cache_retention",
			prompt_cache_options: "prompt_cache_options",
			provider_options: "provider_options",
			providerOptions: "provider_options",
			web_search_options: "web_search_options",
			webSearchOptions: "web_search_options",
			safety_identifier: "safety_identifier",
			background: "background",
			instructions: "instructions",
		},
	},
	messages: {
		allowedTopLevel: new Set([
			"model",
			"messages",
			"system",
			"usage",
			"max_tokens",
			"max_output_tokens",
			"temperature",
			"top_p",
			"top_k",
			"stream",
			"tools",
			"tool_choice",
			"metadata",
			"service_tier",
			"modalities",
			"response_modalities",
			"responseModalities",
			"image_config",
			"imageConfig",
			"stop_sequences",
			"thinking",
			"web_search_options",
			"webSearchOptions",
			"plugins",
			"meta",
			"echo_upstream_request",
			"debug",
			"provider",
			"routing",
		]),
		keyToCanonicalParam: {
			tools: "tools",
			tool_choice: "tool_choice",
			max_tokens: "max_tokens",
			max_output_tokens: "max_tokens",
			temperature: "temperature",
			top_p: "top_p",
			top_k: "top_k",
			stop_sequences: "stop",
			modalities: "modalities",
			response_modalities: "modalities",
			responseModalities: "modalities",
			image_config: "image_config",
			imageConfig: "image_config",
			thinking: "reasoning",
			metadata: "metadata",
			service_tier: "service_tier",
			web_search_options: "web_search_options",
			webSearchOptions: "web_search_options",
			prompt_cache_key: "prompt_cache_key",
			prompt_cache_retention: "prompt_cache_retention",
			provider_options: "provider_options",
			providerOptions: "provider_options",
			safety_identifier: "safety_identifier",
		},
	},
};

const CAPABILITY_PARAM_ALIASES: Record<string, string[]> = {
	max_tokens: ["max_tokens", "max_output_tokens", "max_completion_tokens"],
	max_tool_calls: ["max_tool_calls", "max_tools_calls"],
	stop: ["stop", "stop_sequences"],
	reasoning: ["reasoning", "thinking"],
	service_tier: ["service_tier", "serviceTier"],
	response_format: ["response_format", "text", "structured_outputs"],
	modalities: ["modalities", "response_modalities", "responseModalities"],
	image_config: ["image_config", "imageConfig"],
	web_search_options: ["web_search_options", "webSearchOptions"],
	provider_options: ["provider_options", "providerOptions"],
	prompt_cache_key: ["prompt_cache_key"],
	prompt_cache_retention: ["prompt_cache_retention"],
	prompt_cache_options: ["prompt_cache_options"],
	logprobs: ["logprobs", "top_logprobs"],
	top_logprobs: ["top_logprobs", "logprobs"],
};

function paramPathCandidates(paramPath: string): string[] {
	const trimmed = paramPath.trim();
	if (!trimmed) return [];
	const segments = trimmed.split(".").filter(Boolean);
	const [root, ...rest] = segments;
	if (!root) return [];
	const aliases = CAPABILITY_PARAM_ALIASES[root] ?? [root];
	const suffix = rest.length > 0 ? `.${rest.join(".")}` : "";
	return Array.from(new Set(aliases.map((alias) => `${alias}${suffix}`)));
}

export function textEndpointRegistryFor(
	endpoint: Endpoint,
): EndpointParamRegistry | null {
	if (
		endpoint === "chat.completions" ||
		endpoint === "responses" ||
		endpoint === "messages"
	) {
		return TEXT_ENDPOINT_REGISTRY[endpoint];
	}
	return null;
}

/**
 * Returns the canonical parameter IDs understood by the gateway's text
 * endpoint mapping registry. Data tooling uses this to avoid advertising
 * upstream-only fields that cannot be represented in the IR.
 */
export function gatewayMappedParamIds(): Set<string> {
	const ids = new Set<string>();
	for (const endpoint of ["chat.completions", "responses", "messages"] as const) {
		const registry = TEXT_ENDPOINT_REGISTRY[endpoint];
		for (const canonical of Object.values(registry.keyToCanonicalParam)) ids.add(canonical);
	}
	for (const id of [
		"include_reasoning",
		"reasoning.effort",
		"reasoning.enabled",
		"reasoning.mode",
		"reasoning_effort",
		"structured_outputs",
		"verbosity",
	]) ids.add(id);
	return ids;
}

export function expandCapabilityParamAliases(rootParam: string): string[] {
	return CAPABILITY_PARAM_ALIASES[rootParam] ?? [rootParam];
}

export function isAlwaysSupportedParam(endpoint: Endpoint, param: string): boolean {
	if (param === "modalities") return true;
	if (endpoint === "messages" && param === "max_tokens") return true;
	return false;
}

export function resolveProviderParamSupportOverride(
	providerId: string,
	paramPath: string,
): boolean | undefined {
	const candidates = paramPathCandidates(paramPath);
	if (!candidates.length) return undefined;
	return resolveTextProviderParamPolicyOverride({
		providerId,
		paramPathCandidates: candidates,
	});
}
