begin;
insert into public.v2_service_tiers(service_tier_slug,display_name) values('standard','Standard') on conflict do nothing;
insert into public.v2_providers(provider_slug,name,status,metadata) values('catalog-review-test','Review test','not_ready','{"self_serve":{"provider_review_status":"approved"}}');
insert into public.provider_catalog_sources(provider_slug,management_mode) values('catalog-review-test','managed');
do $test$
declare request_run uuid:=gen_random_uuid(); request_id uuid; lease_id uuid:=gen_random_uuid();
document jsonb:='[{"id":"catalog-review-test/model","name":"Review model","providerModelSlug":"upstream","inputModalities":["text"],"outputModalities":["text"],"availability":"not_ready","capabilities":[{"id":"responses","parameters":[]}],"pricing":[]}]';
begin
  assert not has_table_privilege('authenticated','public.provider_catalog_model_requests','insert');
  assert not has_function_privilege('authenticated','public.review_provider_catalog_model_request(uuid,text,text,uuid,timestamptz)','execute');
  insert into public.provider_catalog_sync_runs(id,provider_slug,trigger) values(request_run,'catalog-review-test','webhook');
  perform public.apply_provider_catalog_snapshot('catalog-review-test',request_run,document);
  assert not exists(select 1 from public.v2_models where model_slug='catalog-review-test/model');
  assert not exists(select 1 from public.v2_model_provider_routes where provider_slug='catalog-review-test');
  select id into request_id from public.provider_catalog_model_requests where provider_slug='catalog-review-test';
  assert request_id is not null;
  perform public.apply_provider_catalog_snapshot('catalog-review-test',request_run,document);
  assert (select count(*)=1 from public.provider_catalog_model_requests where provider_slug='catalog-review-test');
  assert (select count(*)=1 from public.claim_provider_model_notifications(lease_id));
  assert (select count(*)=0 from public.claim_provider_model_notifications(gen_random_uuid()));
  perform public.review_provider_catalog_model_request(request_id,'rejected','Insufficient evidence',null);
  perform public.apply_provider_catalog_snapshot('catalog-review-test',request_run,document);
  assert (select status='rejected' from public.provider_catalog_model_requests where id=request_id);
  assert (select review_status='rejected' and review_summary->>'pending'='0' and review_summary->>'rejected'='1' from public.provider_catalog_sync_runs where id=request_run);
  assert not exists(select 1 from public.v2_models where model_slug='catalog-review-test/model');
  perform public.review_provider_catalog_model_request(request_id,'needs_changes','Clarify model identity',null);
  perform public.apply_provider_catalog_snapshot('catalog-review-test',request_run,document);
  assert (select review_status='needs_changes' and review_summary->>'pending'='0' and review_summary->>'needs_changes'='1' from public.provider_catalog_sync_runs where id=request_run);
  perform public.review_provider_catalog_model_request(request_id,'approved',null,null);
  assert exists(select 1 from public.v2_models where model_slug='catalog-review-test/model' and hidden);
  assert (select refresh_requested from public.provider_catalog_sources where provider_slug='catalog-review-test');
  perform public.apply_provider_catalog_snapshot('catalog-review-test',request_run,document);
  assert (select decision='approved' from public.provider_catalog_sync_models where run_id=request_run and model_slug='catalog-review-test/model');
  -- A second proposal is withdrawn when it disappears from the latest snapshot.
  document:=jsonb_set(document,'{0,id}','"catalog-review-test/withdrawn"');
  perform public.apply_provider_catalog_snapshot('catalog-review-test',request_run,document);
  perform public.apply_provider_catalog_snapshot('catalog-review-test',request_run,'[]');
  assert (select status='withdrawn' from public.provider_catalog_model_requests where model_slug='catalog-review-test/withdrawn');
end $test$;
rollback;
