export type CloudflareColo = { code: string; location: string; continent: string };

/** Cloudflare's published colo/IATA catalogue, grouped in the UI by continent. */
export const CLOUDFLARE_COLOS: CloudflareColo[] = [
	{"code":"AAE","location":"Annaba, Algeria","continent":"Africa"},
	{"code":"ABJ","location":"Abidjan, Ivory Coast","continent":"Africa"},
	{"code":"ABQ","location":"Albuquerque, United States","continent":"North America"},
	{"code":"ACC","location":"Accra, Ghana","continent":"Africa"},
	{"code":"ACX","location":"Xingyi, China","continent":"Asia"},
	{"code":"ADB","location":"Izmir, Turkey","continent":"Europe"},
	{"code":"ADD","location":"Addis Ababa, Ethiopia","continent":"Africa"},
	{"code":"ADL","location":"Adelaide, Australia","continent":"Oceania"},
	{"code":"AGR","location":"Agra, India","continent":"Asia"},
	{"code":"AKL","location":"Auckland, New Zealand","continent":"Oceania"},
	{"code":"AKX","location":"Aktobe, Kazakhstan","continent":"Europe"},
	{"code":"ALA","location":"Almaty, Kazakhstan","continent":"Europe"},
	{"code":"ALG","location":"Algiers, Algeria","continent":"Africa"},
	{"code":"AMD","location":"Ahmedabad, India","continent":"Asia"},
	{"code":"AMM","location":"Amman, Jordan","continent":"Asia"},
	{"code":"AMS","location":"Amsterdam, Netherlands","continent":"Europe"},
	{"code":"ANC","location":"Anchorage, United States","continent":"North America"},
	{"code":"ARI","location":"Arica, Chile","continent":"South America"},
	{"code":"ARN","location":"Stockholm, Sweden","continent":"Europe"},
	{"code":"ARU","location":"Aracatuba, Brazil","continent":"South America"},
	{"code":"ASK","location":"Yamoussoukro, Ivory Coast","continent":"Africa"},
	{"code":"ASU","location":"Asunción, Paraguay","continent":"South America"},
	{"code":"ATH","location":"Athens, Greece","continent":"Europe"},
	{"code":"ATL","location":"Atlanta, United States","continent":"North America"},
	{"code":"AUS","location":"Austin, United States","continent":"North America"},
	{"code":"BAH","location":"Manama, Bahrain","continent":"Asia"},
	{"code":"BAQ","location":"Barranquilla, Colombia","continent":"South America"},
	{"code":"BBI","location":"Bhubaneswar, India","continent":"Asia"},
	{"code":"BCN","location":"Barcelona, Spain","continent":"Europe"},
	{"code":"BEG","location":"Belgrade, Serbia","continent":"Europe"},
	{"code":"BEL","location":"Belém, Brazil","continent":"South America"},
	{"code":"BEY","location":"Beirut, Lebanon","continent":"Asia"},
	{"code":"BGI","location":"Bridgetown, Barbados","continent":"North America"},
	{"code":"BGR","location":"Bangor, United States","continent":"North America"},
	{"code":"BGW","location":"Baghdad, Iraq","continent":"Asia"},
	{"code":"BHY","location":"Beihai, China","continent":"Asia"},
	{"code":"BKK","location":"Bangkok, Thailand","continent":"Asia"},
	{"code":"BLR","location":"Bangalore, India","continent":"Asia"},
	{"code":"BNA","location":"Nashville, United States","continent":"North America"},
	{"code":"BNE","location":"Brisbane, Australia","continent":"Oceania"},
	{"code":"BNU","location":"Blumenau, Brazil","continent":"South America"},
	{"code":"BOD","location":"Bordeaux, France","continent":"Europe"},
	{"code":"BOG","location":"Bogotá, Colombia","continent":"South America"},
	{"code":"BOM","location":"Mumbai, India","continent":"Asia"},
	{"code":"BOS","location":"Boston, United States","continent":"North America"},
	{"code":"BRU","location":"Brussels, Belgium","continent":"Europe"},
	{"code":"BSB","location":"Brasilia, Brazil","continent":"South America"},
	{"code":"BSR","location":"Basra, Iraq","continent":"Asia"},
	{"code":"BTS","location":"Bratislava, Slovakia","continent":"Europe"},
	{"code":"BUD","location":"Budapest, Hungary","continent":"Europe"},
	{"code":"BUF","location":"Buffalo, United States","continent":"North America"},
	{"code":"BWN","location":"Bandar Seri Begawan, Brunei","continent":"Asia"},
	{"code":"CAI","location":"Cairo, Egypt","continent":"Africa"},
	{"code":"CAN","location":"Guangzhou, China","continent":"Asia"},
	{"code":"CAW","location":"Campos dos Goytacazes, Brazil","continent":"South America"},
	{"code":"CBR","location":"Canberra, Australia","continent":"Oceania"},
	{"code":"CCP","location":"Concepción, Chile","continent":"South America"},
	{"code":"CCU","location":"Kolkata, India","continent":"Asia"},
	{"code":"CDG","location":"Paris, France","continent":"Europe"},
	{"code":"CEB","location":"Cebu, Philippines","continent":"Asia"},
	{"code":"CFC","location":"Caçador, Brazil","continent":"South America"},
	{"code":"CGB","location":"Cuiaba, Brazil","continent":"South America"},
	{"code":"CGD","location":"Changde, China","continent":"Asia"},
	{"code":"CGK","location":"Jakarta, Indonesia","continent":"Asia"},
	{"code":"CGO","location":"Zhengzhou, China","continent":"Asia"},
	{"code":"CGP","location":"Chittagong, Bangladesh","continent":"Asia"},
	{"code":"CGY","location":"Cagayan de Oro, Philippines","continent":"Asia"},
	{"code":"CHC","location":"Christchurch, New Zealand","continent":"Oceania"},
	{"code":"CJB","location":"Coimbatore, India","continent":"Asia"},
	{"code":"CKG","location":"Chongqing, China","continent":"Asia"},
	{"code":"CLE","location":"Cleveland, United States","continent":"North America"},
	{"code":"CLO","location":"Cali, Colombia","continent":"South America"},
	{"code":"CLT","location":"Charlotte, United States","continent":"North America"},
	{"code":"CMB","location":"Colombo, Sri Lanka","continent":"Asia"},
	{"code":"CMH","location":"Columbus, United States","continent":"North America"},
	{"code":"CNF","location":"Belo Horizonte, Brazil","continent":"South America"},
	{"code":"CNN","location":"Kannur, India","continent":"Asia"},
	{"code":"CNX","location":"Chiang Mai, Thailand","continent":"Asia"},
	{"code":"COK","location":"Kochi, India","continent":"Asia"},
	{"code":"COR","location":"Córdoba, Argentina","continent":"South America"},
	{"code":"CPH","location":"Copenhagen, Denmark","continent":"Europe"},
	{"code":"CPT","location":"Cape Town, South Africa","continent":"Africa"},
	{"code":"CRK","location":"Tarlac City, Philippines","continent":"Asia"},
	{"code":"CSX","location":"Changsha, China","continent":"Asia"},
	{"code":"CTU","location":"Chengdu, China","continent":"Asia"},
	{"code":"CVG","location":"Cincinnati, United States","continent":"North America"},
	{"code":"CWB","location":"Curitiba, Brazil","continent":"South America"},
	{"code":"CZL","location":"Constantine, Algeria","continent":"Africa"},
	{"code":"CZX","location":"Changzhou, China","continent":"Asia"},
	{"code":"DAC","location":"Dhaka, Bangladesh","continent":"Asia"},
	{"code":"DAD","location":"Da Nang, Vietnam","continent":"Asia"},
	{"code":"DAR","location":"Dar Es Salaam, Tanzania","continent":"Africa"},
	{"code":"DEL","location":"New Delhi, India","continent":"Asia"},
	{"code":"DEN","location":"Denver, United States","continent":"North America"},
	{"code":"DFW","location":"Dallas, United States","continent":"North America"},
	{"code":"DKR","location":"Dakar, Senegal","continent":"Africa"},
	{"code":"DLA","location":"Douala, Cameroon","continent":"Africa"},
	{"code":"DLC","location":"Dalian, China","continent":"Asia"},
	{"code":"DME","location":"Moscow, Russia","continent":"Europe"},
	{"code":"DMM","location":"Dammam, Saudi Arabia","continent":"Asia"},
	{"code":"DOH","location":"Doha, Qatar","continent":"Asia"},
	{"code":"DPS","location":"Denpasar, Indonesia","continent":"Asia"},
	{"code":"DTW","location":"Detroit, United States","continent":"North America"},
	{"code":"DUB","location":"Dublin, Ireland","continent":"Europe"},
	{"code":"DUR","location":"Durban, South Africa","continent":"Africa"},
	{"code":"DUS","location":"Düsseldorf, Germany","continent":"Europe"},
	{"code":"DXB","location":"Dubai, United Arab Emirates","continent":"Asia"},
	{"code":"EBB","location":"Kampala, Uganda","continent":"Africa"},
	{"code":"EBL","location":"Erbil, Iraq","continent":"Asia"},
	{"code":"EDI","location":"Edinburgh, United Kingdom","continent":"Europe"},
	{"code":"EVN","location":"Yerevan, Armenia","continent":"Asia"},
	{"code":"EWR","location":"Newark, United States","continent":"North America"},
	{"code":"EZE","location":"Buenos Aires, Argentina","continent":"South America"},
	{"code":"FCO","location":"Rome, Italy","continent":"Europe"},
	{"code":"FIH","location":"Kinshasa, DR Congo","continent":"Africa"},
	{"code":"FLN","location":"Florianopolis, Brazil","continent":"South America"},
	{"code":"FOC","location":"Fuzhou, China","continent":"Asia"},
	{"code":"FOR","location":"Fortaleza, Brazil","continent":"South America"},
	{"code":"FRA","location":"Frankfurt, Germany","continent":"Europe"},
	{"code":"FRU","location":"Bishkek, Kyrgyzstan","continent":"Asia"},
	{"code":"FSD","location":"Sioux Falls, United States","continent":"North America"},
	{"code":"FUK","location":"Fukuoka, Japan","continent":"Asia"},
	{"code":"FUO","location":"Foshan, China","continent":"Asia"},
	{"code":"GBE","location":"Gaborone, Botswana","continent":"Africa"},
	{"code":"GDL","location":"Guadalajara, Mexico","continent":"North America"},
	{"code":"GEO","location":"Georgetown, Guyana","continent":"South America"},
	{"code":"GIG","location":"Rio de Janeiro, Brazil","continent":"South America"},
	{"code":"GND","location":"St. George's, Grenada","continent":"South America"},
	{"code":"GOT","location":"Gothenburg, Sweden","continent":"Europe"},
	{"code":"GRU","location":"São Paulo, Brazil","continent":"South America"},
	{"code":"GUA","location":"Guatemala City, Guatemala","continent":"North America"},
	{"code":"GUM","location":"Hagatna, Guam","continent":"Asia"},
	{"code":"GVA","location":"Geneva, Switzerland","continent":"Europe"},
	{"code":"GYD","location":"Baku, Azerbaijan","continent":"Asia"},
	{"code":"GYE","location":"Guayaquil, Ecuador","continent":"South America"},
	{"code":"GYN","location":"Goiânia, Brazil","continent":"South America"},
	{"code":"HAK","location":"Haikou, China","continent":"Asia"},
	{"code":"HAM","location":"Hamburg, Germany","continent":"Europe"},
	{"code":"HAN","location":"Hanoi, Vietnam","continent":"Asia"},
	{"code":"HBA","location":"Hobart, Australia","continent":"Oceania"},
	{"code":"HEL","location":"Helsinki, Finland","continent":"Europe"},
	{"code":"HFA","location":"Haifa, Israel","continent":"Asia"},
	{"code":"HFE","location":"Huainan, China","continent":"Asia"},
	{"code":"HGH","location":"Shaoxing, China","continent":"Asia"},
	{"code":"HKG","location":"Hong Kong","continent":"Asia"},
	{"code":"HNL","location":"Honolulu, United States","continent":"North America"},
	{"code":"HRE","location":"Harare, Zimbabwe","continent":"Africa"},
	{"code":"HYD","location":"Hyderabad, India","continent":"Asia"},
	{"code":"HYN","location":"Taizhou, China","continent":"Asia"},
	{"code":"IAD","location":"Ashburn, United States","continent":"North America"},
	{"code":"IAH","location":"Houston, United States","continent":"North America"},
	{"code":"ICN","location":"Seoul, South Korea","continent":"Asia"},
	{"code":"IND","location":"Indianapolis, United States","continent":"North America"},
	{"code":"ISB","location":"Islamabad, Pakistan","continent":"Asia"},
	{"code":"IST","location":"Istanbul, Turkey","continent":"Europe"},
	{"code":"ISU","location":"Sulaymaniyah, Iraq","continent":"Asia"},
	{"code":"ITJ","location":"Itajai, Brazil","continent":"South America"},
	{"code":"IXC","location":"Chandigarh, India","continent":"Asia"},
	{"code":"JAX","location":"Jacksonville, United States","continent":"North America"},
	{"code":"JDO","location":"Juazeiro do Norte, Brazil","continent":"South America"},
	{"code":"JED","location":"Jeddah, Saudi Arabia","continent":"Asia"},
	{"code":"JHB","location":"Johor Bahru, Malaysia","continent":"Asia"},
	{"code":"JIB","location":"Djibouti City","continent":"Africa"},
	{"code":"JNB","location":"Johannesburg, South Africa","continent":"Africa"},
	{"code":"JOG","location":"Yogyakarta, Indonesia","continent":"Asia"},
	{"code":"JOI","location":"Joinville, Brazil","continent":"South America"},
	{"code":"JRG","location":"Sambalpur, India","continent":"Asia"},
	{"code":"JSR","location":"Jashore, Bangladesh","continent":"Asia"},
	{"code":"JXG","location":"Jiaxing, China","continent":"Asia"},
	{"code":"KBP","location":"Kyiv, Ukraine","continent":"Europe"},
	{"code":"KCH","location":"Kuching, Malaysia","continent":"Asia"},
	{"code":"KEF","location":"Reykjavík, Iceland","continent":"Europe"},
	{"code":"KGL","location":"Kigali, Rwanda","continent":"Africa"},
	{"code":"KHH","location":"Kaohsiung City","continent":"Asia"},
	{"code":"KHI","location":"Karachi, Pakistan","continent":"Asia"},
	{"code":"KHN","location":"Xinyu, China","continent":"Asia"},
	{"code":"KIN","location":"Kingston, Jamaica","continent":"North America"},
	{"code":"KIV","location":"Chișinău, Moldova","continent":"Europe"},
	{"code":"KIX","location":"Osaka, Japan","continent":"Asia"},
	{"code":"KJA","location":"Krasnoyarsk, Russia","continent":"Europe"},
	{"code":"KMG","location":"Kunming, China","continent":"Asia"},
	{"code":"KNU","location":"Kanpur, India","continent":"Asia"},
	{"code":"KTM","location":"Kathmandu, Nepal","continent":"Asia"},
	{"code":"KUL","location":"Kuala Lumpur, Malaysia","continent":"Asia"},
	{"code":"KWE","location":"Guiyang, China","continent":"Asia"},
	{"code":"KWI","location":"Kuwait City, Kuwait","continent":"Asia"},
	{"code":"LAD","location":"Luanda, Angola","continent":"Africa"},
	{"code":"LAS","location":"Las Vegas, United States","continent":"North America"},
	{"code":"LAX","location":"Los Angeles, United States","continent":"North America"},
	{"code":"LCA","location":"Nicosia, Cyprus","continent":"Europe"},
	{"code":"LED","location":"Saint Petersburg, Russia","continent":"Europe"},
	{"code":"LHE","location":"Lahore, Pakistan","continent":"Asia"},
	{"code":"LHR","location":"London, United Kingdom","continent":"Europe"},
	{"code":"LHW","location":"Lanzhou, China","continent":"Asia"},
	{"code":"LIM","location":"Lima, Peru","continent":"South America"},
	{"code":"LIS","location":"Lisbon, Portugal","continent":"Europe"},
	{"code":"LJU","location":"Ljubljana, Slovenia","continent":"Europe"},
	{"code":"LLK","location":"Astara, Azerbaijan","continent":"Asia"},
	{"code":"LLW","location":"Lilongwe, Malawi","continent":"Africa"},
	{"code":"LOS","location":"Lagos, Nigeria","continent":"Africa"},
	{"code":"LPB","location":"La Paz, Bolivia","continent":"South America"},
	{"code":"LUN","location":"Lusaka, Zambia","continent":"Africa"},
	{"code":"LUX","location":"Luxembourg City, Luxembourg","continent":"Europe"},
	{"code":"LYA","location":"Luoyang, China","continent":"Asia"},
	{"code":"LYS","location":"Lyon, France","continent":"Europe"},
	{"code":"MAA","location":"Chennai, India","continent":"Asia"},
	{"code":"MAD","location":"Madrid, Spain","continent":"Europe"},
	{"code":"MAN","location":"Manchester, United Kingdom","continent":"Europe"},
	{"code":"MAO","location":"Manaus, Brazil","continent":"South America"},
	{"code":"MBA","location":"Mombasa, Kenya","continent":"Africa"},
	{"code":"MCI","location":"Kansas City, United States","continent":"North America"},
	{"code":"MCT","location":"Muscat, Oman","continent":"Asia"},
	{"code":"MDE","location":"Medellín, Colombia","continent":"South America"},
	{"code":"MEL","location":"Melbourne, Australia","continent":"Oceania"},
	{"code":"MEM","location":"Memphis, United States","continent":"North America"},
	{"code":"MEX","location":"Mexico City, Mexico","continent":"North America"},
	{"code":"MFE","location":"McAllen, United States","continent":"North America"},
	{"code":"MFM","location":"Macau","continent":"Asia"},
	{"code":"MIA","location":"Miami, United States","continent":"North America"},
	{"code":"MLA","location":"Santa Venera, Malta","continent":"Europe"},
	{"code":"MLE","location":"Malé, Maldives","continent":"Asia"},
	{"code":"MLG","location":"Malang, Indonesia","continent":"Asia"},
	{"code":"MNL","location":"Manila, Philippines","continent":"Asia"},
	{"code":"MPM","location":"Maputo, Mozambique","continent":"Africa"},
	{"code":"MRS","location":"Marseille, France","continent":"Europe"},
	{"code":"MRU","location":"Port Louis, Mauritius","continent":"Africa"},
	{"code":"MSP","location":"Minneapolis, United States","continent":"North America"},
	{"code":"MSQ","location":"Minsk, Belarus","continent":"Europe"},
	{"code":"MUC","location":"Munich, Germany","continent":"Europe"},
	{"code":"MXP","location":"Milan, Italy","continent":"Europe"},
	{"code":"NAG","location":"Nagpur, India","continent":"Asia"},
	{"code":"NBO","location":"Nairobi, Kenya","continent":"Africa"},
	{"code":"NJF","location":"Najaf, Iraq","continent":"Asia"},
	{"code":"NNG","location":"Nanning, China","continent":"Asia"},
	{"code":"NOU","location":"Noumea, New Caledonia","continent":"Oceania"},
	{"code":"NQN","location":"Neuquén, Argentina","continent":"South America"},
	{"code":"NQZ","location":"Astana, Kazakhstan","continent":"Europe"},
	{"code":"NRT","location":"Tokyo, Japan","continent":"Asia"},
	{"code":"NVT","location":"Timbó, Brazil","continent":"South America"},
	{"code":"OKA","location":"Naha, Japan","continent":"Asia"},
	{"code":"OKC","location":"Oklahoma City, United States","continent":"North America"},
	{"code":"OMA","location":"Omaha, United States","continent":"North America"},
	{"code":"ORD","location":"Chicago, United States","continent":"North America"},
	{"code":"ORF","location":"Norfolk, United States","continent":"North America"},
	{"code":"ORK","location":"Cork, Ireland","continent":"Europe"},
	{"code":"ORN","location":"Oran, Algeria","continent":"Africa"},
	{"code":"OSL","location":"Oslo, Norway","continent":"Europe"},
	{"code":"OTP","location":"Bucharest, Romania","continent":"Europe"},
	{"code":"OUA","location":"Ouagadougou, Burkina Faso","continent":"Africa"},
	{"code":"PAT","location":"Patna, India","continent":"Asia"},
	{"code":"PBH","location":"Thimphu, Bhutan","continent":"Asia"},
	{"code":"PBM","location":"Paramaribo, Suriname","continent":"South America"},
	{"code":"PDX","location":"Portland, United States","continent":"North America"},
	{"code":"PER","location":"Perth, Australia","continent":"Oceania"},
	{"code":"PHL","location":"Philadelphia, United States","continent":"North America"},
	{"code":"PHX","location":"Phoenix, United States","continent":"North America"},
	{"code":"PIT","location":"Pittsburgh, United States","continent":"North America"},
	{"code":"PKX","location":"Langfang, China","continent":"Asia"},
	{"code":"PMO","location":"Palermo, Italy","continent":"Europe"},
	{"code":"PMW","location":"Palmas, Brazil","continent":"South America"},
	{"code":"PNH","location":"Phnom Penh, Cambodia","continent":"Asia"},
	{"code":"PNQ","location":"Pune, India","continent":"Asia"},
	{"code":"POA","location":"Porto Alegre, Brazil","continent":"South America"},
	{"code":"POS","location":"Port of Spain, Trinidad and Tobago","continent":"South America"},
	{"code":"PPT","location":"Tahiti, French Polynesia","continent":"Oceania"},
	{"code":"PRG","location":"Prague, Czech Republic","continent":"Europe"},
	{"code":"PTY","location":"Panama City, Panama","continent":"South America"},
	{"code":"QRO","location":"Queretaro, Mexico","continent":"North America"},
	{"code":"QWJ","location":"Americana, Brazil","continent":"South America"},
	{"code":"RAO","location":"Ribeirao Preto, Brazil","continent":"South America"},
	{"code":"RDU","location":"Durham, United States","continent":"North America"},
	{"code":"REC","location":"Recife, Brazil","continent":"South America"},
	{"code":"RIC","location":"Richmond, United States","continent":"North America"},
	{"code":"RIX","location":"Riga, Latvia","continent":"Europe"},
	{"code":"RUH","location":"Riyadh, Saudi Arabia","continent":"Asia"},
	{"code":"RUN","location":"Saint-Denis, Réunion","continent":"Africa"},
	{"code":"SAN","location":"San Diego, United States","continent":"North America"},
	{"code":"SAP","location":"San Pedro Sula, Honduras","continent":"South America"},
	{"code":"SAT","location":"San Antonio, United States","continent":"North America"},
	{"code":"SCL","location":"Santiago, Chile","continent":"South America"},
	{"code":"SDQ","location":"Santo Domingo, Dominican Republic","continent":"North America"},
	{"code":"SEA","location":"Seattle, United States","continent":"North America"},
	{"code":"SFO","location":"San Francisco, United States","continent":"North America"},
	{"code":"SGN","location":"Ho Chi Minh City, Vietnam","continent":"Asia"},
	{"code":"SHA","location":"Shanghai, China","continent":"Asia"},
	{"code":"SIN","location":"Singapore","continent":"Asia"},
	{"code":"SJC","location":"San Jose, United States","continent":"North America"},
	{"code":"SJK","location":"São José dos Campos, Brazil","continent":"South America"},
	{"code":"SJO","location":"San José, Costa Rica","continent":"South America"},
	{"code":"SJP","location":"São José do Rio Preto, Brazil","continent":"South America"},
	{"code":"SJU","location":"San Juan, Puerto Rico","continent":"North America"},
	{"code":"SJW","location":"Hengshui, China","continent":"Asia"},
	{"code":"SKG","location":"Thessaloniki, Greece","continent":"Europe"},
	{"code":"SKP","location":"Skopje, North Macedonia","continent":"Europe"},
	{"code":"SLC","location":"Salt Lake City, United States","continent":"North America"},
	{"code":"SMF","location":"Sacramento, United States","continent":"North America"},
	{"code":"SOD","location":"Sorocaba, Brazil","continent":"South America"},
	{"code":"SOF","location":"Sofia, Bulgaria","continent":"Europe"},
	{"code":"SSA","location":"Salvador, Brazil","continent":"South America"},
	{"code":"STI","location":"Santiago de los Caballeros, Dominican Republic","continent":"North America"},
	{"code":"STL","location":"St. Louis, United States","continent":"North America"},
	{"code":"STR","location":"Stuttgart, Germany","continent":"Europe"},
	{"code":"SUV","location":"Suva, Fiji","continent":"Oceania"},
	{"code":"SVX","location":"Yekaterinburg, Russia","continent":"Europe"},
	{"code":"SYD","location":"Sydney, Australia","continent":"Oceania"},
	{"code":"SZX","location":"Shenzhen, China","continent":"Asia"},
	{"code":"TAO","location":"Qingdao, China","continent":"Asia"},
	{"code":"TAS","location":"Tashkent, Uzbekistan","continent":"Asia"},
	{"code":"TBS","location":"Tbilisi, Georgia","continent":"Europe"},
	{"code":"TEN","location":"Tongren, China","continent":"Asia"},
	{"code":"TGU","location":"Tegucigalpa, Honduras","continent":"South America"},
	{"code":"TIA","location":"Tirana, Albania","continent":"Europe"},
	{"code":"TLH","location":"Tallahassee, United States","continent":"North America"},
	{"code":"TLL","location":"Tallinn, Estonia","continent":"Europe"},
	{"code":"TLV","location":"Tel Aviv, Israel","continent":"Asia"},
	{"code":"TNA","location":"Jinan, China","continent":"Asia"},
	{"code":"TNR","location":"Antananarivo, Madagascar","continent":"Africa"},
	{"code":"TPA","location":"Tampa, United States","continent":"North America"},
	{"code":"TPE","location":"Taipei","continent":"Asia"},
	{"code":"TSN","location":"Tianjin, China","continent":"Asia"},
	{"code":"TUN","location":"Tunis, Tunisia","continent":"Africa"},
	{"code":"TXL","location":"Berlin, Germany","continent":"Europe"},
	{"code":"TYN","location":"Yangquan, China","continent":"Asia"},
	{"code":"UDI","location":"Uberlândia, Brazil","continent":"South America"},
	{"code":"UIO","location":"Quito, Ecuador","continent":"South America"},
	{"code":"ULN","location":"Ulaanbaatar, Mongolia","continent":"Asia"},
	{"code":"URT","location":"Surat Thani, Thailand","continent":"Asia"},
	{"code":"VCP","location":"Campinas, Brazil","continent":"South America"},
	{"code":"VIE","location":"Vienna, Austria","continent":"Europe"},
	{"code":"VIX","location":"Vitoria, Brazil","continent":"South America"},
	{"code":"VNO","location":"Vilnius, Lithuania","continent":"Europe"},
	{"code":"VTE","location":"Vientiane, Laos","continent":"Asia"},
	{"code":"WAW","location":"Warsaw, Poland","continent":"Europe"},
	{"code":"WDH","location":"Windhoek, Namibia","continent":"Africa"},
	{"code":"WHU","location":"Wuhu, China","continent":"Asia"},
	{"code":"WLG","location":"Wellington, New Zealand","continent":"Oceania"},
	{"code":"WRO","location":"Wroclaw, Poland","continent":"Europe"},
	{"code":"XAP","location":"Chapeco, Brazil","continent":"South America"},
	{"code":"XFN","location":"Xiangyang, China","continent":"Asia"},
	{"code":"XIY","location":"Baoji, China","continent":"Asia"},
	{"code":"XNH","location":"Nasiriyah, Iraq","continent":"Asia"},
	{"code":"XNN","location":"Xining, China","continent":"Asia"},
	{"code":"YHZ","location":"Halifax, Canada","continent":"North America"},
	{"code":"YOW","location":"Ottawa, Canada","continent":"North America"},
	{"code":"YUL","location":"Montréal, Canada","continent":"North America"},
	{"code":"YVR","location":"Vancouver, Canada","continent":"North America"},
	{"code":"YWG","location":"Winnipeg, Canada","continent":"North America"},
	{"code":"YXE","location":"Saskatoon, Canada","continent":"North America"},
	{"code":"YYC","location":"Calgary, Canada","continent":"North America"},
	{"code":"YYZ","location":"Toronto, Canada","continent":"North America"},
	{"code":"ZAG","location":"Zagreb, Croatia","continent":"Europe"},
	{"code":"ZDM","location":"Ramallah","continent":"Asia"},
	{"code":"ZGN","location":"Zhongshan, China","continent":"Asia"},
	{"code":"ZRH","location":"Zurich, Switzerland","continent":"Europe"},
];

export const CLOUDFLARE_CONTINENTS = ["Africa", "Asia", "Europe", "North America", "Oceania", "South America"] as const;

const CLOUDFLARE_COLO_NAMES = new Map(CLOUDFLARE_COLOS.map((colo) => [colo.code, colo.location]));

export function formatCloudflareColo(code: string): string {
	const normalized = code.trim().toUpperCase();
	const location = CLOUDFLARE_COLO_NAMES.get(normalized);
	return location ? normalized + " (" + location + ")" : normalized;
}
