"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition, type ReactNode } from "react";
import { ChevronLeft, KeyRound, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { createPrivateModelAction, deletePrivateModelAction, updatePrivateModelAction } from "@/app/(dashboard)/settings/workspaces/private-models/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import type { PrivateModelSetting } from "@/lib/fetchers/internal/fetchSettingsPrivateModels";

const BACK = "/settings/workspaces/private-models";
const EMPTY = { model_reference: "", name: "", base_url: "", upstream_model_id: "", credential: "", description: "", context_length: "", max_output_tokens: "", host_provider_id: "", custom_provider_name: "", custom_provider_url: "", routing_policy: "preferred", supports_responses: false, enabled: true };

type Option = { id: string; name: string };
export default function PrivateModelEditor({ mode, initialModel, workspaceNamespace, catalogModels = [], providers = [] }: { mode: "create" | "edit"; initialModel?: PrivateModelSetting; workspaceNamespace: string; catalogModels?: Option[]; providers?: Option[] }) {
	const router = useRouter(); const [pending, startTransition] = useTransition();
	const [providerMode, setProviderMode] = useState<"existing" | "custom">(initialModel?.host_provider_id ? "existing" : "custom");
	const [form, setForm] = useState({ ...EMPTY, name: initialModel?.name ?? "", model_reference: initialModel?.catalog_model_id ?? initialModel?.local_slug ?? initialModel?.model_id.split("/").slice(1).join("/") ?? "", base_url: initialModel?.base_url ?? "", upstream_model_id: initialModel?.upstream_model_id ?? "", description: initialModel?.description ?? "", host_provider_id: initialModel?.host_provider_id ?? "", custom_provider_name: initialModel?.custom_provider_name ?? "", custom_provider_url: initialModel?.custom_provider_url ?? "", routing_policy: initialModel?.routing_policy ?? "preferred", supports_responses: initialModel?.supports_responses ?? false, enabled: initialModel?.enabled ?? true, context_length: initialModel?.context_length?.toString() ?? "", max_output_tokens: initialModel?.max_output_tokens?.toString() ?? "" });
	const set = (key: keyof typeof form, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
	const save = () => startTransition(async () => { try { const payload = { ...form, context_length: form.context_length ? Number(form.context_length) : null, max_output_tokens: form.max_output_tokens ? Number(form.max_output_tokens) : null }; if (mode === "create") await createPrivateModelAction(payload); else if (initialModel) await updatePrivateModelAction(initialModel.id, payload); toast.success(mode === "create" ? "Private model added." : "Private model updated."); router.push(BACK); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "The private model could not be saved."); } });
	const remove = () => initialModel && confirm(`Delete ${initialModel.name}? This cannot be undone.`) && startTransition(async () => { try { await deletePrivateModelAction(initialModel.id); toast.success("Private model deleted."); router.push(BACK); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "The private model could not be deleted."); } });
	return <div className="space-y-6">
		<Button variant="ghost" size="sm" asChild className="-ml-3"><Link href={BACK}><ChevronLeft className="mr-1 size-4" />Back to Private Models</Link></Button>
		<div className="overflow-hidden rounded-xl border">
			<Section title="Identity" description="Attach this deployment to a catalogue model or create a workspace model."><div className="grid gap-4 sm:grid-cols-2"><Field label="Display name"><Input value={form.name} onChange={(e) => set("name", e.target.value)} placeholder="Legal Assistant" /></Field><Field label="Model ID or slug" help={form.model_reference.includes("/") ? (catalogModels.some((item) => item.id === form.model_reference) ? `Attaches as a private provider for ${catalogModels.find((item) => item.id === form.model_reference)?.name}.` : "Only exact catalogue IDs may contain an organisation prefix.") : `A unique catalogue slug attaches automatically; otherwise Phaseo creates ${workspaceNamespace}/${form.model_reference || "model-name"}.`}><Input list="private-model-catalog" className="font-mono" value={form.model_reference} onChange={(e) => set("model_reference", e.target.value.toLowerCase())} placeholder="Search models or enter a new slug" /><datalist id="private-model-catalog">{catalogModels.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</datalist></Field><Field label="Description" className="sm:col-span-2"><Textarea value={form.description ?? ""} onChange={(e) => set("description", e.target.value)} placeholder="What this model is best used for." /></Field></div></Section>
			<Section title="Hosting provider" description="Identify who operates this private deployment."><div className="grid gap-4 sm:grid-cols-2"><Field label="Provider type"><select className="flex h-9 w-full rounded-md border bg-transparent px-3 text-sm" value={providerMode} onChange={(e) => { const next=e.target.value as "existing"|"custom"; setProviderMode(next); if(next==="existing") set("custom_provider_name",""); else set("host_provider_id",""); }}><option value="existing">Existing Phaseo provider</option><option value="custom">Custom provider</option></select></Field>{providerMode === "existing" ? <Field label="Provider"><Input list="private-provider-catalog" value={form.host_provider_id} onChange={(e) => set("host_provider_id", e.target.value.toLowerCase())} placeholder="Search providers" /><datalist id="private-provider-catalog">{providers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</datalist></Field> : <><Field label="Custom provider name"><Input value={form.custom_provider_name} onChange={(e) => set("custom_provider_name", e.target.value)} placeholder="Acme inference" /></Field><Field label="Provider website"><Input value={form.custom_provider_url} onChange={(e) => set("custom_provider_url", e.target.value)} placeholder="https://models.example.com" /></Field></>}<Field label="Routing"><select className="flex h-9 w-full rounded-md border bg-transparent px-3 text-sm" value={form.routing_policy} onChange={(e) => set("routing_policy", e.target.value)}><option value="preferred">Preferred</option><option value="balanced">Normal pool</option><option value="fallback">Fallback only</option></select></Field></div></Section>
			<Section title="Endpoint" description="The OpenAI-compatible deployment Phaseo calls."><div className="grid gap-4 sm:grid-cols-2"><Field label="Base URL"><Input value={form.base_url} onChange={(e) => set("base_url", e.target.value)} placeholder="https://models.example.com/v1" /></Field><Field label="Upstream model ID"><Input className="font-mono" value={form.upstream_model_id} onChange={(e) => set("upstream_model_id", e.target.value)} placeholder="deployment-v4" /></Field><Field label="Context length"><Input type="number" min="1" value={form.context_length} onChange={(e) => set("context_length", e.target.value)} placeholder="Optional" /></Field><Field label="Max output tokens"><Input type="number" min="1" value={form.max_output_tokens} onChange={(e) => set("max_output_tokens", e.target.value)} placeholder="Optional" /></Field><Toggle label="Responses API" description="Route /v1/responses requests here." checked={form.supports_responses} onChange={(value) => set("supports_responses", value)} /><Toggle label="Enabled" description="Show and route this model for members." checked={form.enabled} onChange={(value) => set("enabled", value)} /></div></Section>
			<Section title="Credential" description="Encrypted at rest and never shown after saving." last><Field label={mode === "create" ? "API key" : "Replace API key"} help={mode === "edit" ? `Leave blank to keep ${initialModel?.credential_prefix ?? "••••"}…${initialModel?.credential_suffix ?? "••••"}.` : undefined}><div className="relative"><KeyRound className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" type="password" autoComplete="new-password" value={form.credential} onChange={(e) => set("credential", e.target.value)} /></div></Field></Section>
		</div>
		<div className="flex flex-wrap items-center justify-between gap-3">{mode === "edit" ? <Button variant="ghost" className="text-destructive hover:text-destructive" disabled={pending} onClick={remove}><Trash2 className="mr-2 size-4" />Delete model</Button> : <span />}<div className="flex gap-2"><Button variant="outline" asChild><Link href={BACK}>Cancel</Link></Button><Button disabled={pending} onClick={save}>{pending ? "Saving…" : mode === "create" ? "Add model" : "Save changes"}</Button></div></div>
	</div>;
}
function Section({ title, description, last, children }: { title: string; description: string; last?: boolean; children: ReactNode }) { return <section className={`grid gap-5 p-5 md:grid-cols-[220px_minmax(0,1fr)] ${last ? "" : "border-b"}`}><div><h2 className="text-sm font-medium">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></div>{children}</section>; }
function Field({ label, help, className, children }: { label: string; help?: string; className?: string; children: ReactNode }) { return <div className={`space-y-2 ${className ?? ""}`}><Label>{label}</Label>{children}{help ? <p className="text-xs text-muted-foreground">{help}</p> : null}</div>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 rounded-lg border p-3"><div><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">{description}</p></div><Switch checked={checked} onCheckedChange={onChange} /></div>; }
