"use client";
import { useTranslations } from "next-intl";
import { Link } from "@/i18n/navigation";
import { useRouter } from "@/i18n/navigation";
import { useQueryClient } from "@tanstack/react-query";
import { invalidateAccountQueries } from "@/lib/query/invalidation";
import { useState, useTransition, type ReactNode } from "react";
import { ChevronLeft, KeyRound, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { createPrivateModelAction, deletePrivateModelAction, updatePrivateModelAction } from "@/app/(dashboard)/settings/workspaces/private-models/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import type { PrivateModelSetting } from "@/lib/fetchers/internal/fetchSettingsPrivateModels";

const BACK = "/settings/workspaces/private-models";
const EMPTY = { model_reference: "", name: "", base_url: "", upstream_model_id: "", credential: "", description: "", context_length: "", max_output_tokens: "", host_provider_id: "", custom_provider_name: "", custom_provider_url: "", routing_policy: "preferred", supports_responses: false, enabled: true };

type Option = { id: string; name: string };
export default function PrivateModelEditor({ mode, initialModel, workspaceNamespace, catalogModels = [], providers = [] }: { mode: "create" | "edit"; initialModel?: PrivateModelSetting; workspaceNamespace: string; catalogModels?: Option[]; providers?: Option[] }) {
	const t = useTranslations("SettingsUI");
	const router = useRouter(); const [pending, startTransition] = useTransition();
	const queryClient = useQueryClient();
	const [providerMode, setProviderMode] = useState<"existing" | "custom">(initialModel?.host_provider_id ? "existing" : "custom");
	const [form, setForm] = useState({ ...EMPTY, name: initialModel?.name ?? "", model_reference: initialModel?.catalog_model_id ?? initialModel?.local_slug ?? initialModel?.model_id.split("/").slice(1).join("/") ?? "", base_url: initialModel?.base_url ?? "", upstream_model_id: initialModel?.upstream_model_id ?? "", description: initialModel?.description ?? "", host_provider_id: initialModel?.host_provider_id ?? "", custom_provider_name: initialModel?.custom_provider_name ?? "", custom_provider_url: initialModel?.custom_provider_url ?? "", routing_policy: initialModel?.routing_policy ?? "preferred", supports_responses: initialModel?.supports_responses ?? false, enabled: initialModel?.enabled ?? true, context_length: initialModel?.context_length?.toString() ?? "", max_output_tokens: initialModel?.max_output_tokens?.toString() ?? "" });
	const set = (key: keyof typeof form, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
	const save = () => startTransition(async () => { try { const payload = { ...form, context_length: form.context_length ? Number(form.context_length) : null, max_output_tokens: form.max_output_tokens ? Number(form.max_output_tokens) : null }; if (mode === "create") await createPrivateModelAction(payload); else if (initialModel) await updatePrivateModelAction(initialModel.id, payload); toast.success(mode === "create" ? t("privateModelsCopy.added") : t("privateModelsCopy.updated")); router.push(BACK); await invalidateAccountQueries(queryClient); router.refresh(); } catch { toast.error(t("privateModelsCopy.saveFailed")); } });
	const remove = () => initialModel && confirm(t("privateModelsCopy.deleteConfirm", { name: initialModel.name })) && startTransition(async () => { try { await deletePrivateModelAction(initialModel.id); toast.success(t("privateModelsCopy.deleted")); router.push(BACK); await invalidateAccountQueries(queryClient); router.refresh(); } catch { toast.error(t("privateModelsCopy.deleteFailed")); } });
	return <div className="space-y-6">
		<Button variant="ghost" size="sm" asChild className="-ml-3"><Link href={BACK}><ChevronLeft className="mr-1 size-4" />{t("privateModelsCopy.back")}</Link></Button>
		<div className="overflow-hidden rounded-xl border">
			<Section title={t("privateModelsCopy.identity")} description={t("privateModelsCopy.identityHelp")}><div className="grid gap-4 sm:grid-cols-2"><Field label={t("privateModelsCopy.displayName")}><Input value={form.name} onChange={(e) => set("name", e.target.value)} placeholder={t("privateModelsCopy.legalAssistant")} /></Field><Field label={t("privateModelsCopy.modelReference")} help={form.model_reference.includes("/") ? (catalogModels.some((item) => item.id === form.model_reference) ? t("privateModelsCopy.attachProvider", { name: catalogModels.find((item) => item.id === form.model_reference)?.name ?? form.model_reference }) : t("privateModelsCopy.exactCatalogueId")) : t("privateModelsCopy.slugHelp", { modelId: `${workspaceNamespace}/${form.model_reference || "model-name"}` })}><Input list="private-model-catalog" className="font-mono" value={form.model_reference} onChange={(e) => set("model_reference", e.target.value.toLowerCase())} placeholder={t("privateModelsCopy.searchModels")} /><datalist id="private-model-catalog">{catalogModels.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</datalist></Field><Field label={t("privateModelsCopy.description")} className="sm:col-span-2"><Textarea value={form.description ?? ""} onChange={(e) => set("description", e.target.value)} placeholder={t("privateModelsCopy.descriptionPlaceholder")} /></Field></div></Section>
			<Section title={t("privateModelsCopy.hostingProvider")} description={t("privateModelsCopy.hostingProviderHelp")}><div className="grid gap-4 sm:grid-cols-2"><Field label={t("privateModelsCopy.providerType")}><select className="flex h-9 w-full rounded-md border bg-transparent px-3 text-sm" value={providerMode} onChange={(e) => { const next=e.target.value as "existing"|"custom"; setProviderMode(next); if(next==="existing") set("custom_provider_name",""); else set("host_provider_id",""); }}><option value="existing">{t("privateModelsCopy.existingProvider")}</option><option value="custom">{t("privateModelsCopy.customProvider")}</option></select></Field>{providerMode === "existing" ? <Field label={t("privateModelsCopy.provider")}><Input list="private-provider-catalog" value={form.host_provider_id} onChange={(e) => set("host_provider_id", e.target.value.toLowerCase())} placeholder={t("privateModelsCopy.searchProviders")} /><datalist id="private-provider-catalog">{providers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</datalist></Field> : <><Field label={t("privateModelsCopy.customProviderName")}><Input value={form.custom_provider_name} onChange={(e) => set("custom_provider_name", e.target.value)} placeholder={t("privateModelsCopy.acmeInference")} /></Field><Field label={t("privateModelsCopy.providerWebsite")}><Input value={form.custom_provider_url} onChange={(e) => set("custom_provider_url", e.target.value)} placeholder="https://models.example.com" /></Field></>}<Field label={t("privateModelsCopy.routing")}><select className="flex h-9 w-full rounded-md border bg-transparent px-3 text-sm" value={form.routing_policy} onChange={(e) => set("routing_policy", e.target.value)}><option value="preferred">{t("privateModelsCopy.preferred")}</option><option value="balanced">{t("privateModelsCopy.normalPool")}</option><option value="fallback">{t("privateModelsCopy.fallbackOnly")}</option></select></Field></div></Section>
			<Section title={t("privateModelsCopy.endpoint")} description={t("privateModelsCopy.endpointHelp")}><div className="grid gap-4 sm:grid-cols-2"><Field label={t("privateModelsCopy.baseUrl")}><Input value={form.base_url} onChange={(e) => set("base_url", e.target.value)} placeholder="https://models.example.com/v1" /></Field><Field label={t("privateModelsCopy.upstreamModelId")}><Input className="font-mono" value={form.upstream_model_id} onChange={(e) => set("upstream_model_id", e.target.value)} placeholder="deployment-v4" /></Field><Field label={t("privateModelsCopy.contextLength")}><Input type="number" min="1" value={form.context_length} onChange={(e) => set("context_length", e.target.value)} placeholder={t("privateModelsCopy.optional")} /></Field><Field label={t("privateModelsCopy.maxOutputTokens")}><Input type="number" min="1" value={form.max_output_tokens} onChange={(e) => set("max_output_tokens", e.target.value)} placeholder={t("privateModelsCopy.optional")} /></Field><Toggle label="Responses API" description={t("privateModelsCopy.responsesHelp")} checked={form.supports_responses} onChange={(value) => set("supports_responses", value)} /><Toggle label={t("privateModelsCopy.enabled")} description={t("privateModelsCopy.enabledHelp")} checked={form.enabled} onChange={(value) => set("enabled", value)} /></div></Section>
			<Section title={t("privateModelsCopy.credential")} description={t("privateModelsCopy.credentialHelp")} last><Field label={mode === "create" ? t("privateModelsCopy.apiKey") : t("privateModelsCopy.replaceApiKey")} help={mode === "edit" ? t("privateModelsCopy.keepCredential", { credential: `${initialModel?.credential_prefix ?? "••••"}…${initialModel?.credential_suffix ?? "••••"}` }) : undefined}><div className="relative"><KeyRound className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" type="password" autoComplete="new-password" value={form.credential} onChange={(e) => set("credential", e.target.value)} /></div></Field></Section>
		</div>
		<div className="flex flex-wrap items-center justify-between gap-3">{mode === "edit" ? <Button variant="ghost" className="text-destructive hover:text-destructive" disabled={pending} onClick={remove}><Trash2 className="mr-2 size-4" />{t("privateModelsCopy.deleteModel")}</Button> : <span />}<div className="flex gap-2"><Button variant="outline" asChild><Link href={BACK}>{t("settingsPageCopy.cancel")}</Link></Button><Button disabled={pending} onClick={save}>{pending ? t("settingsPageCopy.saving") : mode === "create" ? t("privateModelsCopy.addModel") : t("privateModelsCopy.saveChanges")}</Button></div></div>
	</div>;
}
function Section({ title, description, last, children }: { title: string; description: string; last?: boolean; children: ReactNode }) { return <section className={`grid gap-5 p-5 md:grid-cols-[220px_minmax(0,1fr)] ${last ? "" : "border-b"}`}><div><h2 className="text-sm font-medium">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></div>{children}</section>; }
function Field({ label, help, className, children }: { label: string; help?: string; className?: string; children: ReactNode }) { return <div className={`space-y-2 ${className ?? ""}`}><Label>{label}</Label>{children}{help ? <p className="text-xs text-muted-foreground">{help}</p> : null}</div>; }
function Toggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 rounded-lg border p-3"><div><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">{description}</p></div><Switch checked={checked} onCheckedChange={onChange} /></div>; }
