import { MessageContent } from "./MessageContent";
import { Check, Circle, CircleDot, CircleSlash, Copy } from "lucide-react";
import type { AgentActivity } from "../../shared/workspace";
import { useTextCopy } from "./useTextCopy";

const labels = { tool: "Tool result", reasoning: "Reasoning", plan: "Plan", usage: "Usage", compaction: "Compaction result" };
export function ActivityResult({ activity }: { activity: AgentActivity }) {
	const { status, copying, copy } = useTextCopy(activity.text);
	const steps = activity.type === "plan" ? activity.steps : undefined;
	const compaction = activity.type === "compaction" ? activity.compaction : undefined;
	const number = new Intl.NumberFormat();
	const statusOnly = activity.type === "compaction" && !activity.text;
	return <details data-conversation-id={`activity:${activity.id}`} className="task-activity" open={Boolean(steps?.length)}><summary>{activity.title}{activity.status ? ` · ${activity.status}` : ""}{steps?.length ? ` · ${steps.filter(step => step.status === "completed").length}/${steps.length} completed` : ""}</summary><div className="activity-result">{statusOnly ? <p className="compaction-status">{activity.status === "running" ? "Compacting native context…" : activity.status === "completed" ? "Native context compacted." : "Native compaction failed."}</p> : <><div className="message-code-actions"><span aria-live="polite">{status === "failed" ? "Copy failed" : labels[activity.type]}</span><button type="button" disabled={copying || !activity.text} onClick={() => void copy()} aria-label={status === "copied" ? "Result copied" : "Copy result"}>{status === "copied" ? <Check size={14} /> : <Copy size={14} />}{status === "copied" ? "Copied" : "Copy result"}</button></div>{activity.type === "compaction" && activity.summary ? <><div className="compaction-summary"><MessageContent text={activity.summary} /></div><details className="compaction-source"><summary>Original result</summary><pre>{activity.text}</pre></details></> : compaction ? <><dl className="compaction-metrics"><div><dt>Before</dt><dd>{number.format(compaction.beforeTokens)} tokens</dd></div>{compaction.afterTokens !== undefined && <div><dt>After</dt><dd>{number.format(compaction.afterTokens)} tokens</dd></div>}{compaction.durationMs !== undefined && <div><dt>Duration</dt><dd>{number.format(compaction.durationMs)} ms</dd></div>}</dl><details className="compaction-source"><summary>Original result</summary><pre>{activity.text}</pre></details></> : steps?.length ? <>{activity.explanation && <p className="plan-explanation">{activity.explanation}</p>}<ol className="plan-steps">{steps.map((step, index) => <li key={index} data-status={step.status}>{step.status === "cancelled" ? <CircleSlash size={16} aria-hidden /> : step.status === "completed" ? <Check size={16} aria-hidden /> : step.status === "in_progress" ? <CircleDot size={16} aria-hidden /> : <Circle size={16} aria-hidden />}<span>{step.text}<small>{step.status === "in_progress" ? "In progress" : step.status === "completed" ? "Completed" : step.status === "cancelled" ? "Cancelled" : "Pending"}</small></span></li>)}</ol><details className="plan-source"><summary>Original result</summary><pre>{activity.text}</pre></details></> : <pre>{activity.text}</pre>}</>}</div></details>;
}
