import { useEffect, useState } from "react";
import { nativeActionText, type NativeAction, type NativeActionEntry } from "../../shared/nativeActions";
export function NativeActionPicker({ taskId, onInsert }: { taskId: string; onInsert: (text: string, action?: NativeAction) => void }) {
 const [actions, setActions] = useState<NativeActionEntry[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<NativeActionEntry>(); const [args, setArgs] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [attempt, setAttempt] = useState(0);
 useEffect(() => { let active = true; setLoading(true); setError(""); const api = window.phaseoDesktop?.workspace; if (!api) { setLoading(false); setError("Open the desktop app to load native actions."); return; } void api.nativeActions(taskId).then(value => { if (active) setActions(value.actions); }, reason => { if (active) setError(reason instanceof Error ? reason.message : String(reason)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [taskId, attempt]);
 return <div className="prompt-command-preview">
 {error && <p className="task-error" role="alert">{error}</p>}
 {selected ? <><strong>{selected.name}</strong>{selected.description && <p>{selected.description}</p>}{selected.path && <p className="task-muted">{selected.path}</p>}<label>Arguments<textarea aria-label="Native action arguments" placeholder={selected.argumentHint} maxLength={99000} value={args} onChange={event => setArgs(event.target.value)} /></label><div className="prompt-command-actions"><button type="button" onClick={() => setSelected(undefined)}>Back</button><button type="button" className="task-primary" onClick={() => { try { const action = { kind: selected.kind, id: selected.id, name: selected.name, arguments: args }; onInsert(nativeActionText(action), action); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }}>Insert into chat</button></div></> : <><input aria-label="Search native actions" placeholder="Search commands and skills" value={query} onChange={event => setQuery(event.target.value)} />{loading ? <p role="status">Loading native actions…</p> : <div className="prompt-command-results">{actions.filter(action => `${action.name} ${action.description}`.toLowerCase().includes(query.toLowerCase())).map(action => <button type="button" key={`${action.kind}:${action.id}`} onClick={() => { setSelected(action); setArgs(""); }}><span><strong>{action.name}</strong>{action.description && <small>{action.description}</small>}</span><small>{action.kind === "skill" ? "Skill" : "Command"}</small></button>)}{!actions.length && !error && <p className="task-muted">No native commands or skills in this project.</p>}</div>}<button type="button" disabled={loading} onClick={() => setAttempt(value => value + 1)}>Refresh</button></>}
 </div>;
}
