import { useEffect, useId, useRef, useState } from "react";
import { nativeActionText, type NativeAction, type NativeActionEntry } from "../../shared/nativeActions";
export function NativeActionPicker({ taskId, onInsert }: { taskId: string; onInsert: (text: string, action?: NativeAction) => void }) {
 const search = useRef<HTMLInputElement>(null), argumentsInput = useRef<HTMLTextAreaElement>(null), list = useRef<HTMLDivElement>(null); const listId = useId(); const [index, setIndex] = useState(0);
 const [actions, setActions] = useState<NativeActionEntry[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<NativeActionEntry>(); const [args, setArgs] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [attempt, setAttempt] = useState(0);
 useEffect(() => { let active = true; setLoading(true); setError(""); setActions([]); setIndex(0); const api = window.phaseoDesktop?.workspace; if (!api) { setLoading(false); setError("Open the desktop app to load native actions."); return; } void api.nativeActions(taskId).then(value => { if (active) setActions(value.actions); }, reason => { if (active) setError(reason instanceof Error ? reason.message : String(reason)); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [taskId, attempt]);
 const matches = actions.filter(action => `${action.name} ${action.description}`.toLowerCase().includes(query.toLowerCase())); const activeIndex = Math.max(0, Math.min(index, matches.length - 1));
 useEffect(() => { if (selected) argumentsInput.current?.focus(); else search.current?.focus(); }, [selected]);
 useEffect(() => { list.current?.querySelector('[aria-selected="true"]')?.scrollIntoView({ block: "nearest" }); }, [activeIndex, query, actions]);
 const choose = (action: NativeActionEntry) => { setSelected(action); setArgs(""); };
 return <div className="prompt-command-preview">
 {error && <p className="task-error" role="alert">{error}</p>}
 {selected ? <><strong>{selected.name}</strong>{selected.description && <p>{selected.description}</p>}{selected.path && <p className="task-muted">{selected.path}</p>}<label>Arguments<textarea ref={argumentsInput} aria-label="Native action arguments" placeholder={selected.argumentHint} maxLength={99000} value={args} onChange={event => setArgs(event.target.value)} /></label><div className="prompt-command-actions"><button type="button" onClick={() => setSelected(undefined)}>Back</button><button type="button" className="task-primary" onClick={() => { try { const action = { kind: selected.kind, id: selected.id, name: selected.name, arguments: args }; onInsert(nativeActionText(action), action); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }}>Insert into chat</button></div></> : <><input ref={search} role="combobox" aria-autocomplete="list" aria-expanded={!loading && !error && matches.length > 0} aria-controls={listId} aria-activedescendant={!loading && !error && matches.length ? `${listId}-${activeIndex}` : undefined} aria-label="Search native actions" placeholder="Search commands and skills" value={query} onChange={event => { setQuery(event.target.value); setIndex(0); }} onKeyDown={event => { if (event.nativeEvent.isComposing || loading || error || !matches.length) return; if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setIndex((activeIndex + (event.key === "ArrowDown" ? 1 : -1) + matches.length) % matches.length); } else if (event.key === "Home" || event.key === "End") { event.preventDefault(); setIndex(event.key === "Home" ? 0 : matches.length - 1); } else if (event.key === "Enter") { event.preventDefault(); choose(matches[activeIndex]); } }} />{loading ? <p role="status">Loading native actions…</p> : <div ref={list} id={listId} role="listbox" aria-label="Native commands and skills" className="prompt-command-results">{!error && matches.map((action, itemIndex) => <button type="button" role="option" aria-selected={activeIndex === itemIndex} id={`${listId}-${itemIndex}`} key={`${action.kind}:${action.id}`} onFocus={() => setIndex(itemIndex)} onClick={() => choose(action)}><span><strong>{action.name}</strong>{action.description && <small>{action.description}</small>}</span><small>{action.kind === "skill" ? "Skill" : "Command"}</small></button>)}{!matches.length && !error && <p className="task-muted" role="status">{actions.length ? "No matching commands or skills." : "No native commands or skills in this project."}</p>}</div>}<button type="button" disabled={loading} onClick={() => setAttempt(value => value + 1)}>Refresh</button></>}
 </div>;
}
