import { Hono } from "hono";
import type { Env } from "@/env";
import { publicStatusRouter } from "./status";
import { publicModelsRouter } from "./models";
import { publicReferenceDataRouter } from "./reference-data";
import { publicCollectionsRouter } from "./collections";
import { publicUpdatesRouter } from "./updates";
import { publicOrganisationsRouter } from "./organisations";
import { publicAppsRouter } from "./apps";
import { publicMarketplaceRouter } from "./marketplace";
import { publicLandingRouter } from "./landing";
import { publicCompareRouter } from "./compare";
import { publicProvidersRouter } from "./providers";
import { publicRankingsRouter } from "./rankings";
import { publicMonitorRouter } from "./monitor";
import { publicPricingRouter } from "./pricing";
import { publicGatewayRouter } from "./gateway";
import { publicOgRouter } from "./og";

export const publicRouter = new Hono<{ Bindings: Env }>();
publicRouter.route("/", publicStatusRouter);
publicRouter.route("/models", publicModelsRouter);
publicRouter.route("/", publicReferenceDataRouter);
publicRouter.route("/", publicCollectionsRouter);
publicRouter.route("/", publicUpdatesRouter);
publicRouter.route("/", publicOrganisationsRouter);
publicRouter.route("/", publicAppsRouter);
publicRouter.route("/", publicMarketplaceRouter);
publicRouter.route("/", publicLandingRouter);
publicRouter.route("/", publicCompareRouter);
publicRouter.route("/api-providers", publicProvidersRouter);
publicRouter.route("/", publicRankingsRouter);
publicRouter.route("/", publicMonitorRouter);
publicRouter.route("/", publicPricingRouter);
publicRouter.route("/", publicGatewayRouter);
publicRouter.route("/", publicOgRouter);
