// This file is generated by scripts/sdk/generate-model-id-constants.mjs.
// Do not edit manually.

package phaseo

import gen "github.com/phaseoteam/Phaseo/packages/sdk/sdk-go/src/gen"

// ModelIds contains known model IDs for editor autocomplete and hover docs.
const (
	// Model ID: ai21/jamba-large-1.7
	// Model page: https://phaseo.app/models/ai21/jamba-large-1.7
	ModelIDAi21JambaLarge17 gen.ModelId = "ai21/jamba-large-1.7"
	// Model ID: ai21/jamba-mini-2
	// Model page: https://phaseo.app/models/ai21/jamba-mini-2
	ModelIDAi21JambaMini2 gen.ModelId = "ai21/jamba-mini-2"
	// Model ID: aion-labs/aion-2.0
	// Model page: https://phaseo.app/models/aion-labs/aion-2.0
	ModelIDAionLabsAion20 gen.ModelId = "aion-labs/aion-2.0"
	// Model ID: aion-labs/aion-2.5
	// Model page: https://phaseo.app/models/aion-labs/aion-2.5
	ModelIDAionLabsAion25 gen.ModelId = "aion-labs/aion-2.5"
	// Model ID: aion-labs/aion-3.0
	// Model page: https://phaseo.app/models/aion-labs/aion-3.0
	ModelIDAionLabsAion30 gen.ModelId = "aion-labs/aion-3.0"
	// Model ID: aion-labs/aion-3.0-mini
	// Model page: https://phaseo.app/models/aion-labs/aion-3.0-mini
	ModelIDAionLabsAion30Mini gen.ModelId = "aion-labs/aion-3.0-mini"
	// Model ID: aion-labs/aion-rp-llama-3.1-8b
	// Model page: https://phaseo.app/models/aion-labs/aion-rp-llama-3.1-8b
	ModelIDAionLabsAionRpLlama318b gen.ModelId = "aion-labs/aion-rp-llama-3.1-8b"
	// Model ID: allenai/molmo-2-8b
	// Model page: https://phaseo.app/models/allenai/molmo-2-8b
	ModelIDAllenaiMolmo28b gen.ModelId = "allenai/molmo-2-8b"
	// Model ID: allenai/olmo-3.1-32b
	// Model page: https://phaseo.app/models/allenai/olmo-3.1-32b
	ModelIDAllenaiOlmo3132b gen.ModelId = "allenai/olmo-3.1-32b"
	// Model ID: anthropic/claude-fable-5
	// Model page: https://phaseo.app/models/anthropic/claude-fable-5
	ModelIDAnthropicClaudeFable5 gen.ModelId = "anthropic/claude-fable-5"
	// Model ID: anthropic/claude-haiku-4.5
	// Model page: https://phaseo.app/models/anthropic/claude-haiku-4.5
	ModelIDAnthropicClaudeHaiku45 gen.ModelId = "anthropic/claude-haiku-4.5"
	// Model ID: anthropic/claude-opus-4.1
	// Model page: https://phaseo.app/models/anthropic/claude-opus-4.1
	ModelIDAnthropicClaudeOpus41 gen.ModelId = "anthropic/claude-opus-4.1"
	// Model ID: anthropic/claude-opus-4.5
	// Model page: https://phaseo.app/models/anthropic/claude-opus-4.5
	ModelIDAnthropicClaudeOpus45 gen.ModelId = "anthropic/claude-opus-4.5"
	// Model ID: anthropic/claude-opus-4.6
	// Model page: https://phaseo.app/models/anthropic/claude-opus-4.6
	ModelIDAnthropicClaudeOpus46 gen.ModelId = "anthropic/claude-opus-4.6"
	// Model ID: anthropic/claude-opus-4.7
	// Model page: https://phaseo.app/models/anthropic/claude-opus-4.7
	ModelIDAnthropicClaudeOpus47 gen.ModelId = "anthropic/claude-opus-4.7"
	// Model ID: anthropic/claude-opus-4.7-fast
	// Model page: https://phaseo.app/models/anthropic/claude-opus-4.7-fast
	ModelIDAnthropicClaudeOpus47Fast gen.ModelId = "anthropic/claude-opus-4.7-fast"
	// Model ID: anthropic/claude-opus-4.8
	// Model page: https://phaseo.app/models/anthropic/claude-opus-4.8
	ModelIDAnthropicClaudeOpus48 gen.ModelId = "anthropic/claude-opus-4.8"
	// Model ID: anthropic/claude-sonnet-4.5
	// Model page: https://phaseo.app/models/anthropic/claude-sonnet-4.5
	ModelIDAnthropicClaudeSonnet45 gen.ModelId = "anthropic/claude-sonnet-4.5"
	// Model ID: anthropic/claude-sonnet-4.6
	// Model page: https://phaseo.app/models/anthropic/claude-sonnet-4.6
	ModelIDAnthropicClaudeSonnet46 gen.ModelId = "anthropic/claude-sonnet-4.6"
	// Model ID: anthropic/claude-sonnet-5
	// Model page: https://phaseo.app/models/anthropic/claude-sonnet-5
	ModelIDAnthropicClaudeSonnet5 gen.ModelId = "anthropic/claude-sonnet-5"
	// Model ID: arcee-ai/trinity-large
	// Model page: https://phaseo.app/models/arcee-ai/trinity-large
	ModelIDArceeAiTrinityLarge gen.ModelId = "arcee-ai/trinity-large"
	// Model ID: arcee-ai/trinity-large-thinking
	// Model page: https://phaseo.app/models/arcee-ai/trinity-large-thinking
	ModelIDArceeAiTrinityLargeThinking gen.ModelId = "arcee-ai/trinity-large-thinking"
	// Model ID: arcee-ai/trinity-mini
	// Model page: https://phaseo.app/models/arcee-ai/trinity-mini
	ModelIDArceeAiTrinityMini gen.ModelId = "arcee-ai/trinity-mini"
	// Model ID: baidu/ernie-4.5-21b-a3b
	// Model page: https://phaseo.app/models/baidu/ernie-4.5-21b-a3b
	ModelIDBaiduErnie4521bA3b gen.ModelId = "baidu/ernie-4.5-21b-a3b"
	// Model ID: baidu/ernie-4.5-21b-a3b-thinking
	// Model page: https://phaseo.app/models/baidu/ernie-4.5-21b-a3b-thinking
	ModelIDBaiduErnie4521bA3bThinking gen.ModelId = "baidu/ernie-4.5-21b-a3b-thinking"
	// Model ID: baidu/ernie-4.5-300b-a47b
	// Model page: https://phaseo.app/models/baidu/ernie-4.5-300b-a47b
	ModelIDBaiduErnie45300bA47b gen.ModelId = "baidu/ernie-4.5-300b-a47b"
	// Model ID: baidu/ernie-4.5-vl-28b-a3b
	// Model page: https://phaseo.app/models/baidu/ernie-4.5-vl-28b-a3b
	ModelIDBaiduErnie45Vl28bA3b gen.ModelId = "baidu/ernie-4.5-vl-28b-a3b"
	// Model ID: baidu/ernie-4.5-vl-28b-a3b-thinking
	// Model page: https://phaseo.app/models/baidu/ernie-4.5-vl-28b-a3b-thinking
	ModelIDBaiduErnie45Vl28bA3bThinking gen.ModelId = "baidu/ernie-4.5-vl-28b-a3b-thinking"
	// Model ID: baidu/ernie-4.5-vl-424b-a47b
	// Model page: https://phaseo.app/models/baidu/ernie-4.5-vl-424b-a47b
	ModelIDBaiduErnie45Vl424bA47b gen.ModelId = "baidu/ernie-4.5-vl-424b-a47b"
	// Model ID: black-forest-labs/flux-1-schnell
	// Model page: https://phaseo.app/models/black-forest-labs/flux-1-schnell
	ModelIDBlackForestLabsFlux1Schnell gen.ModelId = "black-forest-labs/flux-1-schnell"
	// Model ID: bytedance/seed-1.6
	// Model page: https://phaseo.app/models/bytedance/seed-1.6
	ModelIDBytedanceSeed16 gen.ModelId = "bytedance/seed-1.6"
	// Model ID: bytedance/seed-1.6-250915
	// Model page: https://phaseo.app/models/bytedance/seed-1.6-250915
	ModelIDBytedanceSeed16250915 gen.ModelId = "bytedance/seed-1.6-250915"
	// Model ID: bytedance/seed-1.6-flash
	// Model page: https://phaseo.app/models/bytedance/seed-1.6-flash
	ModelIDBytedanceSeed16Flash gen.ModelId = "bytedance/seed-1.6-flash"
	// Model ID: bytedance/seed-1.6-flash-250715
	// Model page: https://phaseo.app/models/bytedance/seed-1.6-flash-250715
	ModelIDBytedanceSeed16Flash250715 gen.ModelId = "bytedance/seed-1.6-flash-250715"
	// Model ID: bytedance/seed-1.8
	// Model page: https://phaseo.app/models/bytedance/seed-1.8
	ModelIDBytedanceSeed18 gen.ModelId = "bytedance/seed-1.8"
	// Model ID: bytedance/seed-2.0-lite
	// Model page: https://phaseo.app/models/bytedance/seed-2.0-lite
	ModelIDBytedanceSeed20Lite gen.ModelId = "bytedance/seed-2.0-lite"
	// Model ID: bytedance/seed-2.0-lite-260428
	// Model page: https://phaseo.app/models/bytedance/seed-2.0-lite-260428
	ModelIDBytedanceSeed20Lite260428 gen.ModelId = "bytedance/seed-2.0-lite-260428"
	// Model ID: bytedance/seed-2.0-mini
	// Model page: https://phaseo.app/models/bytedance/seed-2.0-mini
	ModelIDBytedanceSeed20Mini gen.ModelId = "bytedance/seed-2.0-mini"
	// Model ID: bytedance/seed-2.0-mini-260428
	// Model page: https://phaseo.app/models/bytedance/seed-2.0-mini-260428
	ModelIDBytedanceSeed20Mini260428 gen.ModelId = "bytedance/seed-2.0-mini-260428"
	// Model ID: bytedance/seed-2.0-pro
	// Model page: https://phaseo.app/models/bytedance/seed-2.0-pro
	ModelIDBytedanceSeed20Pro gen.ModelId = "bytedance/seed-2.0-pro"
	// Model ID: bytedance/seed-oss-36b-instruct
	// Model page: https://phaseo.app/models/bytedance/seed-oss-36b-instruct
	ModelIDBytedanceSeedOss36bInstruct gen.ModelId = "bytedance/seed-oss-36b-instruct"
	// Model ID: bytedance/seed-translation
	// Model page: https://phaseo.app/models/bytedance/seed-translation
	ModelIDBytedanceSeedTranslation gen.ModelId = "bytedance/seed-translation"
	// Model ID: bytedance/seedance-2.0
	// Model page: https://phaseo.app/models/bytedance/seedance-2.0
	ModelIDBytedanceSeedance20 gen.ModelId = "bytedance/seedance-2.0"
	// Model ID: bytedance/seedance-2.0-fast
	// Model page: https://phaseo.app/models/bytedance/seedance-2.0-fast
	ModelIDBytedanceSeedance20Fast gen.ModelId = "bytedance/seedance-2.0-fast"
	// Model ID: bytedance/seedance-2.0-mini-260615
	// Model page: https://phaseo.app/models/bytedance/seedance-2.0-mini-260615
	ModelIDBytedanceSeedance20Mini260615 gen.ModelId = "bytedance/seedance-2.0-mini-260615"
	// Model ID: crofai/greg-1-mini
	// Model page: https://phaseo.app/models/crofai/greg-1-mini
	ModelIDCrofaiGreg1Mini gen.ModelId = "crofai/greg-1-mini"
	// Model ID: crofai/greg-2-super
	// Model page: https://phaseo.app/models/crofai/greg-2-super
	ModelIDCrofaiGreg2Super gen.ModelId = "crofai/greg-2-super"
	// Model ID: crofai/greg-2-ultra
	// Model page: https://phaseo.app/models/crofai/greg-2-ultra
	ModelIDCrofaiGreg2Ultra gen.ModelId = "crofai/greg-2-ultra"
	// Model ID: crofai/greg-rp
	// Model page: https://phaseo.app/models/crofai/greg-rp
	ModelIDCrofaiGregRp gen.ModelId = "crofai/greg-rp"
	// Model ID: deepseek/deepseek-ocr
	// Model page: https://phaseo.app/models/deepseek/deepseek-ocr
	ModelIDDeepseekDeepseekOcr gen.ModelId = "deepseek/deepseek-ocr"
	// Model ID: deepseek/deepseek-ocr-2
	// Model page: https://phaseo.app/models/deepseek/deepseek-ocr-2
	ModelIDDeepseekDeepseekOcr2 gen.ModelId = "deepseek/deepseek-ocr-2"
	// Model ID: deepseek/deepseek-prover-v2-671b
	// Model page: https://phaseo.app/models/deepseek/deepseek-prover-v2-671b
	ModelIDDeepseekDeepseekProverV2671b gen.ModelId = "deepseek/deepseek-prover-v2-671b"
	// Model ID: deepseek/deepseek-r1
	// Model page: https://phaseo.app/models/deepseek/deepseek-r1
	ModelIDDeepseekDeepseekR1 gen.ModelId = "deepseek/deepseek-r1"
	// Model ID: deepseek/deepseek-r1-0528
	// Model page: https://phaseo.app/models/deepseek/deepseek-r1-0528
	ModelIDDeepseekDeepseekR10528 gen.ModelId = "deepseek/deepseek-r1-0528"
	// Model ID: deepseek/deepseek-r1-2025-05-28
	// Model page: https://phaseo.app/models/deepseek/deepseek-r1-2025-05-28
	ModelIDDeepseekDeepseekR120250528 gen.ModelId = "deepseek/deepseek-r1-2025-05-28"
	// Model ID: deepseek/deepseek-r1-turbo
	// Model page: https://phaseo.app/models/deepseek/deepseek-r1-turbo
	ModelIDDeepseekDeepseekR1Turbo gen.ModelId = "deepseek/deepseek-r1-turbo"
	// Model ID: deepseek/deepseek-v3
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3
	ModelIDDeepseekDeepseekV3 gen.ModelId = "deepseek/deepseek-v3"
	// Model ID: deepseek/deepseek-v3-0324
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3-0324
	ModelIDDeepseekDeepseekV30324 gen.ModelId = "deepseek/deepseek-v3-0324"
	// Model ID: deepseek/deepseek-v3-turbo
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3-turbo
	ModelIDDeepseekDeepseekV3Turbo gen.ModelId = "deepseek/deepseek-v3-turbo"
	// Model ID: deepseek/deepseek-v3.1
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3.1
	ModelIDDeepseekDeepseekV31 gen.ModelId = "deepseek/deepseek-v3.1"
	// Model ID: deepseek/deepseek-v3.1-terminus
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3.1-terminus
	ModelIDDeepseekDeepseekV31Terminus gen.ModelId = "deepseek/deepseek-v3.1-terminus"
	// Model ID: deepseek/deepseek-v3.2
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3.2
	ModelIDDeepseekDeepseekV32 gen.ModelId = "deepseek/deepseek-v3.2"
	// Model ID: deepseek/deepseek-v3.2-exp
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3.2-exp
	ModelIDDeepseekDeepseekV32Exp gen.ModelId = "deepseek/deepseek-v3.2-exp"
	// Model ID: deepseek/deepseek-v3.2-speciale
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3.2-speciale
	ModelIDDeepseekDeepseekV32Speciale gen.ModelId = "deepseek/deepseek-v3.2-speciale"
	// Model ID: deepseek/deepseek-v3.2-thinking
	// Model page: https://phaseo.app/models/deepseek/deepseek-v3.2-thinking
	ModelIDDeepseekDeepseekV32Thinking gen.ModelId = "deepseek/deepseek-v3.2-thinking"
	// Model ID: deepseek/deepseek-v4-flash
	// Model page: https://phaseo.app/models/deepseek/deepseek-v4-flash
	ModelIDDeepseekDeepseekV4Flash gen.ModelId = "deepseek/deepseek-v4-flash"
	// Model ID: deepseek/deepseek-v4-pro
	// Model page: https://phaseo.app/models/deepseek/deepseek-v4-pro
	ModelIDDeepseekDeepseekV4Pro gen.ModelId = "deepseek/deepseek-v4-pro"
	// Model ID: deepseek/deepseek-v4-pro-lightning
	// Model page: https://phaseo.app/models/deepseek/deepseek-v4-pro-lightning
	ModelIDDeepseekDeepseekV4ProLightning gen.ModelId = "deepseek/deepseek-v4-pro-lightning"
	// Model ID: eleven-labs/eleven-flash-v2
	// Model page: https://phaseo.app/models/eleven-labs/eleven-flash-v2
	ModelIDElevenLabsElevenFlashV2 gen.ModelId = "eleven-labs/eleven-flash-v2"
	// Model ID: eleven-labs/eleven-flash-v2.5
	// Model page: https://phaseo.app/models/eleven-labs/eleven-flash-v2.5
	ModelIDElevenLabsElevenFlashV25 gen.ModelId = "eleven-labs/eleven-flash-v2.5"
	// Model ID: eleven-labs/eleven-multilingual-v2
	// Model page: https://phaseo.app/models/eleven-labs/eleven-multilingual-v2
	ModelIDElevenLabsElevenMultilingualV2 gen.ModelId = "eleven-labs/eleven-multilingual-v2"
	// Model ID: eleven-labs/eleven-turbo-v2
	// Model page: https://phaseo.app/models/eleven-labs/eleven-turbo-v2
	ModelIDElevenLabsElevenTurboV2 gen.ModelId = "eleven-labs/eleven-turbo-v2"
	// Model ID: eleven-labs/eleven-turbo-v2.5
	// Model page: https://phaseo.app/models/eleven-labs/eleven-turbo-v2.5
	ModelIDElevenLabsElevenTurboV25 gen.ModelId = "eleven-labs/eleven-turbo-v2.5"
	// Model ID: eleven-labs/eleven-v3
	// Model page: https://phaseo.app/models/eleven-labs/eleven-v3
	ModelIDElevenLabsElevenV3 gen.ModelId = "eleven-labs/eleven-v3"
	// Model ID: essential-ai/rnj-1
	// Model page: https://phaseo.app/models/essential-ai/rnj-1
	ModelIDEssentialAiRnj1 gen.ModelId = "essential-ai/rnj-1"
	// Model ID: google/gemini-2.5-flash
	// Model page: https://phaseo.app/models/google/gemini-2.5-flash
	ModelIDGoogleGemini25Flash gen.ModelId = "google/gemini-2.5-flash"
	// Model ID: google/gemini-2.5-flash-lite
	// Model page: https://phaseo.app/models/google/gemini-2.5-flash-lite
	ModelIDGoogleGemini25FlashLite gen.ModelId = "google/gemini-2.5-flash-lite"
	// Model ID: google/gemini-2.5-flash-lite-preview-2025-06-17
	// Model page: https://phaseo.app/models/google/gemini-2.5-flash-lite-preview-2025-06-17
	ModelIDGoogleGemini25FlashLitePreview20250617 gen.ModelId = "google/gemini-2.5-flash-lite-preview-2025-06-17"
	// Model ID: google/gemini-2.5-flash-lite-preview-2025-09-25
	// Model page: https://phaseo.app/models/google/gemini-2.5-flash-lite-preview-2025-09-25
	ModelIDGoogleGemini25FlashLitePreview20250925 gen.ModelId = "google/gemini-2.5-flash-lite-preview-2025-09-25"
	// Model ID: google/gemini-2.5-pro
	// Model page: https://phaseo.app/models/google/gemini-2.5-pro
	ModelIDGoogleGemini25Pro gen.ModelId = "google/gemini-2.5-pro"
	// Model ID: google/gemini-3-flash-preview
	// Model page: https://phaseo.app/models/google/gemini-3-flash-preview
	ModelIDGoogleGemini3FlashPreview gen.ModelId = "google/gemini-3-flash-preview"
	// Model ID: google/gemini-3-pro-image
	// Model page: https://phaseo.app/models/google/gemini-3-pro-image
	ModelIDGoogleGemini3ProImage gen.ModelId = "google/gemini-3-pro-image"
	// Model ID: google/gemini-3.1-flash-image
	// Model page: https://phaseo.app/models/google/gemini-3.1-flash-image
	ModelIDGoogleGemini31FlashImage gen.ModelId = "google/gemini-3.1-flash-image"
	// Model ID: google/gemini-3.1-flash-image-preview
	// Model page: https://phaseo.app/models/google/gemini-3.1-flash-image-preview
	ModelIDGoogleGemini31FlashImagePreview gen.ModelId = "google/gemini-3.1-flash-image-preview"
	// Model ID: google/gemini-3.1-flash-lite
	// Model page: https://phaseo.app/models/google/gemini-3.1-flash-lite
	ModelIDGoogleGemini31FlashLite gen.ModelId = "google/gemini-3.1-flash-lite"
	// Model ID: google/gemini-3.1-flash-lite-image
	// Model page: https://phaseo.app/models/google/gemini-3.1-flash-lite-image
	ModelIDGoogleGemini31FlashLiteImage gen.ModelId = "google/gemini-3.1-flash-lite-image"
	// Model ID: google/gemini-3.1-flash-lite-preview
	// Model page: https://phaseo.app/models/google/gemini-3.1-flash-lite-preview
	ModelIDGoogleGemini31FlashLitePreview gen.ModelId = "google/gemini-3.1-flash-lite-preview"
	// Model ID: google/gemini-3.1-flash-tts-preview
	// Model page: https://phaseo.app/models/google/gemini-3.1-flash-tts-preview
	ModelIDGoogleGemini31FlashTtsPreview gen.ModelId = "google/gemini-3.1-flash-tts-preview"
	// Model ID: google/gemini-3.1-pro-preview
	// Model page: https://phaseo.app/models/google/gemini-3.1-pro-preview
	ModelIDGoogleGemini31ProPreview gen.ModelId = "google/gemini-3.1-pro-preview"
	// Model ID: google/gemini-3.1-pro-preview-customtools
	// Model page: https://phaseo.app/models/google/gemini-3.1-pro-preview-customtools
	ModelIDGoogleGemini31ProPreviewCustomtools gen.ModelId = "google/gemini-3.1-pro-preview-customtools"
	// Model ID: google/gemini-3.5-flash
	// Model page: https://phaseo.app/models/google/gemini-3.5-flash
	ModelIDGoogleGemini35Flash gen.ModelId = "google/gemini-3.5-flash"
	// Model ID: google/gemini-3.5-pro
	// Model page: https://phaseo.app/models/google/gemini-3.5-pro
	ModelIDGoogleGemini35Pro gen.ModelId = "google/gemini-3.5-pro"
	// Model ID: google/gemini-embedding-001
	// Model page: https://phaseo.app/models/google/gemini-embedding-001
	ModelIDGoogleGeminiEmbedding001 gen.ModelId = "google/gemini-embedding-001"
	// Model ID: google/gemini-embedding-2
	// Model page: https://phaseo.app/models/google/gemini-embedding-2
	ModelIDGoogleGeminiEmbedding2 gen.ModelId = "google/gemini-embedding-2"
	// Model ID: google/gemini-embedding-2-preview
	// Model page: https://phaseo.app/models/google/gemini-embedding-2-preview
	ModelIDGoogleGeminiEmbedding2Preview gen.ModelId = "google/gemini-embedding-2-preview"
	// Model ID: google/gemini-robotics-er-1.6-preview
	// Model page: https://phaseo.app/models/google/gemini-robotics-er-1.6-preview
	ModelIDGoogleGeminiRoboticsEr16Preview gen.ModelId = "google/gemini-robotics-er-1.6-preview"
	// Model ID: google/gemma-3-27b
	// Model page: https://phaseo.app/models/google/gemma-3-27b
	ModelIDGoogleGemma327b gen.ModelId = "google/gemma-3-27b"
	// Model ID: google/gemma-3n-e4b
	// Model page: https://phaseo.app/models/google/gemma-3n-e4b
	ModelIDGoogleGemma3nE4b gen.ModelId = "google/gemma-3n-e4b"
	// Model ID: google/gemma-4-26b-a4b
	// Model page: https://phaseo.app/models/google/gemma-4-26b-a4b
	ModelIDGoogleGemma426bA4b gen.ModelId = "google/gemma-4-26b-a4b"
	// Model ID: google/gemma-4-26b-a4b:free
	// Model page: https://phaseo.app/models/google/gemma-4-26b-a4b%3Afree
	ModelIDGoogleGemma426bA4bFree gen.ModelId = "google/gemma-4-26b-a4b:free"
	// Model ID: google/gemma-4-31b
	// Model page: https://phaseo.app/models/google/gemma-4-31b
	ModelIDGoogleGemma431b gen.ModelId = "google/gemma-4-31b"
	// Model ID: google/gemma-4-31b-it
	// Model page: https://phaseo.app/models/google/gemma-4-31b-it
	ModelIDGoogleGemma431bIt gen.ModelId = "google/gemma-4-31b-it"
	// Model ID: google/gemma-4-31b:free
	// Model page: https://phaseo.app/models/google/gemma-4-31b%3Afree
	ModelIDGoogleGemma431bFree gen.ModelId = "google/gemma-4-31b:free"
	// Model ID: google/lyria-3-clip-preview
	// Model page: https://phaseo.app/models/google/lyria-3-clip-preview
	ModelIDGoogleLyria3ClipPreview gen.ModelId = "google/lyria-3-clip-preview"
	// Model ID: google/lyria-3-pro-preview
	// Model page: https://phaseo.app/models/google/lyria-3-pro-preview
	ModelIDGoogleLyria3ProPreview gen.ModelId = "google/lyria-3-pro-preview"
	// Model ID: google/veo-2
	// Model page: https://phaseo.app/models/google/veo-2
	ModelIDGoogleVeo2 gen.ModelId = "google/veo-2"
	// Model ID: google/veo-3.1-fast-preview
	// Model page: https://phaseo.app/models/google/veo-3.1-fast-preview
	ModelIDGoogleVeo31FastPreview gen.ModelId = "google/veo-3.1-fast-preview"
	// Model ID: google/veo-3.1-lite-generate-preview
	// Model page: https://phaseo.app/models/google/veo-3.1-lite-generate-preview
	ModelIDGoogleVeo31LiteGeneratePreview gen.ModelId = "google/veo-3.1-lite-generate-preview"
	// Model ID: google/veo-3.1-preview
	// Model page: https://phaseo.app/models/google/veo-3.1-preview
	ModelIDGoogleVeo31Preview gen.ModelId = "google/veo-3.1-preview"
	// Model ID: ibm/granite-4.1-8b
	// Model page: https://phaseo.app/models/ibm/granite-4.1-8b
	ModelIDIbmGranite418b gen.ModelId = "ibm/granite-4.1-8b"
	// Model ID: inception/mercury-2
	// Model page: https://phaseo.app/models/inception/mercury-2
	ModelIDInceptionMercury2 gen.ModelId = "inception/mercury-2"
	// Model ID: inception/mercury-edit-2
	// Model page: https://phaseo.app/models/inception/mercury-edit-2
	ModelIDInceptionMercuryEdit2 gen.ModelId = "inception/mercury-edit-2"
	// Model ID: inclusionai/ling-2.6-1t
	// Model page: https://phaseo.app/models/inclusionai/ling-2.6-1t
	ModelIDInclusionaiLing261t gen.ModelId = "inclusionai/ling-2.6-1t"
	// Model ID: inclusionai/ling-flash-2.0
	// Model page: https://phaseo.app/models/inclusionai/ling-flash-2.0
	ModelIDInclusionaiLingFlash20 gen.ModelId = "inclusionai/ling-flash-2.0"
	// Model ID: inclusionai/ring-flash-2.0
	// Model page: https://phaseo.app/models/inclusionai/ring-flash-2.0
	ModelIDInclusionaiRingFlash20 gen.ModelId = "inclusionai/ring-flash-2.0"
	// Model ID: inflection/inflection-3-pi
	// Model page: https://phaseo.app/models/inflection/inflection-3-pi
	ModelIDInflectionInflection3Pi gen.ModelId = "inflection/inflection-3-pi"
	// Model ID: inflection/inflection-3-productivity
	// Model page: https://phaseo.app/models/inflection/inflection-3-productivity
	ModelIDInflectionInflection3Productivity gen.ModelId = "inflection/inflection-3-productivity"
	// Model ID: kwaipilot/kat-coder-air-v2.5
	// Model page: https://phaseo.app/models/kwaipilot/kat-coder-air-v2.5
	ModelIDKwaipilotKatCoderAirV25 gen.ModelId = "kwaipilot/kat-coder-air-v2.5"
	// Model ID: kwaipilot/kat-coder-exp-72b-1010
	// Model page: https://phaseo.app/models/kwaipilot/kat-coder-exp-72b-1010
	ModelIDKwaipilotKatCoderExp72b1010 gen.ModelId = "kwaipilot/kat-coder-exp-72b-1010"
	// Model ID: kwaipilot/kat-coder-pro
	// Model page: https://phaseo.app/models/kwaipilot/kat-coder-pro
	ModelIDKwaipilotKatCoderPro gen.ModelId = "kwaipilot/kat-coder-pro"
	// Model ID: kwaipilot/kat-coder-pro-v1
	// Model page: https://phaseo.app/models/kwaipilot/kat-coder-pro-v1
	ModelIDKwaipilotKatCoderProV1 gen.ModelId = "kwaipilot/kat-coder-pro-v1"
	// Model ID: kwaipilot/kat-coder-pro-v2
	// Model page: https://phaseo.app/models/kwaipilot/kat-coder-pro-v2
	ModelIDKwaipilotKatCoderProV2 gen.ModelId = "kwaipilot/kat-coder-pro-v2"
	// Model ID: kwaipilot/kat-coder-pro-v2.5
	// Model page: https://phaseo.app/models/kwaipilot/kat-coder-pro-v2.5
	ModelIDKwaipilotKatCoderProV25 gen.ModelId = "kwaipilot/kat-coder-pro-v2.5"
	// Model ID: liquid-ai/lfm-2-24b-a2b
	// Model page: https://phaseo.app/models/liquid-ai/lfm-2-24b-a2b
	ModelIDLiquidAiLfm224bA2b gen.ModelId = "liquid-ai/lfm-2-24b-a2b"
	// Model ID: meituan/longcat-2.0
	// Model page: https://phaseo.app/models/meituan/longcat-2.0
	ModelIDMeituanLongcat20 gen.ModelId = "meituan/longcat-2.0"
	// Model ID: meta/llama-3-70b
	// Model page: https://phaseo.app/models/meta/llama-3-70b
	ModelIDMetaLlama370b gen.ModelId = "meta/llama-3-70b"
	// Model ID: meta/llama-3-8b
	// Model page: https://phaseo.app/models/meta/llama-3-8b
	ModelIDMetaLlama38b gen.ModelId = "meta/llama-3-8b"
	// Model ID: meta/llama-3-8b-lite
	// Model page: https://phaseo.app/models/meta/llama-3-8b-lite
	ModelIDMetaLlama38bLite gen.ModelId = "meta/llama-3-8b-lite"
	// Model ID: meta/llama-3.1-70b
	// Model page: https://phaseo.app/models/meta/llama-3.1-70b
	ModelIDMetaLlama3170b gen.ModelId = "meta/llama-3.1-70b"
	// Model ID: meta/llama-3.1-8b
	// Model page: https://phaseo.app/models/meta/llama-3.1-8b
	ModelIDMetaLlama318b gen.ModelId = "meta/llama-3.1-8b"
	// Model ID: meta/llama-3.2-11b-vision
	// Model page: https://phaseo.app/models/meta/llama-3.2-11b-vision
	ModelIDMetaLlama3211bVision gen.ModelId = "meta/llama-3.2-11b-vision"
	// Model ID: meta/llama-3.2-3b
	// Model page: https://phaseo.app/models/meta/llama-3.2-3b
	ModelIDMetaLlama323b gen.ModelId = "meta/llama-3.2-3b"
	// Model ID: meta/llama-3.3-70b
	// Model page: https://phaseo.app/models/meta/llama-3.3-70b
	ModelIDMetaLlama3370b gen.ModelId = "meta/llama-3.3-70b"
	// Model ID: meta/llama-4-maverick
	// Model page: https://phaseo.app/models/meta/llama-4-maverick
	ModelIDMetaLlama4Maverick gen.ModelId = "meta/llama-4-maverick"
	// Model ID: meta/llama-4-scout
	// Model page: https://phaseo.app/models/meta/llama-4-scout
	ModelIDMetaLlama4Scout gen.ModelId = "meta/llama-4-scout"
	// Model ID: meta/llama-guard-4-12b
	// Model page: https://phaseo.app/models/meta/llama-guard-4-12b
	ModelIDMetaLlamaGuard412b gen.ModelId = "meta/llama-guard-4-12b"
	// Model ID: meta/llama-prompt-guard-2-22m
	// Model page: https://phaseo.app/models/meta/llama-prompt-guard-2-22m
	ModelIDMetaLlamaPromptGuard222m gen.ModelId = "meta/llama-prompt-guard-2-22m"
	// Model ID: meta/llama-prompt-guard-2-86m
	// Model page: https://phaseo.app/models/meta/llama-prompt-guard-2-86m
	ModelIDMetaLlamaPromptGuard286m gen.ModelId = "meta/llama-prompt-guard-2-86m"
	// Model ID: microsoft/phi-4
	// Model page: https://phaseo.app/models/microsoft/phi-4
	ModelIDMicrosoftPhi4 gen.ModelId = "microsoft/phi-4"
	// Model ID: microsoft/phi-4-mini
	// Model page: https://phaseo.app/models/microsoft/phi-4-mini
	ModelIDMicrosoftPhi4Mini gen.ModelId = "microsoft/phi-4-mini"
	// Model ID: minimax/hailuo-02
	// Model page: https://phaseo.app/models/minimax/hailuo-02
	ModelIDMinimaxHailuo02 gen.ModelId = "minimax/hailuo-02"
	// Model ID: minimax/hailuo-2.3
	// Model page: https://phaseo.app/models/minimax/hailuo-2.3
	ModelIDMinimaxHailuo23 gen.ModelId = "minimax/hailuo-2.3"
	// Model ID: minimax/hailuo-2.3-fast
	// Model page: https://phaseo.app/models/minimax/hailuo-2.3-fast
	ModelIDMinimaxHailuo23Fast gen.ModelId = "minimax/hailuo-2.3-fast"
	// Model ID: minimax/m2-her
	// Model page: https://phaseo.app/models/minimax/m2-her
	ModelIDMinimaxM2Her gen.ModelId = "minimax/m2-her"
	// Model ID: minimax/minimax-m1-80k
	// Model page: https://phaseo.app/models/minimax/minimax-m1-80k
	ModelIDMinimaxMinimaxM180k gen.ModelId = "minimax/minimax-m1-80k"
	// Model ID: minimax/minimax-m2
	// Model page: https://phaseo.app/models/minimax/minimax-m2
	ModelIDMinimaxMinimaxM2 gen.ModelId = "minimax/minimax-m2"
	// Model ID: minimax/minimax-m2.1
	// Model page: https://phaseo.app/models/minimax/minimax-m2.1
	ModelIDMinimaxMinimaxM21 gen.ModelId = "minimax/minimax-m2.1"
	// Model ID: minimax/minimax-m2.5
	// Model page: https://phaseo.app/models/minimax/minimax-m2.5
	ModelIDMinimaxMinimaxM25 gen.ModelId = "minimax/minimax-m2.5"
	// Model ID: minimax/minimax-m2.5-highspeed
	// Model page: https://phaseo.app/models/minimax/minimax-m2.5-highspeed
	ModelIDMinimaxMinimaxM25Highspeed gen.ModelId = "minimax/minimax-m2.5-highspeed"
	// Model ID: minimax/minimax-m2.7
	// Model page: https://phaseo.app/models/minimax/minimax-m2.7
	ModelIDMinimaxMinimaxM27 gen.ModelId = "minimax/minimax-m2.7"
	// Model ID: minimax/minimax-m3
	// Model page: https://phaseo.app/models/minimax/minimax-m3
	ModelIDMinimaxMinimaxM3 gen.ModelId = "minimax/minimax-m3"
	// Model ID: minimax/music-2.6
	// Model page: https://phaseo.app/models/minimax/music-2.6
	ModelIDMinimaxMusic26 gen.ModelId = "minimax/music-2.6"
	// Model ID: minimax/music-2.6-free
	// Model page: https://phaseo.app/models/minimax/music-2.6-free
	ModelIDMinimaxMusic26Free gen.ModelId = "minimax/music-2.6-free"
	// Model ID: mistral/codestral-embed
	// Model page: https://phaseo.app/models/mistral/codestral-embed
	ModelIDMistralCodestralEmbed gen.ModelId = "mistral/codestral-embed"
	// Model ID: mistral/devstral-2
	// Model page: https://phaseo.app/models/mistral/devstral-2
	ModelIDMistralDevstral2 gen.ModelId = "mistral/devstral-2"
	// Model ID: mistral/devstral-medium-1.0
	// Model page: https://phaseo.app/models/mistral/devstral-medium-1.0
	ModelIDMistralDevstralMedium10 gen.ModelId = "mistral/devstral-medium-1.0"
	// Model ID: mistral/devstral-small-1.1
	// Model page: https://phaseo.app/models/mistral/devstral-small-1.1
	ModelIDMistralDevstralSmall11 gen.ModelId = "mistral/devstral-small-1.1"
	// Model ID: mistral/leanstral-1.5:free
	// Model page: https://phaseo.app/models/mistral/leanstral-1.5%3Afree
	ModelIDMistralLeanstral15Free gen.ModelId = "mistral/leanstral-1.5:free"
	// Model ID: mistral/magistral-medium-1.2
	// Model page: https://phaseo.app/models/mistral/magistral-medium-1.2
	ModelIDMistralMagistralMedium12 gen.ModelId = "mistral/magistral-medium-1.2"
	// Model ID: mistral/ministral-3-14b
	// Model page: https://phaseo.app/models/mistral/ministral-3-14b
	ModelIDMistralMinistral314b gen.ModelId = "mistral/ministral-3-14b"
	// Model ID: mistral/ministral-3-3b
	// Model page: https://phaseo.app/models/mistral/ministral-3-3b
	ModelIDMistralMinistral33b gen.ModelId = "mistral/ministral-3-3b"
	// Model ID: mistral/ministral-3-8b
	// Model page: https://phaseo.app/models/mistral/ministral-3-8b
	ModelIDMistralMinistral38b gen.ModelId = "mistral/ministral-3-8b"
	// Model ID: mistral/mistral-embed
	// Model page: https://phaseo.app/models/mistral/mistral-embed
	ModelIDMistralMistralEmbed gen.ModelId = "mistral/mistral-embed"
	// Model ID: mistral/mistral-large-2.1
	// Model page: https://phaseo.app/models/mistral/mistral-large-2.1
	ModelIDMistralMistralLarge21 gen.ModelId = "mistral/mistral-large-2.1"
	// Model ID: mistral/mistral-large-3
	// Model page: https://phaseo.app/models/mistral/mistral-large-3
	ModelIDMistralMistralLarge3 gen.ModelId = "mistral/mistral-large-3"
	// Model ID: mistral/mistral-medium-3.0
	// Model page: https://phaseo.app/models/mistral/mistral-medium-3.0
	ModelIDMistralMistralMedium30 gen.ModelId = "mistral/mistral-medium-3.0"
	// Model ID: mistral/mistral-medium-3.1
	// Model page: https://phaseo.app/models/mistral/mistral-medium-3.1
	ModelIDMistralMistralMedium31 gen.ModelId = "mistral/mistral-medium-3.1"
	// Model ID: mistral/mistral-medium-3.5
	// Model page: https://phaseo.app/models/mistral/mistral-medium-3.5
	ModelIDMistralMistralMedium35 gen.ModelId = "mistral/mistral-medium-3.5"
	// Model ID: mistral/mistral-moderation
	// Model page: https://phaseo.app/models/mistral/mistral-moderation
	ModelIDMistralMistralModeration gen.ModelId = "mistral/mistral-moderation"
	// Model ID: mistral/mistral-moderation-2
	// Model page: https://phaseo.app/models/mistral/mistral-moderation-2
	ModelIDMistralMistralModeration2 gen.ModelId = "mistral/mistral-moderation-2"
	// Model ID: mistral/mistral-nemo-12b
	// Model page: https://phaseo.app/models/mistral/mistral-nemo-12b
	ModelIDMistralMistralNemo12b gen.ModelId = "mistral/mistral-nemo-12b"
	// Model ID: mistral/mistral-nemo-2407
	// Model page: https://phaseo.app/models/mistral/mistral-nemo-2407
	ModelIDMistralMistralNemo2407 gen.ModelId = "mistral/mistral-nemo-2407"
	// Model ID: mistral/mistral-small-24b-2501
	// Model page: https://phaseo.app/models/mistral/mistral-small-24b-2501
	ModelIDMistralMistralSmall24b2501 gen.ModelId = "mistral/mistral-small-24b-2501"
	// Model ID: mistral/mistral-small-3.2
	// Model page: https://phaseo.app/models/mistral/mistral-small-3.2
	ModelIDMistralMistralSmall32 gen.ModelId = "mistral/mistral-small-3.2"
	// Model ID: mistral/mistral-small-4
	// Model page: https://phaseo.app/models/mistral/mistral-small-4
	ModelIDMistralMistralSmall4 gen.ModelId = "mistral/mistral-small-4"
	// Model ID: mistral/mixtral-8x7b
	// Model page: https://phaseo.app/models/mistral/mixtral-8x7b
	ModelIDMistralMixtral8x7b gen.ModelId = "mistral/mixtral-8x7b"
	// Model ID: mistral/pixtral-large
	// Model page: https://phaseo.app/models/mistral/pixtral-large
	ModelIDMistralPixtralLarge gen.ModelId = "mistral/pixtral-large"
	// Model ID: mistralai/mistral-nemo
	// Model page: https://phaseo.app/models/mistralai/mistral-nemo
	ModelIDMistralaiMistralNemo gen.ModelId = "mistralai/mistral-nemo"
	// Model ID: moonshotai/kimi-k2
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2
	ModelIDMoonshotaiKimiK2 gen.ModelId = "moonshotai/kimi-k2"
	// Model ID: moonshotai/kimi-k2-0905
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2-0905
	ModelIDMoonshotaiKimiK20905 gen.ModelId = "moonshotai/kimi-k2-0905"
	// Model ID: moonshotai/kimi-k2-instruct
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2-instruct
	ModelIDMoonshotaiKimiK2Instruct gen.ModelId = "moonshotai/kimi-k2-instruct"
	// Model ID: moonshotai/kimi-k2-instruct-0905
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2-instruct-0905
	ModelIDMoonshotaiKimiK2Instruct0905 gen.ModelId = "moonshotai/kimi-k2-instruct-0905"
	// Model ID: moonshotai/kimi-k2-thinking
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2-thinking
	ModelIDMoonshotaiKimiK2Thinking gen.ModelId = "moonshotai/kimi-k2-thinking"
	// Model ID: moonshotai/kimi-k2.5
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2.5
	ModelIDMoonshotaiKimiK25 gen.ModelId = "moonshotai/kimi-k2.5"
	// Model ID: moonshotai/kimi-k2.5-lightning
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2.5-lightning
	ModelIDMoonshotaiKimiK25Lightning gen.ModelId = "moonshotai/kimi-k2.5-lightning"
	// Model ID: moonshotai/kimi-k2.6
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2.6
	ModelIDMoonshotaiKimiK26 gen.ModelId = "moonshotai/kimi-k2.6"
	// Model ID: moonshotai/kimi-k2.7-code
	// Model page: https://phaseo.app/models/moonshotai/kimi-k2.7-code
	ModelIDMoonshotaiKimiK27Code gen.ModelId = "moonshotai/kimi-k2.7-code"
	// Model ID: moonshotai/moonshot-v1-128k
	// Model page: https://phaseo.app/models/moonshotai/moonshot-v1-128k
	ModelIDMoonshotaiMoonshotV1128k gen.ModelId = "moonshotai/moonshot-v1-128k"
	// Model ID: moonshotai/moonshot-v1-128k-vision-preview
	// Model page: https://phaseo.app/models/moonshotai/moonshot-v1-128k-vision-preview
	ModelIDMoonshotaiMoonshotV1128kVisionPreview gen.ModelId = "moonshotai/moonshot-v1-128k-vision-preview"
	// Model ID: moonshotai/moonshot-v1-32k
	// Model page: https://phaseo.app/models/moonshotai/moonshot-v1-32k
	ModelIDMoonshotaiMoonshotV132k gen.ModelId = "moonshotai/moonshot-v1-32k"
	// Model ID: moonshotai/moonshot-v1-32k-vision-preview
	// Model page: https://phaseo.app/models/moonshotai/moonshot-v1-32k-vision-preview
	ModelIDMoonshotaiMoonshotV132kVisionPreview gen.ModelId = "moonshotai/moonshot-v1-32k-vision-preview"
	// Model ID: moonshotai/moonshot-v1-8k
	// Model page: https://phaseo.app/models/moonshotai/moonshot-v1-8k
	ModelIDMoonshotaiMoonshotV18k gen.ModelId = "moonshotai/moonshot-v1-8k"
	// Model ID: moonshotai/moonshot-v1-8k-vision-preview
	// Model page: https://phaseo.app/models/moonshotai/moonshot-v1-8k-vision-preview
	ModelIDMoonshotaiMoonshotV18kVisionPreview gen.ModelId = "moonshotai/moonshot-v1-8k-vision-preview"
	// Model ID: morph/morph-v3-fast
	// Model page: https://phaseo.app/models/morph/morph-v3-fast
	ModelIDMorphMorphV3Fast gen.ModelId = "morph/morph-v3-fast"
	// Model ID: morph/morph-v3-large
	// Model page: https://phaseo.app/models/morph/morph-v3-large
	ModelIDMorphMorphV3Large gen.ModelId = "morph/morph-v3-large"
	// Model ID: nex-agi/deepseek-v3.1-nex-n1
	// Model page: https://phaseo.app/models/nex-agi/deepseek-v3.1-nex-n1
	ModelIDNexAgiDeepseekV31NexN1 gen.ModelId = "nex-agi/deepseek-v3.1-nex-n1"
	// Model ID: nex-agi/nex-n2-pro
	// Model page: https://phaseo.app/models/nex-agi/nex-n2-pro
	ModelIDNexAgiNexN2Pro gen.ModelId = "nex-agi/nex-n2-pro"
	// Model ID: nous/hermes-3-llama-3.1-405b
	// Model page: https://phaseo.app/models/nous/hermes-3-llama-3.1-405b
	ModelIDNousHermes3Llama31405b gen.ModelId = "nous/hermes-3-llama-3.1-405b"
	// Model ID: nousresearch/hermes-3-llama-3.1-405b
	// Model page: https://phaseo.app/models/nousresearch/hermes-3-llama-3.1-405b
	ModelIDNousresearchHermes3Llama31405b gen.ModelId = "nousresearch/hermes-3-llama-3.1-405b"
	// Model ID: nousresearch/hermes-3-llama-3.1-70b
	// Model page: https://phaseo.app/models/nousresearch/hermes-3-llama-3.1-70b
	ModelIDNousresearchHermes3Llama3170b gen.ModelId = "nousresearch/hermes-3-llama-3.1-70b"
	// Model ID: nousresearch/hermes-4-405b
	// Model page: https://phaseo.app/models/nousresearch/hermes-4-405b
	ModelIDNousresearchHermes4405b gen.ModelId = "nousresearch/hermes-4-405b"
	// Model ID: nousresearch/hermes-4-70b
	// Model page: https://phaseo.app/models/nousresearch/hermes-4-70b
	ModelIDNousresearchHermes470b gen.ModelId = "nousresearch/hermes-4-70b"
	// Model ID: nvidia/cosmos3-super-reasoner
	// Model page: https://phaseo.app/models/nvidia/cosmos3-super-reasoner
	ModelIDNvidiaCosmos3SuperReasoner gen.ModelId = "nvidia/cosmos3-super-reasoner"
	// Model ID: nvidia/llama-3.1-nemotron-70b-instruct
	// Model page: https://phaseo.app/models/nvidia/llama-3.1-nemotron-70b-instruct
	ModelIDNvidiaLlama31Nemotron70bInstruct gen.ModelId = "nvidia/llama-3.1-nemotron-70b-instruct"
	// Model ID: nvidia/llama-3.1-nemotron-ultra-253b
	// Model page: https://phaseo.app/models/nvidia/llama-3.1-nemotron-ultra-253b
	ModelIDNvidiaLlama31NemotronUltra253b gen.ModelId = "nvidia/llama-3.1-nemotron-ultra-253b"
	// Model ID: nvidia/llama-3.3-nemotron-super-49b-v1.5
	// Model page: https://phaseo.app/models/nvidia/llama-3.3-nemotron-super-49b-v1.5
	ModelIDNvidiaLlama33NemotronSuper49bV15 gen.ModelId = "nvidia/llama-3.3-nemotron-super-49b-v1.5"
	// Model ID: nvidia/nemotron-3-nano-30b-a3b
	// Model page: https://phaseo.app/models/nvidia/nemotron-3-nano-30b-a3b
	ModelIDNvidiaNemotron3Nano30bA3b gen.ModelId = "nvidia/nemotron-3-nano-30b-a3b"
	// Model ID: nvidia/nemotron-3-nano-omni-30b-a3b-reasoning
	// Model page: https://phaseo.app/models/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning
	ModelIDNvidiaNemotron3NanoOmni30bA3bReasoning gen.ModelId = "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning"
	// Model ID: nvidia/nemotron-3-super-120b-a12b
	// Model page: https://phaseo.app/models/nvidia/nemotron-3-super-120b-a12b
	ModelIDNvidiaNemotron3Super120bA12b gen.ModelId = "nvidia/nemotron-3-super-120b-a12b"
	// Model ID: nvidia/nemotron-3-ultra-550b-a55b
	// Model page: https://phaseo.app/models/nvidia/nemotron-3-ultra-550b-a55b
	ModelIDNvidiaNemotron3Ultra550bA55b gen.ModelId = "nvidia/nemotron-3-ultra-550b-a55b"
	// Model ID: nvidia/nvidia-nemotron-3-nano-30b-a3b
	// Model page: https://phaseo.app/models/nvidia/nvidia-nemotron-3-nano-30b-a3b
	ModelIDNvidiaNvidiaNemotron3Nano30bA3b gen.ModelId = "nvidia/nvidia-nemotron-3-nano-30b-a3b"
	// Model ID: nvidia/nvidia-nemotron-nano-12b-v2-vl
	// Model page: https://phaseo.app/models/nvidia/nvidia-nemotron-nano-12b-v2-vl
	ModelIDNvidiaNvidiaNemotronNano12bV2Vl gen.ModelId = "nvidia/nvidia-nemotron-nano-12b-v2-vl"
	// Model ID: openai/babbage-002
	// Model page: https://phaseo.app/models/openai/babbage-002
	ModelIDOpenaiBabbage002 gen.ModelId = "openai/babbage-002"
	// Model ID: openai/chat-latest
	// Model page: https://phaseo.app/models/openai/chat-latest
	ModelIDOpenaiChatLatest gen.ModelId = "openai/chat-latest"
	// Model ID: openai/chatgpt-4o
	// Model page: https://phaseo.app/models/openai/chatgpt-4o
	ModelIDOpenaiChatgpt4o gen.ModelId = "openai/chatgpt-4o"
	// Model ID: openai/computer-use-preview
	// Model page: https://phaseo.app/models/openai/computer-use-preview
	ModelIDOpenaiComputerUsePreview gen.ModelId = "openai/computer-use-preview"
	// Model ID: openai/davinci-002
	// Model page: https://phaseo.app/models/openai/davinci-002
	ModelIDOpenaiDavinci002 gen.ModelId = "openai/davinci-002"
	// Model ID: openai/gpt-3.5-turbo-16k
	// Model page: https://phaseo.app/models/openai/gpt-3.5-turbo-16k
	ModelIDOpenaiGpt35Turbo16k gen.ModelId = "openai/gpt-3.5-turbo-16k"
	// Model ID: openai/gpt-3.5-turbo-2023-03-21
	// Model page: https://phaseo.app/models/openai/gpt-3.5-turbo-2023-03-21
	ModelIDOpenaiGpt35Turbo20230321 gen.ModelId = "openai/gpt-3.5-turbo-2023-03-21"
	// Model ID: openai/gpt-4-2023-06-13
	// Model page: https://phaseo.app/models/openai/gpt-4-2023-06-13
	ModelIDOpenaiGpt420230613 gen.ModelId = "openai/gpt-4-2023-06-13"
	// Model ID: openai/gpt-4-turbo-2023-03-14
	// Model page: https://phaseo.app/models/openai/gpt-4-turbo-2023-03-14
	ModelIDOpenaiGpt4Turbo20230314 gen.ModelId = "openai/gpt-4-turbo-2023-03-14"
	// Model ID: openai/gpt-4-turbo-2023-11-06
	// Model page: https://phaseo.app/models/openai/gpt-4-turbo-2023-11-06
	ModelIDOpenaiGpt4Turbo20231106 gen.ModelId = "openai/gpt-4-turbo-2023-11-06"
	// Model ID: openai/gpt-4-turbo-2024-01-25
	// Model page: https://phaseo.app/models/openai/gpt-4-turbo-2024-01-25
	ModelIDOpenaiGpt4Turbo20240125 gen.ModelId = "openai/gpt-4-turbo-2024-01-25"
	// Model ID: openai/gpt-4.1
	// Model page: https://phaseo.app/models/openai/gpt-4.1
	ModelIDOpenaiGpt41 gen.ModelId = "openai/gpt-4.1"
	// Model ID: openai/gpt-4.1-mini
	// Model page: https://phaseo.app/models/openai/gpt-4.1-mini
	ModelIDOpenaiGpt41Mini gen.ModelId = "openai/gpt-4.1-mini"
	// Model ID: openai/gpt-4.1-nano
	// Model page: https://phaseo.app/models/openai/gpt-4.1-nano
	ModelIDOpenaiGpt41Nano gen.ModelId = "openai/gpt-4.1-nano"
	// Model ID: openai/gpt-4o-2024-05-13
	// Model page: https://phaseo.app/models/openai/gpt-4o-2024-05-13
	ModelIDOpenaiGpt4o20240513 gen.ModelId = "openai/gpt-4o-2024-05-13"
	// Model ID: openai/gpt-4o-2024-08-06
	// Model page: https://phaseo.app/models/openai/gpt-4o-2024-08-06
	ModelIDOpenaiGpt4o20240806 gen.ModelId = "openai/gpt-4o-2024-08-06"
	// Model ID: openai/gpt-4o-2024-11-20
	// Model page: https://phaseo.app/models/openai/gpt-4o-2024-11-20
	ModelIDOpenaiGpt4o20241120 gen.ModelId = "openai/gpt-4o-2024-11-20"
	// Model ID: openai/gpt-4o-mini
	// Model page: https://phaseo.app/models/openai/gpt-4o-mini
	ModelIDOpenaiGpt4oMini gen.ModelId = "openai/gpt-4o-mini"
	// Model ID: openai/gpt-4o-mini-transcribe
	// Model page: https://phaseo.app/models/openai/gpt-4o-mini-transcribe
	ModelIDOpenaiGpt4oMiniTranscribe gen.ModelId = "openai/gpt-4o-mini-transcribe"
	// Model ID: openai/gpt-4o-mini-tts
	// Model page: https://phaseo.app/models/openai/gpt-4o-mini-tts
	ModelIDOpenaiGpt4oMiniTts gen.ModelId = "openai/gpt-4o-mini-tts"
	// Model ID: openai/gpt-4o-transcribe
	// Model page: https://phaseo.app/models/openai/gpt-4o-transcribe
	ModelIDOpenaiGpt4oTranscribe gen.ModelId = "openai/gpt-4o-transcribe"
	// Model ID: openai/gpt-5
	// Model page: https://phaseo.app/models/openai/gpt-5
	ModelIDOpenaiGpt5 gen.ModelId = "openai/gpt-5"
	// Model ID: openai/gpt-5-chat
	// Model page: https://phaseo.app/models/openai/gpt-5-chat
	ModelIDOpenaiGpt5Chat gen.ModelId = "openai/gpt-5-chat"
	// Model ID: openai/gpt-5-codex
	// Model page: https://phaseo.app/models/openai/gpt-5-codex
	ModelIDOpenaiGpt5Codex gen.ModelId = "openai/gpt-5-codex"
	// Model ID: openai/gpt-5-mini
	// Model page: https://phaseo.app/models/openai/gpt-5-mini
	ModelIDOpenaiGpt5Mini gen.ModelId = "openai/gpt-5-mini"
	// Model ID: openai/gpt-5-nano
	// Model page: https://phaseo.app/models/openai/gpt-5-nano
	ModelIDOpenaiGpt5Nano gen.ModelId = "openai/gpt-5-nano"
	// Model ID: openai/gpt-5-pro
	// Model page: https://phaseo.app/models/openai/gpt-5-pro
	ModelIDOpenaiGpt5Pro gen.ModelId = "openai/gpt-5-pro"
	// Model ID: openai/gpt-5.1
	// Model page: https://phaseo.app/models/openai/gpt-5.1
	ModelIDOpenaiGpt51 gen.ModelId = "openai/gpt-5.1"
	// Model ID: openai/gpt-5.1-chat
	// Model page: https://phaseo.app/models/openai/gpt-5.1-chat
	ModelIDOpenaiGpt51Chat gen.ModelId = "openai/gpt-5.1-chat"
	// Model ID: openai/gpt-5.1-codex
	// Model page: https://phaseo.app/models/openai/gpt-5.1-codex
	ModelIDOpenaiGpt51Codex gen.ModelId = "openai/gpt-5.1-codex"
	// Model ID: openai/gpt-5.1-codex-max
	// Model page: https://phaseo.app/models/openai/gpt-5.1-codex-max
	ModelIDOpenaiGpt51CodexMax gen.ModelId = "openai/gpt-5.1-codex-max"
	// Model ID: openai/gpt-5.1-codex-mini
	// Model page: https://phaseo.app/models/openai/gpt-5.1-codex-mini
	ModelIDOpenaiGpt51CodexMini gen.ModelId = "openai/gpt-5.1-codex-mini"
	// Model ID: openai/gpt-5.2
	// Model page: https://phaseo.app/models/openai/gpt-5.2
	ModelIDOpenaiGpt52 gen.ModelId = "openai/gpt-5.2"
	// Model ID: openai/gpt-5.2-chat
	// Model page: https://phaseo.app/models/openai/gpt-5.2-chat
	ModelIDOpenaiGpt52Chat gen.ModelId = "openai/gpt-5.2-chat"
	// Model ID: openai/gpt-5.2-codex
	// Model page: https://phaseo.app/models/openai/gpt-5.2-codex
	ModelIDOpenaiGpt52Codex gen.ModelId = "openai/gpt-5.2-codex"
	// Model ID: openai/gpt-5.2-pro
	// Model page: https://phaseo.app/models/openai/gpt-5.2-pro
	ModelIDOpenaiGpt52Pro gen.ModelId = "openai/gpt-5.2-pro"
	// Model ID: openai/gpt-5.3-chat
	// Model page: https://phaseo.app/models/openai/gpt-5.3-chat
	ModelIDOpenaiGpt53Chat gen.ModelId = "openai/gpt-5.3-chat"
	// Model ID: openai/gpt-5.3-codex
	// Model page: https://phaseo.app/models/openai/gpt-5.3-codex
	ModelIDOpenaiGpt53Codex gen.ModelId = "openai/gpt-5.3-codex"
	// Model ID: openai/gpt-5.4
	// Model page: https://phaseo.app/models/openai/gpt-5.4
	ModelIDOpenaiGpt54 gen.ModelId = "openai/gpt-5.4"
	// Model ID: openai/gpt-5.4-mini
	// Model page: https://phaseo.app/models/openai/gpt-5.4-mini
	ModelIDOpenaiGpt54Mini gen.ModelId = "openai/gpt-5.4-mini"
	// Model ID: openai/gpt-5.4-nano
	// Model page: https://phaseo.app/models/openai/gpt-5.4-nano
	ModelIDOpenaiGpt54Nano gen.ModelId = "openai/gpt-5.4-nano"
	// Model ID: openai/gpt-5.4-pro
	// Model page: https://phaseo.app/models/openai/gpt-5.4-pro
	ModelIDOpenaiGpt54Pro gen.ModelId = "openai/gpt-5.4-pro"
	// Model ID: openai/gpt-5.5
	// Model page: https://phaseo.app/models/openai/gpt-5.5
	ModelIDOpenaiGpt55 gen.ModelId = "openai/gpt-5.5"
	// Model ID: openai/gpt-5.5-pro
	// Model page: https://phaseo.app/models/openai/gpt-5.5-pro
	ModelIDOpenaiGpt55Pro gen.ModelId = "openai/gpt-5.5-pro"
	// Model ID: openai/gpt-image-1
	// Model page: https://phaseo.app/models/openai/gpt-image-1
	ModelIDOpenaiGptImage1 gen.ModelId = "openai/gpt-image-1"
	// Model ID: openai/gpt-image-1-mini
	// Model page: https://phaseo.app/models/openai/gpt-image-1-mini
	ModelIDOpenaiGptImage1Mini gen.ModelId = "openai/gpt-image-1-mini"
	// Model ID: openai/gpt-image-1.5
	// Model page: https://phaseo.app/models/openai/gpt-image-1.5
	ModelIDOpenaiGptImage15 gen.ModelId = "openai/gpt-image-1.5"
	// Model ID: openai/gpt-image-2
	// Model page: https://phaseo.app/models/openai/gpt-image-2
	ModelIDOpenaiGptImage2 gen.ModelId = "openai/gpt-image-2"
	// Model ID: openai/gpt-oss-120b
	// Model page: https://phaseo.app/models/openai/gpt-oss-120b
	ModelIDOpenaiGptOss120b gen.ModelId = "openai/gpt-oss-120b"
	// Model ID: openai/gpt-oss-20b
	// Model page: https://phaseo.app/models/openai/gpt-oss-20b
	ModelIDOpenaiGptOss20b gen.ModelId = "openai/gpt-oss-20b"
	// Model ID: openai/gpt-oss-safeguard-20b
	// Model page: https://phaseo.app/models/openai/gpt-oss-safeguard-20b
	ModelIDOpenaiGptOssSafeguard20b gen.ModelId = "openai/gpt-oss-safeguard-20b"
	// Model ID: openai/o1
	// Model page: https://phaseo.app/models/openai/o1
	ModelIDOpenaiO1 gen.ModelId = "openai/o1"
	// Model ID: openai/o1-mini
	// Model page: https://phaseo.app/models/openai/o1-mini
	ModelIDOpenaiO1Mini gen.ModelId = "openai/o1-mini"
	// Model ID: openai/o1-pro
	// Model page: https://phaseo.app/models/openai/o1-pro
	ModelIDOpenaiO1Pro gen.ModelId = "openai/o1-pro"
	// Model ID: openai/o3
	// Model page: https://phaseo.app/models/openai/o3
	ModelIDOpenaiO3 gen.ModelId = "openai/o3"
	// Model ID: openai/o3-deep-research
	// Model page: https://phaseo.app/models/openai/o3-deep-research
	ModelIDOpenaiO3DeepResearch gen.ModelId = "openai/o3-deep-research"
	// Model ID: openai/o3-mini
	// Model page: https://phaseo.app/models/openai/o3-mini
	ModelIDOpenaiO3Mini gen.ModelId = "openai/o3-mini"
	// Model ID: openai/o3-pro
	// Model page: https://phaseo.app/models/openai/o3-pro
	ModelIDOpenaiO3Pro gen.ModelId = "openai/o3-pro"
	// Model ID: openai/o4-mini
	// Model page: https://phaseo.app/models/openai/o4-mini
	ModelIDOpenaiO4Mini gen.ModelId = "openai/o4-mini"
	// Model ID: openai/o4-mini-deep-research
	// Model page: https://phaseo.app/models/openai/o4-mini-deep-research
	ModelIDOpenaiO4MiniDeepResearch gen.ModelId = "openai/o4-mini-deep-research"
	// Model ID: openai/omni-moderation
	// Model page: https://phaseo.app/models/openai/omni-moderation
	ModelIDOpenaiOmniModeration gen.ModelId = "openai/omni-moderation"
	// Model ID: openai/sora-2
	// Model page: https://phaseo.app/models/openai/sora-2
	ModelIDOpenaiSora2 gen.ModelId = "openai/sora-2"
	// Model ID: openai/sora-2-pro
	// Model page: https://phaseo.app/models/openai/sora-2-pro
	ModelIDOpenaiSora2Pro gen.ModelId = "openai/sora-2-pro"
	// Model ID: openai/text-embedding-3-large
	// Model page: https://phaseo.app/models/openai/text-embedding-3-large
	ModelIDOpenaiTextEmbedding3Large gen.ModelId = "openai/text-embedding-3-large"
	// Model ID: openai/text-embedding-3-small
	// Model page: https://phaseo.app/models/openai/text-embedding-3-small
	ModelIDOpenaiTextEmbedding3Small gen.ModelId = "openai/text-embedding-3-small"
	// Model ID: openai/text-embedding-ada-002
	// Model page: https://phaseo.app/models/openai/text-embedding-ada-002
	ModelIDOpenaiTextEmbeddingAda002 gen.ModelId = "openai/text-embedding-ada-002"
	// Model ID: openai/whisper-1
	// Model page: https://phaseo.app/models/openai/whisper-1
	ModelIDOpenaiWhisper1 gen.ModelId = "openai/whisper-1"
	// Model ID: phaseo/free
	// Model page: https://phaseo.app/models/phaseo/free
	ModelIDPhaseoFree gen.ModelId = "phaseo/free"
	// Model ID: poolside/laguna-m.1:free
	// Model page: https://phaseo.app/models/poolside/laguna-m.1%3Afree
	ModelIDPoolsideLagunaM1Free gen.ModelId = "poolside/laguna-m.1:free"
	// Model ID: poolside/laguna-xs-2.1:free
	// Model page: https://phaseo.app/models/poolside/laguna-xs-2.1%3Afree
	ModelIDPoolsideLagunaXs21Free gen.ModelId = "poolside/laguna-xs-2.1:free"
	// Model ID: qwen/qvq-max
	// Model page: https://phaseo.app/models/qwen/qvq-max
	ModelIDQwenQvqMax gen.ModelId = "qwen/qvq-max"
	// Model ID: qwen/qwen-3.6-plus
	// Model page: https://phaseo.app/models/qwen/qwen-3.6-plus
	ModelIDQwenQwen36Plus gen.ModelId = "qwen/qwen-3.6-plus"
	// Model ID: qwen/qwen-flash
	// Model page: https://phaseo.app/models/qwen/qwen-flash
	ModelIDQwenQwenFlash gen.ModelId = "qwen/qwen-flash"
	// Model ID: qwen/qwen-flash-character
	// Model page: https://phaseo.app/models/qwen/qwen-flash-character
	ModelIDQwenQwenFlashCharacter gen.ModelId = "qwen/qwen-flash-character"
	// Model ID: qwen/qwen-max
	// Model page: https://phaseo.app/models/qwen/qwen-max
	ModelIDQwenQwenMax gen.ModelId = "qwen/qwen-max"
	// Model ID: qwen/qwen-mt-flash
	// Model page: https://phaseo.app/models/qwen/qwen-mt-flash
	ModelIDQwenQwenMtFlash gen.ModelId = "qwen/qwen-mt-flash"
	// Model ID: qwen/qwen-mt-lite
	// Model page: https://phaseo.app/models/qwen/qwen-mt-lite
	ModelIDQwenQwenMtLite gen.ModelId = "qwen/qwen-mt-lite"
	// Model ID: qwen/qwen-mt-plus
	// Model page: https://phaseo.app/models/qwen/qwen-mt-plus
	ModelIDQwenQwenMtPlus gen.ModelId = "qwen/qwen-mt-plus"
	// Model ID: qwen/qwen-mt-turbo
	// Model page: https://phaseo.app/models/qwen/qwen-mt-turbo
	ModelIDQwenQwenMtTurbo gen.ModelId = "qwen/qwen-mt-turbo"
	// Model ID: qwen/qwen-plus-2025-01-25
	// Model page: https://phaseo.app/models/qwen/qwen-plus-2025-01-25
	ModelIDQwenQwenPlus20250125 gen.ModelId = "qwen/qwen-plus-2025-01-25"
	// Model ID: qwen/qwen-plus-2025-04-28
	// Model page: https://phaseo.app/models/qwen/qwen-plus-2025-04-28
	ModelIDQwenQwenPlus20250428 gen.ModelId = "qwen/qwen-plus-2025-04-28"
	// Model ID: qwen/qwen-plus-2025-07-14
	// Model page: https://phaseo.app/models/qwen/qwen-plus-2025-07-14
	ModelIDQwenQwenPlus20250714 gen.ModelId = "qwen/qwen-plus-2025-07-14"
	// Model ID: qwen/qwen-plus-2025-07-28
	// Model page: https://phaseo.app/models/qwen/qwen-plus-2025-07-28
	ModelIDQwenQwenPlus20250728 gen.ModelId = "qwen/qwen-plus-2025-07-28"
	// Model ID: qwen/qwen-plus-2025-09-11
	// Model page: https://phaseo.app/models/qwen/qwen-plus-2025-09-11
	ModelIDQwenQwenPlus20250911 gen.ModelId = "qwen/qwen-plus-2025-09-11"
	// Model ID: qwen/qwen-plus-2025-12-01
	// Model page: https://phaseo.app/models/qwen/qwen-plus-2025-12-01
	ModelIDQwenQwenPlus20251201 gen.ModelId = "qwen/qwen-plus-2025-12-01"
	// Model ID: qwen/qwen-plus-character
	// Model page: https://phaseo.app/models/qwen/qwen-plus-character
	ModelIDQwenQwenPlusCharacter gen.ModelId = "qwen/qwen-plus-character"
	// Model ID: qwen/qwen-turbo-2024-11-01
	// Model page: https://phaseo.app/models/qwen/qwen-turbo-2024-11-01
	ModelIDQwenQwenTurbo20241101 gen.ModelId = "qwen/qwen-turbo-2024-11-01"
	// Model ID: qwen/qwen-turbo-2025-04-28
	// Model page: https://phaseo.app/models/qwen/qwen-turbo-2025-04-28
	ModelIDQwenQwenTurbo20250428 gen.ModelId = "qwen/qwen-turbo-2025-04-28"
	// Model ID: qwen/qwen-vl-max-2025-04-08
	// Model page: https://phaseo.app/models/qwen/qwen-vl-max-2025-04-08
	ModelIDQwenQwenVlMax20250408 gen.ModelId = "qwen/qwen-vl-max-2025-04-08"
	// Model ID: qwen/qwen-vl-max-2025-08-13
	// Model page: https://phaseo.app/models/qwen/qwen-vl-max-2025-08-13
	ModelIDQwenQwenVlMax20250813 gen.ModelId = "qwen/qwen-vl-max-2025-08-13"
	// Model ID: qwen/qwen-vl-plus-2025-01-25
	// Model page: https://phaseo.app/models/qwen/qwen-vl-plus-2025-01-25
	ModelIDQwenQwenVlPlus20250125 gen.ModelId = "qwen/qwen-vl-plus-2025-01-25"
	// Model ID: qwen/qwen-vl-plus-2025-05-07
	// Model page: https://phaseo.app/models/qwen/qwen-vl-plus-2025-05-07
	ModelIDQwenQwenVlPlus20250507 gen.ModelId = "qwen/qwen-vl-plus-2025-05-07"
	// Model ID: qwen/qwen-vl-plus-2025-08-15
	// Model page: https://phaseo.app/models/qwen/qwen-vl-plus-2025-08-15
	ModelIDQwenQwenVlPlus20250815 gen.ModelId = "qwen/qwen-vl-plus-2025-08-15"
	// Model ID: qwen/qwen2.5-14b
	// Model page: https://phaseo.app/models/qwen/qwen2.5-14b
	ModelIDQwenQwen2514b gen.ModelId = "qwen/qwen2.5-14b"
	// Model ID: qwen/qwen2.5-14b-1m
	// Model page: https://phaseo.app/models/qwen/qwen2.5-14b-1m
	ModelIDQwenQwen2514b1m gen.ModelId = "qwen/qwen2.5-14b-1m"
	// Model ID: qwen/qwen2.5-32b
	// Model page: https://phaseo.app/models/qwen/qwen2.5-32b
	ModelIDQwenQwen2532b gen.ModelId = "qwen/qwen2.5-32b"
	// Model ID: qwen/qwen2.5-72b
	// Model page: https://phaseo.app/models/qwen/qwen2.5-72b
	ModelIDQwenQwen2572b gen.ModelId = "qwen/qwen2.5-72b"
	// Model ID: qwen/qwen2.5-7b
	// Model page: https://phaseo.app/models/qwen/qwen2.5-7b
	ModelIDQwenQwen257b gen.ModelId = "qwen/qwen2.5-7b"
	// Model ID: qwen/qwen2.5-7b-1m
	// Model page: https://phaseo.app/models/qwen/qwen2.5-7b-1m
	ModelIDQwenQwen257b1m gen.ModelId = "qwen/qwen2.5-7b-1m"
	// Model ID: qwen/qwen2.5-coder-7b
	// Model page: https://phaseo.app/models/qwen/qwen2.5-coder-7b
	ModelIDQwenQwen25Coder7b gen.ModelId = "qwen/qwen2.5-coder-7b"
	// Model ID: qwen/qwen2.5-vl-32b
	// Model page: https://phaseo.app/models/qwen/qwen2.5-vl-32b
	ModelIDQwenQwen25Vl32b gen.ModelId = "qwen/qwen2.5-vl-32b"
	// Model ID: qwen/qwen2.5-vl-32b-instruct
	// Model page: https://phaseo.app/models/qwen/qwen2.5-vl-32b-instruct
	ModelIDQwenQwen25Vl32bInstruct gen.ModelId = "qwen/qwen2.5-vl-32b-instruct"
	// Model ID: qwen/qwen2.5-vl-72b
	// Model page: https://phaseo.app/models/qwen/qwen2.5-vl-72b
	ModelIDQwenQwen25Vl72b gen.ModelId = "qwen/qwen2.5-vl-72b"
	// Model ID: qwen/qwen2.5-vl-72b-instruct
	// Model page: https://phaseo.app/models/qwen/qwen2.5-vl-72b-instruct
	ModelIDQwenQwen25Vl72bInstruct gen.ModelId = "qwen/qwen2.5-vl-72b-instruct"
	// Model ID: qwen/qwen2.5-vl-7b
	// Model page: https://phaseo.app/models/qwen/qwen2.5-vl-7b
	ModelIDQwenQwen25Vl7b gen.ModelId = "qwen/qwen2.5-vl-7b"
	// Model ID: qwen/qwen3-0.6b
	// Model page: https://phaseo.app/models/qwen/qwen3-0.6b
	ModelIDQwenQwen306b gen.ModelId = "qwen/qwen3-0.6b"
	// Model ID: qwen/qwen3-1.7b
	// Model page: https://phaseo.app/models/qwen/qwen3-1.7b
	ModelIDQwenQwen317b gen.ModelId = "qwen/qwen3-1.7b"
	// Model ID: qwen/qwen3-14b
	// Model page: https://phaseo.app/models/qwen/qwen3-14b
	ModelIDQwenQwen314b gen.ModelId = "qwen/qwen3-14b"
	// Model ID: qwen/qwen3-235b-a22b-2507
	// Model page: https://phaseo.app/models/qwen/qwen3-235b-a22b-2507
	ModelIDQwenQwen3235bA22b2507 gen.ModelId = "qwen/qwen3-235b-a22b-2507"
	// Model ID: qwen/qwen3-235b-a22b-instruct-2507
	// Model page: https://phaseo.app/models/qwen/qwen3-235b-a22b-instruct-2507
	ModelIDQwenQwen3235bA22bInstruct2507 gen.ModelId = "qwen/qwen3-235b-a22b-instruct-2507"
	// Model ID: qwen/qwen3-235b-a22b-thinking-2507
	// Model page: https://phaseo.app/models/qwen/qwen3-235b-a22b-thinking-2507
	ModelIDQwenQwen3235bA22bThinking2507 gen.ModelId = "qwen/qwen3-235b-a22b-thinking-2507"
	// Model ID: qwen/qwen3-30b-a3b
	// Model page: https://phaseo.app/models/qwen/qwen3-30b-a3b
	ModelIDQwenQwen330bA3b gen.ModelId = "qwen/qwen3-30b-a3b"
	// Model ID: qwen/qwen3-30b-a3b-2507
	// Model page: https://phaseo.app/models/qwen/qwen3-30b-a3b-2507
	ModelIDQwenQwen330bA3b2507 gen.ModelId = "qwen/qwen3-30b-a3b-2507"
	// Model ID: qwen/qwen3-30b-a3b-instruct-2507
	// Model page: https://phaseo.app/models/qwen/qwen3-30b-a3b-instruct-2507
	ModelIDQwenQwen330bA3bInstruct2507 gen.ModelId = "qwen/qwen3-30b-a3b-instruct-2507"
	// Model ID: qwen/qwen3-30b-a3b-thinking-2507
	// Model page: https://phaseo.app/models/qwen/qwen3-30b-a3b-thinking-2507
	ModelIDQwenQwen330bA3bThinking2507 gen.ModelId = "qwen/qwen3-30b-a3b-thinking-2507"
	// Model ID: qwen/qwen3-32b
	// Model page: https://phaseo.app/models/qwen/qwen3-32b
	ModelIDQwenQwen332b gen.ModelId = "qwen/qwen3-32b"
	// Model ID: qwen/qwen3-4b
	// Model page: https://phaseo.app/models/qwen/qwen3-4b
	ModelIDQwenQwen34b gen.ModelId = "qwen/qwen3-4b"
	// Model ID: qwen/qwen3-8b
	// Model page: https://phaseo.app/models/qwen/qwen3-8b
	ModelIDQwenQwen38b gen.ModelId = "qwen/qwen3-8b"
	// Model ID: qwen/qwen3-coder
	// Model page: https://phaseo.app/models/qwen/qwen3-coder
	ModelIDQwenQwen3Coder gen.ModelId = "qwen/qwen3-coder"
	// Model ID: qwen/qwen3-coder-30b-a3b
	// Model page: https://phaseo.app/models/qwen/qwen3-coder-30b-a3b
	ModelIDQwenQwen3Coder30bA3b gen.ModelId = "qwen/qwen3-coder-30b-a3b"
	// Model ID: qwen/qwen3-coder-480b-a35b
	// Model page: https://phaseo.app/models/qwen/qwen3-coder-480b-a35b
	ModelIDQwenQwen3Coder480bA35b gen.ModelId = "qwen/qwen3-coder-480b-a35b"
	// Model ID: qwen/qwen3-coder-flash
	// Model page: https://phaseo.app/models/qwen/qwen3-coder-flash
	ModelIDQwenQwen3CoderFlash gen.ModelId = "qwen/qwen3-coder-flash"
	// Model ID: qwen/qwen3-coder-next
	// Model page: https://phaseo.app/models/qwen/qwen3-coder-next
	ModelIDQwenQwen3CoderNext gen.ModelId = "qwen/qwen3-coder-next"
	// Model ID: qwen/qwen3-coder-plus-2025-07-22
	// Model page: https://phaseo.app/models/qwen/qwen3-coder-plus-2025-07-22
	ModelIDQwenQwen3CoderPlus20250722 gen.ModelId = "qwen/qwen3-coder-plus-2025-07-22"
	// Model ID: qwen/qwen3-coder-plus-2025-09-23
	// Model page: https://phaseo.app/models/qwen/qwen3-coder-plus-2025-09-23
	ModelIDQwenQwen3CoderPlus20250923 gen.ModelId = "qwen/qwen3-coder-plus-2025-09-23"
	// Model ID: qwen/qwen3-embedding-8b
	// Model page: https://phaseo.app/models/qwen/qwen3-embedding-8b
	ModelIDQwenQwen3Embedding8b gen.ModelId = "qwen/qwen3-embedding-8b"
	// Model ID: qwen/qwen3-max
	// Model page: https://phaseo.app/models/qwen/qwen3-max
	ModelIDQwenQwen3Max gen.ModelId = "qwen/qwen3-max"
	// Model ID: qwen/qwen3-max-2025-09-23
	// Model page: https://phaseo.app/models/qwen/qwen3-max-2025-09-23
	ModelIDQwenQwen3Max20250923 gen.ModelId = "qwen/qwen3-max-2025-09-23"
	// Model ID: qwen/qwen3-max-2026-01-23
	// Model page: https://phaseo.app/models/qwen/qwen3-max-2026-01-23
	ModelIDQwenQwen3Max20260123 gen.ModelId = "qwen/qwen3-max-2026-01-23"
	// Model ID: qwen/qwen3-max-preview
	// Model page: https://phaseo.app/models/qwen/qwen3-max-preview
	ModelIDQwenQwen3MaxPreview gen.ModelId = "qwen/qwen3-max-preview"
	// Model ID: qwen/qwen3-max-thinking
	// Model page: https://phaseo.app/models/qwen/qwen3-max-thinking
	ModelIDQwenQwen3MaxThinking gen.ModelId = "qwen/qwen3-max-thinking"
	// Model ID: qwen/qwen3-next-80b
	// Model page: https://phaseo.app/models/qwen/qwen3-next-80b
	ModelIDQwenQwen3Next80b gen.ModelId = "qwen/qwen3-next-80b"
	// Model ID: qwen/qwen3-next-80b-a3b
	// Model page: https://phaseo.app/models/qwen/qwen3-next-80b-a3b
	ModelIDQwenQwen3Next80bA3b gen.ModelId = "qwen/qwen3-next-80b-a3b"
	// Model ID: qwen/qwen3-next-80b-a3b-instruct
	// Model page: https://phaseo.app/models/qwen/qwen3-next-80b-a3b-instruct
	ModelIDQwenQwen3Next80bA3bInstruct gen.ModelId = "qwen/qwen3-next-80b-a3b-instruct"
	// Model ID: qwen/qwen3-next-80b-a3b-thinking
	// Model page: https://phaseo.app/models/qwen/qwen3-next-80b-a3b-thinking
	ModelIDQwenQwen3Next80bA3bThinking gen.ModelId = "qwen/qwen3-next-80b-a3b-thinking"
	// Model ID: qwen/qwen3-omni-30b-a3b-thinking
	// Model page: https://phaseo.app/models/qwen/qwen3-omni-30b-a3b-thinking
	ModelIDQwenQwen3Omni30bA3bThinking gen.ModelId = "qwen/qwen3-omni-30b-a3b-thinking"
	// Model ID: qwen/qwen3-reranker
	// Model page: https://phaseo.app/models/qwen/qwen3-reranker
	ModelIDQwenQwen3Reranker gen.ModelId = "qwen/qwen3-reranker"
	// Model ID: qwen/qwen3-vl-235b-a22b
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-235b-a22b
	ModelIDQwenQwen3Vl235bA22b gen.ModelId = "qwen/qwen3-vl-235b-a22b"
	// Model ID: qwen/qwen3-vl-235b-a22b-instruct
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-235b-a22b-instruct
	ModelIDQwenQwen3Vl235bA22bInstruct gen.ModelId = "qwen/qwen3-vl-235b-a22b-instruct"
	// Model ID: qwen/qwen3-vl-235b-a22b-thinking
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-235b-a22b-thinking
	ModelIDQwenQwen3Vl235bA22bThinking gen.ModelId = "qwen/qwen3-vl-235b-a22b-thinking"
	// Model ID: qwen/qwen3-vl-30b-a3b
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-30b-a3b
	ModelIDQwenQwen3Vl30bA3b gen.ModelId = "qwen/qwen3-vl-30b-a3b"
	// Model ID: qwen/qwen3-vl-30b-a3b-instruct
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-30b-a3b-instruct
	ModelIDQwenQwen3Vl30bA3bInstruct gen.ModelId = "qwen/qwen3-vl-30b-a3b-instruct"
	// Model ID: qwen/qwen3-vl-30b-a3b-thinking
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-30b-a3b-thinking
	ModelIDQwenQwen3Vl30bA3bThinking gen.ModelId = "qwen/qwen3-vl-30b-a3b-thinking"
	// Model ID: qwen/qwen3-vl-32b-instruct
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-32b-instruct
	ModelIDQwenQwen3Vl32bInstruct gen.ModelId = "qwen/qwen3-vl-32b-instruct"
	// Model ID: qwen/qwen3-vl-32b-thinking
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-32b-thinking
	ModelIDQwenQwen3Vl32bThinking gen.ModelId = "qwen/qwen3-vl-32b-thinking"
	// Model ID: qwen/qwen3-vl-8b
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-8b
	ModelIDQwenQwen3Vl8b gen.ModelId = "qwen/qwen3-vl-8b"
	// Model ID: qwen/qwen3-vl-8b-instruct
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-8b-instruct
	ModelIDQwenQwen3Vl8bInstruct gen.ModelId = "qwen/qwen3-vl-8b-instruct"
	// Model ID: qwen/qwen3-vl-flash-2025-10-15
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-flash-2025-10-15
	ModelIDQwenQwen3VlFlash20251015 gen.ModelId = "qwen/qwen3-vl-flash-2025-10-15"
	// Model ID: qwen/qwen3-vl-flash-2026-01-22
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-flash-2026-01-22
	ModelIDQwenQwen3VlFlash20260122 gen.ModelId = "qwen/qwen3-vl-flash-2026-01-22"
	// Model ID: qwen/qwen3-vl-plus-2025-09-23
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-plus-2025-09-23
	ModelIDQwenQwen3VlPlus20250923 gen.ModelId = "qwen/qwen3-vl-plus-2025-09-23"
	// Model ID: qwen/qwen3-vl-plus-2025-12-19
	// Model page: https://phaseo.app/models/qwen/qwen3-vl-plus-2025-12-19
	ModelIDQwenQwen3VlPlus20251219 gen.ModelId = "qwen/qwen3-vl-plus-2025-12-19"
	// Model ID: qwen/qwen3.5-122b-a10b
	// Model page: https://phaseo.app/models/qwen/qwen3.5-122b-a10b
	ModelIDQwenQwen35122bA10b gen.ModelId = "qwen/qwen3.5-122b-a10b"
	// Model ID: qwen/qwen3.5-27b
	// Model page: https://phaseo.app/models/qwen/qwen3.5-27b
	ModelIDQwenQwen3527b gen.ModelId = "qwen/qwen3.5-27b"
	// Model ID: qwen/qwen3.5-35b-a3b
	// Model page: https://phaseo.app/models/qwen/qwen3.5-35b-a3b
	ModelIDQwenQwen3535bA3b gen.ModelId = "qwen/qwen3.5-35b-a3b"
	// Model ID: qwen/qwen3.5-397b-a17b
	// Model page: https://phaseo.app/models/qwen/qwen3.5-397b-a17b
	ModelIDQwenQwen35397bA17b gen.ModelId = "qwen/qwen3.5-397b-a17b"
	// Model ID: qwen/qwen3.5-4b
	// Model page: https://phaseo.app/models/qwen/qwen3.5-4b
	ModelIDQwenQwen354b gen.ModelId = "qwen/qwen3.5-4b"
	// Model ID: qwen/qwen3.5-9b
	// Model page: https://phaseo.app/models/qwen/qwen3.5-9b
	ModelIDQwenQwen359b gen.ModelId = "qwen/qwen3.5-9b"
	// Model ID: qwen/qwen3.5-flash
	// Model page: https://phaseo.app/models/qwen/qwen3.5-flash
	ModelIDQwenQwen35Flash gen.ModelId = "qwen/qwen3.5-flash"
	// Model ID: qwen/qwen3.5-livetranslate-flash-realtime-2026-05-19
	// Model page: https://phaseo.app/models/qwen/qwen3.5-livetranslate-flash-realtime-2026-05-19
	ModelIDQwenQwen35LivetranslateFlashRealtime20260519 gen.ModelId = "qwen/qwen3.5-livetranslate-flash-realtime-2026-05-19"
	// Model ID: qwen/qwen3.5-plus
	// Model page: https://phaseo.app/models/qwen/qwen3.5-plus
	ModelIDQwenQwen35Plus gen.ModelId = "qwen/qwen3.5-plus"
	// Model ID: qwen/qwen3.5-plus-2026-04-20
	// Model page: https://phaseo.app/models/qwen/qwen3.5-plus-2026-04-20
	ModelIDQwenQwen35Plus20260420 gen.ModelId = "qwen/qwen3.5-plus-2026-04-20"
	// Model ID: qwen/qwen3.6-27b
	// Model page: https://phaseo.app/models/qwen/qwen3.6-27b
	ModelIDQwenQwen3627b gen.ModelId = "qwen/qwen3.6-27b"
	// Model ID: qwen/qwen3.6-35b-a3b
	// Model page: https://phaseo.app/models/qwen/qwen3.6-35b-a3b
	ModelIDQwenQwen3635bA3b gen.ModelId = "qwen/qwen3.6-35b-a3b"
	// Model ID: qwen/qwen3.6-max-preview
	// Model page: https://phaseo.app/models/qwen/qwen3.6-max-preview
	ModelIDQwenQwen36MaxPreview gen.ModelId = "qwen/qwen3.6-max-preview"
	// Model ID: qwen/qwen3.6-plus
	// Model page: https://phaseo.app/models/qwen/qwen3.6-plus
	ModelIDQwenQwen36Plus_2 gen.ModelId = "qwen/qwen3.6-plus"
	// Model ID: qwen/qwen3.7-max
	// Model page: https://phaseo.app/models/qwen/qwen3.7-max
	ModelIDQwenQwen37Max gen.ModelId = "qwen/qwen3.7-max"
	// Model ID: qwen/qwen3.7-max-2026-05-17
	// Model page: https://phaseo.app/models/qwen/qwen3.7-max-2026-05-17
	ModelIDQwenQwen37Max20260517 gen.ModelId = "qwen/qwen3.7-max-2026-05-17"
	// Model ID: qwen/qwen3.7-plus
	// Model page: https://phaseo.app/models/qwen/qwen3.7-plus
	ModelIDQwenQwen37Plus gen.ModelId = "qwen/qwen3.7-plus"
	// Model ID: qwen/qwen3.7-plus-2026-05-26
	// Model page: https://phaseo.app/models/qwen/qwen3.7-plus-2026-05-26
	ModelIDQwenQwen37Plus20260526 gen.ModelId = "qwen/qwen3.7-plus-2026-05-26"
	// Model ID: qwen/qwq-32b
	// Model page: https://phaseo.app/models/qwen/qwq-32b
	ModelIDQwenQwq32b gen.ModelId = "qwen/qwq-32b"
	// Model ID: qwen/qwq-plus
	// Model page: https://phaseo.app/models/qwen/qwq-plus
	ModelIDQwenQwqPlus gen.ModelId = "qwen/qwq-plus"
	// Model ID: qwen/text-embedding-v3
	// Model page: https://phaseo.app/models/qwen/text-embedding-v3
	ModelIDQwenTextEmbeddingV3 gen.ModelId = "qwen/text-embedding-v3"
	// Model ID: qwen/text-embedding-v4
	// Model page: https://phaseo.app/models/qwen/text-embedding-v4
	ModelIDQwenTextEmbeddingV4 gen.ModelId = "qwen/text-embedding-v4"
	// Model ID: qwen/wan2.7-t2v
	// Model page: https://phaseo.app/models/qwen/wan2.7-t2v
	ModelIDQwenWan27T2v gen.ModelId = "qwen/wan2.7-t2v"
	// Model ID: spacex-ai/grok-4.20-beta-0309
	// Model page: https://phaseo.app/models/spacex-ai/grok-4.20-beta-0309
	ModelIDSpacexAiGrok420Beta0309 gen.ModelId = "spacex-ai/grok-4.20-beta-0309"
	// Model ID: spacex-ai/grok-4.20-multi-agent-beta-0309
	// Model page: https://phaseo.app/models/spacex-ai/grok-4.20-multi-agent-beta-0309
	ModelIDSpacexAiGrok420MultiAgentBeta0309 gen.ModelId = "spacex-ai/grok-4.20-multi-agent-beta-0309"
	// Model ID: spacex-ai/grok-4.3
	// Model page: https://phaseo.app/models/spacex-ai/grok-4.3
	ModelIDSpacexAiGrok43 gen.ModelId = "spacex-ai/grok-4.3"
	// Model ID: spacex-ai/grok-4.5
	// Model page: https://phaseo.app/models/spacex-ai/grok-4.5
	ModelIDSpacexAiGrok45 gen.ModelId = "spacex-ai/grok-4.5"
	// Model ID: spacex-ai/grok-build-0.1
	// Model page: https://phaseo.app/models/spacex-ai/grok-build-0.1
	ModelIDSpacexAiGrokBuild01 gen.ModelId = "spacex-ai/grok-build-0.1"
	// Model ID: spacex-ai/grok-code-fast-1
	// Model page: https://phaseo.app/models/spacex-ai/grok-code-fast-1
	ModelIDSpacexAiGrokCodeFast1 gen.ModelId = "spacex-ai/grok-code-fast-1"
	// Model ID: spacex-ai/grok-imagine-image
	// Model page: https://phaseo.app/models/spacex-ai/grok-imagine-image
	ModelIDSpacexAiGrokImagineImage gen.ModelId = "spacex-ai/grok-imagine-image"
	// Model ID: spacex-ai/grok-imagine-image-quality
	// Model page: https://phaseo.app/models/spacex-ai/grok-imagine-image-quality
	ModelIDSpacexAiGrokImagineImageQuality gen.ModelId = "spacex-ai/grok-imagine-image-quality"
	// Model ID: spacex-ai/grok-imagine-video
	// Model page: https://phaseo.app/models/spacex-ai/grok-imagine-video
	ModelIDSpacexAiGrokImagineVideo gen.ModelId = "spacex-ai/grok-imagine-video"
	// Model ID: spacex-ai/grok-tts
	// Model page: https://phaseo.app/models/spacex-ai/grok-tts
	ModelIDSpacexAiGrokTts gen.ModelId = "spacex-ai/grok-tts"
	// Model ID: stepfun/step-3.5-flash
	// Model page: https://phaseo.app/models/stepfun/step-3.5-flash
	ModelIDStepfunStep35Flash gen.ModelId = "stepfun/step-3.5-flash"
	// Model ID: stepfun/step-3.7-flash
	// Model page: https://phaseo.app/models/stepfun/step-3.7-flash
	ModelIDStepfunStep37Flash gen.ModelId = "stepfun/step-3.7-flash"
	// Model ID: tencent/hunyuan-a13b-instruct
	// Model page: https://phaseo.app/models/tencent/hunyuan-a13b-instruct
	ModelIDTencentHunyuanA13bInstruct gen.ModelId = "tencent/hunyuan-a13b-instruct"
	// Model ID: tencent/hy3
	// Model page: https://phaseo.app/models/tencent/hy3
	ModelIDTencentHy3 gen.ModelId = "tencent/hy3"
	// Model ID: tencent/hy3-preview
	// Model page: https://phaseo.app/models/tencent/hy3-preview
	ModelIDTencentHy3Preview gen.ModelId = "tencent/hy3-preview"
	// Model ID: tencent/hy3:free
	// Model page: https://phaseo.app/models/tencent/hy3%3Afree
	ModelIDTencentHy3Free gen.ModelId = "tencent/hy3:free"
	// Model ID: venice/venice-uncensored
	// Model page: https://phaseo.app/models/venice/venice-uncensored
	ModelIDVeniceVeniceUncensored gen.ModelId = "venice/venice-uncensored"
	// Model ID: venice/venice-uncensored-1.1
	// Model page: https://phaseo.app/models/venice/venice-uncensored-1.1
	ModelIDVeniceVeniceUncensored11 gen.ModelId = "venice/venice-uncensored-1.1"
	// Model ID: voyage/rerank-1
	// Model page: https://phaseo.app/models/voyage/rerank-1
	ModelIDVoyageRerank1 gen.ModelId = "voyage/rerank-1"
	// Model ID: voyage/rerank-2
	// Model page: https://phaseo.app/models/voyage/rerank-2
	ModelIDVoyageRerank2 gen.ModelId = "voyage/rerank-2"
	// Model ID: voyage/rerank-2-lite
	// Model page: https://phaseo.app/models/voyage/rerank-2-lite
	ModelIDVoyageRerank2Lite gen.ModelId = "voyage/rerank-2-lite"
	// Model ID: voyage/rerank-lite-1
	// Model page: https://phaseo.app/models/voyage/rerank-lite-1
	ModelIDVoyageRerankLite1 gen.ModelId = "voyage/rerank-lite-1"
	// Model ID: voyage/voyage-01
	// Model page: https://phaseo.app/models/voyage/voyage-01
	ModelIDVoyageVoyage01 gen.ModelId = "voyage/voyage-01"
	// Model ID: voyage/voyage-02
	// Model page: https://phaseo.app/models/voyage/voyage-02
	ModelIDVoyageVoyage02 gen.ModelId = "voyage/voyage-02"
	// Model ID: voyage/voyage-2
	// Model page: https://phaseo.app/models/voyage/voyage-2
	ModelIDVoyageVoyage2 gen.ModelId = "voyage/voyage-2"
	// Model ID: voyage/voyage-3
	// Model page: https://phaseo.app/models/voyage/voyage-3
	ModelIDVoyageVoyage3 gen.ModelId = "voyage/voyage-3"
	// Model ID: voyage/voyage-3-large
	// Model page: https://phaseo.app/models/voyage/voyage-3-large
	ModelIDVoyageVoyage3Large gen.ModelId = "voyage/voyage-3-large"
	// Model ID: voyage/voyage-3-lite
	// Model page: https://phaseo.app/models/voyage/voyage-3-lite
	ModelIDVoyageVoyage3Lite gen.ModelId = "voyage/voyage-3-lite"
	// Model ID: voyage/voyage-3.5
	// Model page: https://phaseo.app/models/voyage/voyage-3.5
	ModelIDVoyageVoyage35 gen.ModelId = "voyage/voyage-3.5"
	// Model ID: voyage/voyage-3.5-lite
	// Model page: https://phaseo.app/models/voyage/voyage-3.5-lite
	ModelIDVoyageVoyage35Lite gen.ModelId = "voyage/voyage-3.5-lite"
	// Model ID: voyage/voyage-4
	// Model page: https://phaseo.app/models/voyage/voyage-4
	ModelIDVoyageVoyage4 gen.ModelId = "voyage/voyage-4"
	// Model ID: voyage/voyage-4-large
	// Model page: https://phaseo.app/models/voyage/voyage-4-large
	ModelIDVoyageVoyage4Large gen.ModelId = "voyage/voyage-4-large"
	// Model ID: voyage/voyage-4-lite
	// Model page: https://phaseo.app/models/voyage/voyage-4-lite
	ModelIDVoyageVoyage4Lite gen.ModelId = "voyage/voyage-4-lite"
	// Model ID: voyage/voyage-code-2
	// Model page: https://phaseo.app/models/voyage/voyage-code-2
	ModelIDVoyageVoyageCode2 gen.ModelId = "voyage/voyage-code-2"
	// Model ID: voyage/voyage-code-3
	// Model page: https://phaseo.app/models/voyage/voyage-code-3
	ModelIDVoyageVoyageCode3 gen.ModelId = "voyage/voyage-code-3"
	// Model ID: voyage/voyage-context-3
	// Model page: https://phaseo.app/models/voyage/voyage-context-3
	ModelIDVoyageVoyageContext3 gen.ModelId = "voyage/voyage-context-3"
	// Model ID: voyage/voyage-finance-2
	// Model page: https://phaseo.app/models/voyage/voyage-finance-2
	ModelIDVoyageVoyageFinance2 gen.ModelId = "voyage/voyage-finance-2"
	// Model ID: voyage/voyage-large-2
	// Model page: https://phaseo.app/models/voyage/voyage-large-2
	ModelIDVoyageVoyageLarge2 gen.ModelId = "voyage/voyage-large-2"
	// Model ID: voyage/voyage-large-2-instruct
	// Model page: https://phaseo.app/models/voyage/voyage-large-2-instruct
	ModelIDVoyageVoyageLarge2Instruct gen.ModelId = "voyage/voyage-large-2-instruct"
	// Model ID: voyage/voyage-law-2
	// Model page: https://phaseo.app/models/voyage/voyage-law-2
	ModelIDVoyageVoyageLaw2 gen.ModelId = "voyage/voyage-law-2"
	// Model ID: voyage/voyage-lite-01
	// Model page: https://phaseo.app/models/voyage/voyage-lite-01
	ModelIDVoyageVoyageLite01 gen.ModelId = "voyage/voyage-lite-01"
	// Model ID: voyage/voyage-lite-01-instruct
	// Model page: https://phaseo.app/models/voyage/voyage-lite-01-instruct
	ModelIDVoyageVoyageLite01Instruct gen.ModelId = "voyage/voyage-lite-01-instruct"
	// Model ID: voyage/voyage-lite-02-instruct
	// Model page: https://phaseo.app/models/voyage/voyage-lite-02-instruct
	ModelIDVoyageVoyageLite02Instruct gen.ModelId = "voyage/voyage-lite-02-instruct"
	// Model ID: voyage/voyage-multilingual-2
	// Model page: https://phaseo.app/models/voyage/voyage-multilingual-2
	ModelIDVoyageVoyageMultilingual2 gen.ModelId = "voyage/voyage-multilingual-2"
	// Model ID: voyage/voyage-multimodal-3
	// Model page: https://phaseo.app/models/voyage/voyage-multimodal-3
	ModelIDVoyageVoyageMultimodal3 gen.ModelId = "voyage/voyage-multimodal-3"
	// Model ID: voyage/voyage-multimodal-3.5
	// Model page: https://phaseo.app/models/voyage/voyage-multimodal-3.5
	ModelIDVoyageVoyageMultimodal35 gen.ModelId = "voyage/voyage-multimodal-3.5"
	// Model ID: xiaomi/mimo-v2-flash
	// Model page: https://phaseo.app/models/xiaomi/mimo-v2-flash
	ModelIDXiaomiMimoV2Flash gen.ModelId = "xiaomi/mimo-v2-flash"
	// Model ID: xiaomi/mimo-v2.5
	// Model page: https://phaseo.app/models/xiaomi/mimo-v2.5
	ModelIDXiaomiMimoV25 gen.ModelId = "xiaomi/mimo-v2.5"
	// Model ID: xiaomi/mimo-v2.5-pro
	// Model page: https://phaseo.app/models/xiaomi/mimo-v2.5-pro
	ModelIDXiaomiMimoV25Pro gen.ModelId = "xiaomi/mimo-v2.5-pro"
	// Model ID: xiaomi/mimo-v2.5-tts:free
	// Model page: https://phaseo.app/models/xiaomi/mimo-v2.5-tts%3Afree
	ModelIDXiaomiMimoV25TtsFree gen.ModelId = "xiaomi/mimo-v2.5-tts:free"
	// Model ID: z-ai/glm-4-32b
	// Model page: https://phaseo.app/models/z-ai/glm-4-32b
	ModelIDZAiGlm432b gen.ModelId = "z-ai/glm-4-32b"
	// Model ID: z-ai/glm-4-7-flash:free
	// Model page: https://phaseo.app/models/z-ai/glm-4-7-flash%3Afree
	ModelIDZAiGlm47FlashFree gen.ModelId = "z-ai/glm-4-7-flash:free"
	// Model ID: z-ai/glm-4.5
	// Model page: https://phaseo.app/models/z-ai/glm-4.5
	ModelIDZAiGlm45 gen.ModelId = "z-ai/glm-4.5"
	// Model ID: z-ai/glm-4.5-air
	// Model page: https://phaseo.app/models/z-ai/glm-4.5-air
	ModelIDZAiGlm45Air gen.ModelId = "z-ai/glm-4.5-air"
	// Model ID: z-ai/glm-4.5-air-x
	// Model page: https://phaseo.app/models/z-ai/glm-4.5-air-x
	ModelIDZAiGlm45AirX gen.ModelId = "z-ai/glm-4.5-air-x"
	// Model ID: z-ai/glm-4.5-x
	// Model page: https://phaseo.app/models/z-ai/glm-4.5-x
	ModelIDZAiGlm45X gen.ModelId = "z-ai/glm-4.5-x"
	// Model ID: z-ai/glm-4.5v
	// Model page: https://phaseo.app/models/z-ai/glm-4.5v
	ModelIDZAiGlm45v gen.ModelId = "z-ai/glm-4.5v"
	// Model ID: z-ai/glm-4.6
	// Model page: https://phaseo.app/models/z-ai/glm-4.6
	ModelIDZAiGlm46 gen.ModelId = "z-ai/glm-4.6"
	// Model ID: z-ai/glm-4.6v
	// Model page: https://phaseo.app/models/z-ai/glm-4.6v
	ModelIDZAiGlm46v gen.ModelId = "z-ai/glm-4.6v"
	// Model ID: z-ai/glm-4.6v-flash
	// Model page: https://phaseo.app/models/z-ai/glm-4.6v-flash
	ModelIDZAiGlm46vFlash gen.ModelId = "z-ai/glm-4.6v-flash"
	// Model ID: z-ai/glm-4.7
	// Model page: https://phaseo.app/models/z-ai/glm-4.7
	ModelIDZAiGlm47 gen.ModelId = "z-ai/glm-4.7"
	// Model ID: z-ai/glm-4.7-flash
	// Model page: https://phaseo.app/models/z-ai/glm-4.7-flash
	ModelIDZAiGlm47Flash gen.ModelId = "z-ai/glm-4.7-flash"
	// Model ID: z-ai/glm-5
	// Model page: https://phaseo.app/models/z-ai/glm-5
	ModelIDZAiGlm5 gen.ModelId = "z-ai/glm-5"
	// Model ID: z-ai/glm-5-code
	// Model page: https://phaseo.app/models/z-ai/glm-5-code
	ModelIDZAiGlm5Code gen.ModelId = "z-ai/glm-5-code"
	// Model ID: z-ai/glm-5-turbo
	// Model page: https://phaseo.app/models/z-ai/glm-5-turbo
	ModelIDZAiGlm5Turbo gen.ModelId = "z-ai/glm-5-turbo"
	// Model ID: z-ai/glm-5.1
	// Model page: https://phaseo.app/models/z-ai/glm-5.1
	ModelIDZAiGlm51 gen.ModelId = "z-ai/glm-5.1"
	// Model ID: z-ai/glm-5.2
	// Model page: https://phaseo.app/models/z-ai/glm-5.2
	ModelIDZAiGlm52 gen.ModelId = "z-ai/glm-5.2"
	// Model ID: z-ai/glm-5v-turbo
	// Model page: https://phaseo.app/models/z-ai/glm-5v-turbo
	ModelIDZAiGlm5vTurbo gen.ModelId = "z-ai/glm-5v-turbo"
	// Model ID: zai-org/glm-4.5-air
	// Model page: https://phaseo.app/models/zai-org/glm-4.5-air
	ModelIDZaiOrgGlm45Air gen.ModelId = "zai-org/glm-4.5-air"
	// Model ID: zai/glm-5
	// Model page: https://phaseo.app/models/zai/glm-5
	ModelIDZaiGlm5 gen.ModelId = "zai/glm-5"
	// Deprecated alias for deepseek/deepseek-v4; use deepseek/deepseek-v4-pro. Remove in the next major SDK release.
	ModelIDDeepseekDeepseekV4 gen.ModelId = ModelIDDeepseekDeepseekV4Pro
)

var KnownModelIDs = []gen.ModelId{
	ModelIDAi21JambaLarge17,
	ModelIDAi21JambaMini2,
	ModelIDAionLabsAion20,
	ModelIDAionLabsAion25,
	ModelIDAionLabsAion30,
	ModelIDAionLabsAion30Mini,
	ModelIDAionLabsAionRpLlama318b,
	ModelIDAllenaiMolmo28b,
	ModelIDAllenaiOlmo3132b,
	ModelIDAnthropicClaudeFable5,
	ModelIDAnthropicClaudeHaiku45,
	ModelIDAnthropicClaudeOpus41,
	ModelIDAnthropicClaudeOpus45,
	ModelIDAnthropicClaudeOpus46,
	ModelIDAnthropicClaudeOpus47,
	ModelIDAnthropicClaudeOpus47Fast,
	ModelIDAnthropicClaudeOpus48,
	ModelIDAnthropicClaudeSonnet45,
	ModelIDAnthropicClaudeSonnet46,
	ModelIDAnthropicClaudeSonnet5,
	ModelIDArceeAiTrinityLarge,
	ModelIDArceeAiTrinityLargeThinking,
	ModelIDArceeAiTrinityMini,
	ModelIDBaiduErnie4521bA3b,
	ModelIDBaiduErnie4521bA3bThinking,
	ModelIDBaiduErnie45300bA47b,
	ModelIDBaiduErnie45Vl28bA3b,
	ModelIDBaiduErnie45Vl28bA3bThinking,
	ModelIDBaiduErnie45Vl424bA47b,
	ModelIDBlackForestLabsFlux1Schnell,
	ModelIDBytedanceSeed16,
	ModelIDBytedanceSeed16250915,
	ModelIDBytedanceSeed16Flash,
	ModelIDBytedanceSeed16Flash250715,
	ModelIDBytedanceSeed18,
	ModelIDBytedanceSeed20Lite,
	ModelIDBytedanceSeed20Lite260428,
	ModelIDBytedanceSeed20Mini,
	ModelIDBytedanceSeed20Mini260428,
	ModelIDBytedanceSeed20Pro,
	ModelIDBytedanceSeedOss36bInstruct,
	ModelIDBytedanceSeedTranslation,
	ModelIDBytedanceSeedance20,
	ModelIDBytedanceSeedance20Fast,
	ModelIDBytedanceSeedance20Mini260615,
	ModelIDCrofaiGreg1Mini,
	ModelIDCrofaiGreg2Super,
	ModelIDCrofaiGreg2Ultra,
	ModelIDCrofaiGregRp,
	ModelIDDeepseekDeepseekOcr,
	ModelIDDeepseekDeepseekOcr2,
	ModelIDDeepseekDeepseekProverV2671b,
	ModelIDDeepseekDeepseekR1,
	ModelIDDeepseekDeepseekR10528,
	ModelIDDeepseekDeepseekR120250528,
	ModelIDDeepseekDeepseekR1Turbo,
	ModelIDDeepseekDeepseekV3,
	ModelIDDeepseekDeepseekV30324,
	ModelIDDeepseekDeepseekV3Turbo,
	ModelIDDeepseekDeepseekV31,
	ModelIDDeepseekDeepseekV31Terminus,
	ModelIDDeepseekDeepseekV32,
	ModelIDDeepseekDeepseekV32Exp,
	ModelIDDeepseekDeepseekV32Speciale,
	ModelIDDeepseekDeepseekV32Thinking,
	ModelIDDeepseekDeepseekV4Flash,
	ModelIDDeepseekDeepseekV4Pro,
	ModelIDDeepseekDeepseekV4ProLightning,
	ModelIDElevenLabsElevenFlashV2,
	ModelIDElevenLabsElevenFlashV25,
	ModelIDElevenLabsElevenMultilingualV2,
	ModelIDElevenLabsElevenTurboV2,
	ModelIDElevenLabsElevenTurboV25,
	ModelIDElevenLabsElevenV3,
	ModelIDEssentialAiRnj1,
	ModelIDGoogleGemini25Flash,
	ModelIDGoogleGemini25FlashLite,
	ModelIDGoogleGemini25FlashLitePreview20250617,
	ModelIDGoogleGemini25FlashLitePreview20250925,
	ModelIDGoogleGemini25Pro,
	ModelIDGoogleGemini3FlashPreview,
	ModelIDGoogleGemini3ProImage,
	ModelIDGoogleGemini31FlashImage,
	ModelIDGoogleGemini31FlashImagePreview,
	ModelIDGoogleGemini31FlashLite,
	ModelIDGoogleGemini31FlashLiteImage,
	ModelIDGoogleGemini31FlashLitePreview,
	ModelIDGoogleGemini31FlashTtsPreview,
	ModelIDGoogleGemini31ProPreview,
	ModelIDGoogleGemini31ProPreviewCustomtools,
	ModelIDGoogleGemini35Flash,
	ModelIDGoogleGemini35Pro,
	ModelIDGoogleGeminiEmbedding001,
	ModelIDGoogleGeminiEmbedding2,
	ModelIDGoogleGeminiEmbedding2Preview,
	ModelIDGoogleGeminiRoboticsEr16Preview,
	ModelIDGoogleGemma327b,
	ModelIDGoogleGemma3nE4b,
	ModelIDGoogleGemma426bA4b,
	ModelIDGoogleGemma426bA4bFree,
	ModelIDGoogleGemma431b,
	ModelIDGoogleGemma431bIt,
	ModelIDGoogleGemma431bFree,
	ModelIDGoogleLyria3ClipPreview,
	ModelIDGoogleLyria3ProPreview,
	ModelIDGoogleVeo2,
	ModelIDGoogleVeo31FastPreview,
	ModelIDGoogleVeo31LiteGeneratePreview,
	ModelIDGoogleVeo31Preview,
	ModelIDIbmGranite418b,
	ModelIDInceptionMercury2,
	ModelIDInceptionMercuryEdit2,
	ModelIDInclusionaiLing261t,
	ModelIDInclusionaiLingFlash20,
	ModelIDInclusionaiRingFlash20,
	ModelIDInflectionInflection3Pi,
	ModelIDInflectionInflection3Productivity,
	ModelIDKwaipilotKatCoderAirV25,
	ModelIDKwaipilotKatCoderExp72b1010,
	ModelIDKwaipilotKatCoderPro,
	ModelIDKwaipilotKatCoderProV1,
	ModelIDKwaipilotKatCoderProV2,
	ModelIDKwaipilotKatCoderProV25,
	ModelIDLiquidAiLfm224bA2b,
	ModelIDMeituanLongcat20,
	ModelIDMetaLlama370b,
	ModelIDMetaLlama38b,
	ModelIDMetaLlama38bLite,
	ModelIDMetaLlama3170b,
	ModelIDMetaLlama318b,
	ModelIDMetaLlama3211bVision,
	ModelIDMetaLlama323b,
	ModelIDMetaLlama3370b,
	ModelIDMetaLlama4Maverick,
	ModelIDMetaLlama4Scout,
	ModelIDMetaLlamaGuard412b,
	ModelIDMetaLlamaPromptGuard222m,
	ModelIDMetaLlamaPromptGuard286m,
	ModelIDMicrosoftPhi4,
	ModelIDMicrosoftPhi4Mini,
	ModelIDMinimaxHailuo02,
	ModelIDMinimaxHailuo23,
	ModelIDMinimaxHailuo23Fast,
	ModelIDMinimaxM2Her,
	ModelIDMinimaxMinimaxM180k,
	ModelIDMinimaxMinimaxM2,
	ModelIDMinimaxMinimaxM21,
	ModelIDMinimaxMinimaxM25,
	ModelIDMinimaxMinimaxM25Highspeed,
	ModelIDMinimaxMinimaxM27,
	ModelIDMinimaxMinimaxM3,
	ModelIDMinimaxMusic26,
	ModelIDMinimaxMusic26Free,
	ModelIDMistralCodestralEmbed,
	ModelIDMistralDevstral2,
	ModelIDMistralDevstralMedium10,
	ModelIDMistralDevstralSmall11,
	ModelIDMistralLeanstral15Free,
	ModelIDMistralMagistralMedium12,
	ModelIDMistralMinistral314b,
	ModelIDMistralMinistral33b,
	ModelIDMistralMinistral38b,
	ModelIDMistralMistralEmbed,
	ModelIDMistralMistralLarge21,
	ModelIDMistralMistralLarge3,
	ModelIDMistralMistralMedium30,
	ModelIDMistralMistralMedium31,
	ModelIDMistralMistralMedium35,
	ModelIDMistralMistralModeration,
	ModelIDMistralMistralModeration2,
	ModelIDMistralMistralNemo12b,
	ModelIDMistralMistralNemo2407,
	ModelIDMistralMistralSmall24b2501,
	ModelIDMistralMistralSmall32,
	ModelIDMistralMistralSmall4,
	ModelIDMistralMixtral8x7b,
	ModelIDMistralPixtralLarge,
	ModelIDMistralaiMistralNemo,
	ModelIDMoonshotaiKimiK2,
	ModelIDMoonshotaiKimiK20905,
	ModelIDMoonshotaiKimiK2Instruct,
	ModelIDMoonshotaiKimiK2Instruct0905,
	ModelIDMoonshotaiKimiK2Thinking,
	ModelIDMoonshotaiKimiK25,
	ModelIDMoonshotaiKimiK25Lightning,
	ModelIDMoonshotaiKimiK26,
	ModelIDMoonshotaiKimiK27Code,
	ModelIDMoonshotaiMoonshotV1128k,
	ModelIDMoonshotaiMoonshotV1128kVisionPreview,
	ModelIDMoonshotaiMoonshotV132k,
	ModelIDMoonshotaiMoonshotV132kVisionPreview,
	ModelIDMoonshotaiMoonshotV18k,
	ModelIDMoonshotaiMoonshotV18kVisionPreview,
	ModelIDMorphMorphV3Fast,
	ModelIDMorphMorphV3Large,
	ModelIDNexAgiDeepseekV31NexN1,
	ModelIDNexAgiNexN2Pro,
	ModelIDNousHermes3Llama31405b,
	ModelIDNousresearchHermes3Llama31405b,
	ModelIDNousresearchHermes3Llama3170b,
	ModelIDNousresearchHermes4405b,
	ModelIDNousresearchHermes470b,
	ModelIDNvidiaCosmos3SuperReasoner,
	ModelIDNvidiaLlama31Nemotron70bInstruct,
	ModelIDNvidiaLlama31NemotronUltra253b,
	ModelIDNvidiaLlama33NemotronSuper49bV15,
	ModelIDNvidiaNemotron3Nano30bA3b,
	ModelIDNvidiaNemotron3NanoOmni30bA3bReasoning,
	ModelIDNvidiaNemotron3Super120bA12b,
	ModelIDNvidiaNemotron3Ultra550bA55b,
	ModelIDNvidiaNvidiaNemotron3Nano30bA3b,
	ModelIDNvidiaNvidiaNemotronNano12bV2Vl,
	ModelIDOpenaiBabbage002,
	ModelIDOpenaiChatLatest,
	ModelIDOpenaiChatgpt4o,
	ModelIDOpenaiComputerUsePreview,
	ModelIDOpenaiDavinci002,
	ModelIDOpenaiGpt35Turbo16k,
	ModelIDOpenaiGpt35Turbo20230321,
	ModelIDOpenaiGpt420230613,
	ModelIDOpenaiGpt4Turbo20230314,
	ModelIDOpenaiGpt4Turbo20231106,
	ModelIDOpenaiGpt4Turbo20240125,
	ModelIDOpenaiGpt41,
	ModelIDOpenaiGpt41Mini,
	ModelIDOpenaiGpt41Nano,
	ModelIDOpenaiGpt4o20240513,
	ModelIDOpenaiGpt4o20240806,
	ModelIDOpenaiGpt4o20241120,
	ModelIDOpenaiGpt4oMini,
	ModelIDOpenaiGpt4oMiniTranscribe,
	ModelIDOpenaiGpt4oMiniTts,
	ModelIDOpenaiGpt4oTranscribe,
	ModelIDOpenaiGpt5,
	ModelIDOpenaiGpt5Chat,
	ModelIDOpenaiGpt5Codex,
	ModelIDOpenaiGpt5Mini,
	ModelIDOpenaiGpt5Nano,
	ModelIDOpenaiGpt5Pro,
	ModelIDOpenaiGpt51,
	ModelIDOpenaiGpt51Chat,
	ModelIDOpenaiGpt51Codex,
	ModelIDOpenaiGpt51CodexMax,
	ModelIDOpenaiGpt51CodexMini,
	ModelIDOpenaiGpt52,
	ModelIDOpenaiGpt52Chat,
	ModelIDOpenaiGpt52Codex,
	ModelIDOpenaiGpt52Pro,
	ModelIDOpenaiGpt53Chat,
	ModelIDOpenaiGpt53Codex,
	ModelIDOpenaiGpt54,
	ModelIDOpenaiGpt54Mini,
	ModelIDOpenaiGpt54Nano,
	ModelIDOpenaiGpt54Pro,
	ModelIDOpenaiGpt55,
	ModelIDOpenaiGpt55Pro,
	ModelIDOpenaiGptImage1,
	ModelIDOpenaiGptImage1Mini,
	ModelIDOpenaiGptImage15,
	ModelIDOpenaiGptImage2,
	ModelIDOpenaiGptOss120b,
	ModelIDOpenaiGptOss20b,
	ModelIDOpenaiGptOssSafeguard20b,
	ModelIDOpenaiO1,
	ModelIDOpenaiO1Mini,
	ModelIDOpenaiO1Pro,
	ModelIDOpenaiO3,
	ModelIDOpenaiO3DeepResearch,
	ModelIDOpenaiO3Mini,
	ModelIDOpenaiO3Pro,
	ModelIDOpenaiO4Mini,
	ModelIDOpenaiO4MiniDeepResearch,
	ModelIDOpenaiOmniModeration,
	ModelIDOpenaiSora2,
	ModelIDOpenaiSora2Pro,
	ModelIDOpenaiTextEmbedding3Large,
	ModelIDOpenaiTextEmbedding3Small,
	ModelIDOpenaiTextEmbeddingAda002,
	ModelIDOpenaiWhisper1,
	ModelIDPhaseoFree,
	ModelIDPoolsideLagunaM1Free,
	ModelIDPoolsideLagunaXs21Free,
	ModelIDQwenQvqMax,
	ModelIDQwenQwen36Plus,
	ModelIDQwenQwenFlash,
	ModelIDQwenQwenFlashCharacter,
	ModelIDQwenQwenMax,
	ModelIDQwenQwenMtFlash,
	ModelIDQwenQwenMtLite,
	ModelIDQwenQwenMtPlus,
	ModelIDQwenQwenMtTurbo,
	ModelIDQwenQwenPlus20250125,
	ModelIDQwenQwenPlus20250428,
	ModelIDQwenQwenPlus20250714,
	ModelIDQwenQwenPlus20250728,
	ModelIDQwenQwenPlus20250911,
	ModelIDQwenQwenPlus20251201,
	ModelIDQwenQwenPlusCharacter,
	ModelIDQwenQwenTurbo20241101,
	ModelIDQwenQwenTurbo20250428,
	ModelIDQwenQwenVlMax20250408,
	ModelIDQwenQwenVlMax20250813,
	ModelIDQwenQwenVlPlus20250125,
	ModelIDQwenQwenVlPlus20250507,
	ModelIDQwenQwenVlPlus20250815,
	ModelIDQwenQwen2514b,
	ModelIDQwenQwen2514b1m,
	ModelIDQwenQwen2532b,
	ModelIDQwenQwen2572b,
	ModelIDQwenQwen257b,
	ModelIDQwenQwen257b1m,
	ModelIDQwenQwen25Coder7b,
	ModelIDQwenQwen25Vl32b,
	ModelIDQwenQwen25Vl32bInstruct,
	ModelIDQwenQwen25Vl72b,
	ModelIDQwenQwen25Vl72bInstruct,
	ModelIDQwenQwen25Vl7b,
	ModelIDQwenQwen306b,
	ModelIDQwenQwen317b,
	ModelIDQwenQwen314b,
	ModelIDQwenQwen3235bA22b2507,
	ModelIDQwenQwen3235bA22bInstruct2507,
	ModelIDQwenQwen3235bA22bThinking2507,
	ModelIDQwenQwen330bA3b,
	ModelIDQwenQwen330bA3b2507,
	ModelIDQwenQwen330bA3bInstruct2507,
	ModelIDQwenQwen330bA3bThinking2507,
	ModelIDQwenQwen332b,
	ModelIDQwenQwen34b,
	ModelIDQwenQwen38b,
	ModelIDQwenQwen3Coder,
	ModelIDQwenQwen3Coder30bA3b,
	ModelIDQwenQwen3Coder480bA35b,
	ModelIDQwenQwen3CoderFlash,
	ModelIDQwenQwen3CoderNext,
	ModelIDQwenQwen3CoderPlus20250722,
	ModelIDQwenQwen3CoderPlus20250923,
	ModelIDQwenQwen3Embedding8b,
	ModelIDQwenQwen3Max,
	ModelIDQwenQwen3Max20250923,
	ModelIDQwenQwen3Max20260123,
	ModelIDQwenQwen3MaxPreview,
	ModelIDQwenQwen3MaxThinking,
	ModelIDQwenQwen3Next80b,
	ModelIDQwenQwen3Next80bA3b,
	ModelIDQwenQwen3Next80bA3bInstruct,
	ModelIDQwenQwen3Next80bA3bThinking,
	ModelIDQwenQwen3Omni30bA3bThinking,
	ModelIDQwenQwen3Reranker,
	ModelIDQwenQwen3Vl235bA22b,
	ModelIDQwenQwen3Vl235bA22bInstruct,
	ModelIDQwenQwen3Vl235bA22bThinking,
	ModelIDQwenQwen3Vl30bA3b,
	ModelIDQwenQwen3Vl30bA3bInstruct,
	ModelIDQwenQwen3Vl30bA3bThinking,
	ModelIDQwenQwen3Vl32bInstruct,
	ModelIDQwenQwen3Vl32bThinking,
	ModelIDQwenQwen3Vl8b,
	ModelIDQwenQwen3Vl8bInstruct,
	ModelIDQwenQwen3VlFlash20251015,
	ModelIDQwenQwen3VlFlash20260122,
	ModelIDQwenQwen3VlPlus20250923,
	ModelIDQwenQwen3VlPlus20251219,
	ModelIDQwenQwen35122bA10b,
	ModelIDQwenQwen3527b,
	ModelIDQwenQwen3535bA3b,
	ModelIDQwenQwen35397bA17b,
	ModelIDQwenQwen354b,
	ModelIDQwenQwen359b,
	ModelIDQwenQwen35Flash,
	ModelIDQwenQwen35LivetranslateFlashRealtime20260519,
	ModelIDQwenQwen35Plus,
	ModelIDQwenQwen35Plus20260420,
	ModelIDQwenQwen3627b,
	ModelIDQwenQwen3635bA3b,
	ModelIDQwenQwen36MaxPreview,
	ModelIDQwenQwen36Plus_2,
	ModelIDQwenQwen37Max,
	ModelIDQwenQwen37Max20260517,
	ModelIDQwenQwen37Plus,
	ModelIDQwenQwen37Plus20260526,
	ModelIDQwenQwq32b,
	ModelIDQwenQwqPlus,
	ModelIDQwenTextEmbeddingV3,
	ModelIDQwenTextEmbeddingV4,
	ModelIDQwenWan27T2v,
	ModelIDSpacexAiGrok420Beta0309,
	ModelIDSpacexAiGrok420MultiAgentBeta0309,
	ModelIDSpacexAiGrok43,
	ModelIDSpacexAiGrok45,
	ModelIDSpacexAiGrokBuild01,
	ModelIDSpacexAiGrokCodeFast1,
	ModelIDSpacexAiGrokImagineImage,
	ModelIDSpacexAiGrokImagineImageQuality,
	ModelIDSpacexAiGrokImagineVideo,
	ModelIDSpacexAiGrokTts,
	ModelIDStepfunStep35Flash,
	ModelIDStepfunStep37Flash,
	ModelIDTencentHunyuanA13bInstruct,
	ModelIDTencentHy3,
	ModelIDTencentHy3Preview,
	ModelIDTencentHy3Free,
	ModelIDVeniceVeniceUncensored,
	ModelIDVeniceVeniceUncensored11,
	ModelIDVoyageRerank1,
	ModelIDVoyageRerank2,
	ModelIDVoyageRerank2Lite,
	ModelIDVoyageRerankLite1,
	ModelIDVoyageVoyage01,
	ModelIDVoyageVoyage02,
	ModelIDVoyageVoyage2,
	ModelIDVoyageVoyage3,
	ModelIDVoyageVoyage3Large,
	ModelIDVoyageVoyage3Lite,
	ModelIDVoyageVoyage35,
	ModelIDVoyageVoyage35Lite,
	ModelIDVoyageVoyage4,
	ModelIDVoyageVoyage4Large,
	ModelIDVoyageVoyage4Lite,
	ModelIDVoyageVoyageCode2,
	ModelIDVoyageVoyageCode3,
	ModelIDVoyageVoyageContext3,
	ModelIDVoyageVoyageFinance2,
	ModelIDVoyageVoyageLarge2,
	ModelIDVoyageVoyageLarge2Instruct,
	ModelIDVoyageVoyageLaw2,
	ModelIDVoyageVoyageLite01,
	ModelIDVoyageVoyageLite01Instruct,
	ModelIDVoyageVoyageLite02Instruct,
	ModelIDVoyageVoyageMultilingual2,
	ModelIDVoyageVoyageMultimodal3,
	ModelIDVoyageVoyageMultimodal35,
	ModelIDXiaomiMimoV2Flash,
	ModelIDXiaomiMimoV25,
	ModelIDXiaomiMimoV25Pro,
	ModelIDXiaomiMimoV25TtsFree,
	ModelIDZAiGlm432b,
	ModelIDZAiGlm47FlashFree,
	ModelIDZAiGlm45,
	ModelIDZAiGlm45Air,
	ModelIDZAiGlm45AirX,
	ModelIDZAiGlm45X,
	ModelIDZAiGlm45v,
	ModelIDZAiGlm46,
	ModelIDZAiGlm46v,
	ModelIDZAiGlm46vFlash,
	ModelIDZAiGlm47,
	ModelIDZAiGlm47Flash,
	ModelIDZAiGlm5,
	ModelIDZAiGlm5Code,
	ModelIDZAiGlm5Turbo,
	ModelIDZAiGlm51,
	ModelIDZAiGlm52,
	ModelIDZAiGlm5vTurbo,
	ModelIDZaiOrgGlm45Air,
	ModelIDZaiGlm5,
}
