/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: e969b1f361c015dd3e0ff808c15b37ff)
interface __BaseEnv_Env {
	PHASEO_API_BASE_URL: string;
	PHASEO_WEB_BASE_URL: string;
	PHASEO_MCP_RESOURCE_SERVER_SECRET: string;
	INFERENCE_RUNS: DurableObjectNamespace<import("./src/index").InferenceRunReceipt>;
	PHASEO_API?: Fetcher /* phaseo-gateway */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "InferenceRunReceipt";
	}
	interface ProductionEnv {
		PHASEO_API_BASE_URL: string;
		PHASEO_WEB_BASE_URL: string;
		PHASEO_MCP_RESOURCE_SERVER_SECRET: string;
		INFERENCE_RUNS: DurableObjectNamespace<import("./src/index").InferenceRunReceipt>;
		PHASEO_API: Fetcher /* phaseo-gateway */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PHASEO_API_BASE_URL" | "PHASEO_WEB_BASE_URL" | "PHASEO_MCP_RESOURCE_SERVER_SECRET">> {}
}
