/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 6810f35ea8ac0eea3824096317645c79)
interface __BaseEnv_Env {
	PHASEO_API_BASE_URL: string;
	PHASEO_MCP_WRITE_TOOLS_ENABLED: string;
	PHASEO_API?: Fetcher /* phaseo-gateway */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface ProductionEnv {
		PHASEO_API_BASE_URL: string;
		PHASEO_MCP_WRITE_TOOLS_ENABLED: string;
		PHASEO_API: Fetcher /* phaseo-gateway */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PHASEO_API_BASE_URL" | "PHASEO_MCP_WRITE_TOOLS_ENABLED">> {}
}
