// Isolated PostgreSQL regression tests. Never connects to Supabase or modifies live data.
// Build only the catalogue fixture tables from their original DDL, then execute the
// real history migration and test complete RPC writes under PostgreSQL constraints.
import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create table public.users(user_id uuid primary key,role text);`);
const migrations=new URL('../../supabase/migrations/',import.meta.url);
const readMigration=(name)=>readFileSync(new URL(name,migrations),'utf8');
const files=['20260722100000_v2_catalogue_routing.sql','20260722101000_v2_pricing_skus.sql','20260722120000_v2_regions_tiers_capabilities.sql','20260722137000_v2_benchmarks.sql','20260722138000_v2_subscriptions.sql','20260726200000_v2_meter_definitions_and_catalogue_extensions.sql','20260810114253_database_authoritative_catalogue_pricing.sql'];
for(const f of files){const sql=readMigration(f);for(const match of sql.matchAll(/create table if not exists public\.[\s\S]*?\n\);/g)){await db.exec(match[0]);}}
await db.exec(`alter table v2_pricing_skus add column service_tier_slug text default 'standard'; alter table v2_model_provider_routes add column provider_availability_status text default 'unknown',add column phaseo_status text default 'disabled',add column access_scope text default 'public'; alter table v2_catalogue_admin_changes drop constraint v2_catalogue_admin_changes_resource_type_check; alter table v2_catalogue_admin_changes drop constraint v2_catalogue_admin_changes_action_check; alter table v2_catalogue_source_overrides drop constraint v2_catalogue_source_overrides_type_check;`);
await db.exec(`create policy v2_benchmark_results_public_select on v2_benchmark_results for select using(true);create policy v2_subscription_plan_models_public_select on v2_subscription_plan_models for select using(true);`);
await db.exec(readMigration('20260907223723_preserve_catalogue_history.sql'));
console.log('Migration loaded');
await db.exec(`insert into auth.users values('00000000-0000-4000-8000-000000000001');insert into public.users values('00000000-0000-4000-8000-000000000001','admin');insert into v2_labs(lab_slug,name) values('test','Test');insert into v2_models(model_slug,lab_slug,name) values('test/model','test','Test'),('test/other','test','Other');insert into v2_providers(provider_slug,name) values('test','Test');insert into v2_model_provider_routes(provider_model_id,model_slug,provider_slug,provider_model_slug) values('test:route','test/model','test','upstream');`);
const actor='00000000-0000-4000-8000-000000000001';
const draft={provider_model_id:'test:route',sku_code:'standard',display_name:'Standard',effective_from:'2026-01-01T00:00:00Z',meters:[{meter_key:'input_tokens',modality:'text',unit:'token',unit_quantity:1000000,price_nanos:2000000000,display_label:'Input',display_unit:'1M tokens'}]};
const call=async(action,payload,model='test/model')=>(await db.query('select mutate_v2_admin_pricing_sku($1,$2,$3,$4) as result',[actor,model,action,payload])).rows[0].result;
const assert=(x,m)=>{if(!x)throw new Error(m);console.log('PASS',m)};
const first=await call('save',draft);
const second=await call('save',{...draft,sku_id:first.sku.sku_id,effective_from:'2026-06-01T00:00:00Z',meters:[{...draft.meters[0],price_nanos:3000000000}]});
assert(second.sku.version===2 && second.sku.sku_id!==first.sku.sku_id,'revision creates a distinct version');
const old=(await db.query('select * from v2_pricing_skus where sku_id=$1',[first.sku.sku_id])).rows[0];
assert(new Date(old.effective_to).toISOString()==='2026-06-01T00:00:00.000Z','old version ends exactly at new start');
assert(Number((await db.query('select price_nanos from v2_pricing_sku_meters where sku_id=$1',[first.sku.sku_id])).rows[0].price_nanos)===2000000000,'old meter price preserved');
async function rejects(fn,label){try{await fn()}catch(e){console.log('PASS',label);return}throw new Error('Expected rejection: '+label)}
await rejects(()=>call('save',{...draft,sku_id:first.sku.sku_id,effective_from:'2026-07-01T00:00:00Z'}),'stale revision rejected');
await rejects(()=>call('end_date',{sku_id:second.sku.sku_id,effective_to:'2026-12-01T00:00:00Z'},'test/other'),'cross-model edit rejected');
await call('end_date',{sku_id:second.sku.sku_id,effective_to:'2026-12-01T00:00:00Z'});
assert((await db.query('select count(*)::int as n from v2_pricing_skus')).rows[0].n===2,'end-date retains every version');
await rejects(()=>db.exec('delete from v2_pricing_skus'),'delete prevented');
await rejects(()=>db.exec('truncate v2_catalogue_row_history'),'history truncation prevented');
await rejects(()=>db.exec('update v2_catalogue_row_history set actor_user_id=null'),'history updates prevented');
await db.query('select mutate_v2_admin_model_graph($1,$2,$3)',[actor,'test/model',{provider_models:[],provider_capabilities:[]}]);
assert((await db.query('select count(*)::int as n from v2_model_provider_routes')).rows[0].n===1,'omitted route retained');
await db.query('select mutate_v2_admin_model_graph($1,$2,$3)',[actor,'test/model',{provider_capabilities:[{provider_id:'test',provider_model_slug:'upstream',capability_id:'text.generate'}]}]);
await db.query('select mutate_v2_admin_model_graph($1,$2,$3)',[actor,'test/model',{provider_capabilities:[]}]);
assert((await db.query('select count(*)::int as n from v2_route_capabilities')).rows[0].n===1,'omitted capability retained');
await db.query('select mutate_v2_admin_model_graph($1,$2,$3)',[actor,'test/model',{provider_capabilities:[{provider_id:'test',provider_model_slug:'upstream',capability_id:'text.generate',effective_to:'2026-12-01T00:00:00Z'}]}]);
assert((await db.query("select count(*)::int as n from v2_catalogue_row_history where table_name='v2_route_capabilities' and operation='UPDATE' and before_state->>'effective_to' is null and after_state->>'effective_to' is not null")).rows[0].n===1,'capability dates audited with before and after');
await db.exec(`insert into v2_benchmarks(benchmark_id,name) values('bench','Bench'); insert into v2_subscription_plans(plan_uuid,plan_id,name) values('00000000-0000-4000-8000-000000000099','test-plan','Test Plan');`);
const graph=async(payload)=>(await db.query('select mutate_v2_admin_model_graph($1,$2,$3)',[actor,'test/model',payload]));
await graph({benchmark_results:[{benchmark_id:'bench',score:'42.5'}],subscription_plan_models:[{plan_uuid:'00000000-0000-4000-8000-000000000099'}]});
assert((await db.query("select * from get_v2_model_benchmarks('test/model')")).rows.length===1,'current benchmark is public');
assert((await db.query("select * from get_v2_model_subscription_plans('test/model')")).rows.length===1,'current plan membership is public');
const bench=(await db.query('select * from v2_benchmark_results')).rows[0];
await graph({benchmark_results:[{id:bench.result_id,benchmark_id:'bench',score:'42.5',effective_to:'2020-01-01T00:00:00Z'}],subscription_plan_models:[{plan_uuid:'00000000-0000-4000-8000-000000000099',effective_to:'2020-01-01T00:00:00Z'}]});
assert((await db.query('select * from v2_benchmark_results')).rows.length===1,'benchmark end-date retains original identity');
assert((await db.query("select * from get_v2_model_benchmarks('test/model')")).rows.length===0,'ended benchmark excluded from public reads');
assert((await db.query("select * from get_v2_model_subscription_plans('test/model')")).rows.length===0,'ended membership excluded from public reads');
assert((await db.query("select count(*)::int as n from v2_catalogue_row_history where table_name='v2_pricing_sku_meters' and model_slug='test/model'")).rows[0].n===2,'meter events associated with model history');
const alias=async(payload)=>(await db.query('select mutate_v2_admin_model_aliases($1,$2,$3)',[actor,'test/model',payload]));
await alias([{alias_slug:'test/latest'}]);
await alias([]);
assert((await db.query('select * from v2_model_aliases')).rows.length===1,'omitted alias retained');
await alias([{alias_slug:'test/latest',effective_to:'2020-01-01T00:00:00Z'}]);
assert((await db.query('select effective_to from v2_model_aliases')).rows[0].effective_to!==null,'alias can be end-dated');
await rejects(()=>db.query('select mutate_v2_admin_provider_route($1,$2,$3)',[actor,'test/other',{provider_model_id:'test:route',provider_slug:'test',provider_model_slug:'upstream'}]),'cross-model provider route edit rejected');
await rejects(()=>db.query('select mutate_v2_admin_pricing_sku($1,$2,$3,$4)',['00000000-0000-4000-8000-000000000002','test/model','save',draft]),'non-admin actor rejected');
await db.exec(`grant select on public.users to service_role;grant select,insert,update,delete on public.v2_pricing_skus,public.v2_pricing_sku_meters,public.v2_catalogue_admin_changes,public.v2_catalogue_source_overrides,public.v2_model_provider_routes to service_role;set role service_role;`);
const third=await call('save',{...draft,sku_code:'service-role-test'});
assert(Boolean(third.sku.sku_id),'service role can create a price with private audit trigger');
await rejects(()=>db.exec("insert into v2_catalogue_row_history(table_name,operation) values('x','INSERT')"),'service role cannot forge history');
await db.exec('reset role');
assert((await db.query("select has_function_privilege('anon','public.mutate_v2_admin_pricing_sku(uuid,text,text,jsonb)','execute') as allowed")).rows[0].allowed===false,'anonymous role cannot call mutation');
await db.exec(`alter table v2_providers add column residency_mode text default 'unknown', add column default_execution_regions text[], add column default_data_regions text[];`);
await db.exec(readMigration('20260907231005_admin_provider_residency.sql'));
const residency = (policy, who=actor) => db.query('select mutate_v2_admin_provider_residency($1,$2,$3) as result',[who,'test',policy]);
const policy={residency_mode:'provider_managed',default_execution_regions:['EU'],default_data_regions:['eu']};
await db.exec('grant select,update on v2_providers to service_role; set role service_role');
const savedPolicy=(await residency(policy)).rows[0].result;
assert(savedPolicy.default_execution_regions[0]==='eu' && savedPolicy.default_data_regions[0]==='eu','regional policy persists and normalizes execution and data regions');
await rejects(()=>residency({...policy,default_data_regions:['']}),'invalid residency region rejected');
await rejects(()=>residency(policy,'00000000-0000-4000-8000-000000000002'),'non-admin residency update rejected');
await db.exec('reset role');
const policyHistory=(await db.query("select * from v2_catalogue_row_history where table_name='v2_providers' and operation='UPDATE' order by event_id desc limit 1")).rows[0];
assert(policyHistory.actor_user_id===actor && policyHistory.before_state.default_execution_regions===null && policyHistory.after_state.default_execution_regions[0]==='eu','regional policy before/after and actor retained in history');
assert((await db.query("select has_function_privilege('anon','public.mutate_v2_admin_provider_residency(uuid,text,jsonb)','execute') as allowed")).rows[0].allowed===false,'anonymous residency mutation denied');
await db.exec(`alter table v2_providers add column provider_family_slug text, add column offer_scope text default 'global', add column offer_label text, add column byok_available boolean default false;`);
await db.exec(readMigration('20260907233148_admin_provider_offers.sql'));
const offerPayload={api_provider_name:'Test',parent_provider_slug:'test',offer_scope:'regional',offer_label:'EU',residency_mode:'provider_managed',default_execution_regions:['eu'],default_data_regions:['eu'],base_url:'https://eu.example.test/v1',link:'https://example.test'};
const offer=(action,payload,slug='test-eu',who=actor)=>db.query('select mutate_v2_admin_provider_offer($1,$2,$3,$4) as result',[who,action,slug,payload]);
await db.exec('grant insert on v2_providers to service_role; set role service_role');
const createdOffer=(await offer('create',offerPayload)).rows[0].result;
assert(createdOffer.provider_family_slug==='test' && createdOffer.default_data_regions[0]==='eu','regional provider creation links family and residency');
assert(createdOffer.routing_enabled===false && createdOffer.routable===false,'new regional provider starts with routing off');
assert(createdOffer.base_url==='https://eu.example.test/v1' && createdOffer.metadata.link==='https://example.test','API URL and website saved separately');
await rejects(()=>offer('create',offerPayload),'duplicate regional provider rejected');
await rejects(()=>offer('create',{...offerPayload,parent_provider_slug:'missing'},'test-new'),'unknown parent rejected');
await rejects(()=>offer('create',{...offerPayload,default_execution_regions:['global']},'test-global'),'global execution rejected for regional offer');
await rejects(()=>offer('create',offerPayload,'test-denied','00000000-0000-4000-8000-000000000002'),'non-admin provider creation rejected');
const editedOffer=(await offer('update',{api_provider_name:'Updated Test',link:'https://website.example.test'})).rows[0].result;
assert(editedOffer.base_url===createdOffer.base_url && editedOffer.default_execution_regions[0]==='eu','partial edit retains endpoint and regional fields');
await db.exec('reset role');
assert((await db.query("select count(*)::int as n from v2_catalogue_row_history where table_name='v2_providers' and after_state->>'provider_slug'='test-eu'")).rows[0].n===2,'regional creation and edit retained in history');
assert((await db.query("select has_function_privilege('anon','public.mutate_v2_admin_provider_offer(uuid,text,text,jsonb)','execute') as allowed")).rows[0].allowed===false,'anonymous provider offer mutation denied');
await db.exec(readMigration('20260907234642_restore_admin_model_notice.sql'));
const notice=(payload,model='test/model',who=actor)=>db.query('select mutate_v2_admin_model_notice($1,$2,$3) as result',[who,model,payload]);
await db.exec('grant select on v2_models to service_role; grant select,insert,update,delete on v2_model_page_notices to service_role; set role service_role');
const firstNotice=(await notice({tone:'warning',markdown:' First notice '})).rows[0].result;
assert(firstNotice.model_slug==='test/model' && firstNotice.markdown==='First notice','notice saves to the requested model');
await notice({tone:'info',markdown:'Other model'},'test/other');
await notice({tone:'critical',markdown:'Updated notice'});
await rejects(()=>notice({tone:'invalid',markdown:'Bad'}),'invalid notice tone rejected');
await rejects(()=>notice({tone:'info',markdown:'x'.repeat(20001)}),'oversized notice rejected');
await rejects(()=>notice({tone:'info',markdown:'Missing'},'test/missing'),'missing notice model rejected');
await rejects(()=>notice({tone:'info',markdown:'Denied'},'test/model','00000000-0000-4000-8000-000000000002'),'non-admin notice write rejected');
await notice(null);
assert((await db.query("select markdown from v2_model_page_notices where model_slug='test/other'")).rows[0].markdown==='Other model','clearing notice leaves other models unchanged');
await db.exec('reset role');
const noticeHistory=(await db.query("select operation,actor_user_id,before_state,after_state from v2_catalogue_row_history where table_name='v2_model_page_notices' and model_slug='test/model' order by event_id")).rows;
assert(noticeHistory.length===3 && noticeHistory.every(row=>row.actor_user_id===actor) && noticeHistory[2].before_state.markdown==='Updated notice' && noticeHistory[2].after_state===null,'notice create, update and clear retain actor and full history');
assert((await db.query("select has_function_privilege('anon','public.mutate_v2_admin_model_notice(uuid,text,jsonb)','execute') or has_function_privilege('authenticated','public.mutate_v2_admin_model_notice(uuid,text,jsonb)','execute') as allowed")).rows[0].allowed===false,'browser roles cannot execute notice mutation');
await db.exec("alter table v2_model_provider_routes add column is_stealth boolean not null default false, add constraint stealth_public_id_check check (not is_stealth or provider_model_id like 'stealth:%')");
await db.exec(readMigration('20260908003234_admin_stealth_provider_routes.sql'));
const stealthRoute = async (payload) => (await db.query('select mutate_v2_admin_provider_route($1,$2,$3) as route',[actor,'test/model',payload])).rows[0].route;
const stealth = await stealthRoute({provider_slug:'test',provider_model_slug:'private-upstream',is_stealth:true});
assert(stealth.is_stealth && stealth.provider_model_id.startsWith('stealth:') && !stealth.provider_model_id.includes('private-upstream'),'stealth creation generates an opaque route identity');
const stealthPrice = await call('save',{...draft,provider_model_id:stealth.provider_model_id});
const omitted = await stealthRoute({provider_model_id:stealth.provider_model_id,provider_slug:'test',provider_model_slug:'private-upstream'});
assert(omitted.is_stealth,'legacy saves preserve the existing stealth flag');
await stealthRoute({...omitted,is_stealth:false});
await stealthRoute({...omitted,is_stealth:true});
assert((await db.query('select provider_model_id from v2_pricing_skus where sku_id=$1',[stealthPrice.sku.sku_id])).rows[0].provider_model_id===stealth.provider_model_id,'stealth toggles preserve route and pricing identities');
await rejects(()=>stealthRoute({provider_model_id:'test:route',provider_slug:'test',provider_model_slug:'upstream',is_stealth:true}),'public route identity cannot become stealth and leak upstream names');
assert((await db.query("select count(*)::int as n from v2_catalogue_row_history where table_name='v2_model_provider_routes' and after_state->>'provider_model_id'=$1",[stealth.provider_model_id])).rows[0].n>0,'stealth mutations keep audit history');
await db.exec('alter table v2_subscription_plans enable row level security; create policy v2_subscription_plans_public_select on v2_subscription_plans for select to anon, authenticated using (true); grant select on v2_subscription_plans to anon, authenticated;');
await db.exec(readMigration('20260908093730_retire_subscription_plan_parents.sql'));
await db.exec("update v2_subscription_plan_models set effective_to=null");
assert((await db.query("select * from get_v2_model_subscription_plans('test/model')")).rows.length===1,'active parent and membership are public');
await db.exec("update v2_subscription_plans set effective_to=now()+interval '1 day'");
assert((await db.query("select * from get_v2_model_subscription_plans('test/model')")).rows.length===1,'future parent retirement remains public until its end');
await db.exec("update v2_subscription_plans set effective_to=now()-interval '1 day'");
assert((await db.query("select * from get_v2_model_subscription_plans('test/model')")).rows.length===0,'retired parent hides an otherwise active membership');
assert((await db.query('select * from v2_subscription_plans')).rows.length===1,'retired parent remains saved');
for (const role of ['anon', 'authenticated']) {
  await db.exec(`set role ${role}`);
  assert((await db.query('select * from v2_subscription_plans')).rows.length===0,`${role} table reads exclude retired parents`);
  await db.exec('reset role');
}
await db.exec("update v2_subscription_plans set effective_to=null");
assert((await db.query("select * from get_v2_model_subscription_plans('test/model')")).rows.length===1,'restored parent becomes public again');
await db.exec('set role anon');
assert((await db.query('select * from v2_subscription_plans')).rows.length===1,'anonymous table read includes restored parent');
await db.exec('reset role');
await db.exec("update v2_subscription_plan_models set effective_to=now()-interval '1 day'");
assert((await db.query("select * from get_v2_model_subscription_plans('test/model')")).rows.length===0,'retired membership remains hidden with active parent');
await db.close();
