import type { ResultGroup } from "./Search.types";

export const curatedGroups: ResultGroup[] = [
    {
        type: "quick-links",
        label: "Quick Actions",
        items: [
            {
                id: "quick-orgs",
                title: "Organisations",
                href: "/organisations",
                icon: "page",
            },
            {
                id: "quick-models",
                title: "Models",
                href: "/models",
                icon: "model",
            },
            {
                id: "quick-benchmarks",
                title: "Benchmarks",
                href: "/benchmarks",
                icon: "benchmark",
            },
            {
                id: "quick-providers",
                title: "API Providers",
                href: "/api-providers",
                icon: "api-provider",
            },
            {
                id: "quick-plans",
                title: "Subscription Plans",
                href: "/subscription-plans",
                icon: "plan",
            },
            {
                id: "quick-countries",
                title: "Countries",
                href: "/countries",
                icon: "country",
            },
        ],
    },
    {
        type: "featured-organisations",
        label: "Organisations",
        items: [
            {
                id: "org-openai",
                title: "OpenAI",
                href: "/organisations/openai",
                icon: "organisation",
                logoId: "openai",
                badge: "New Release"
            },
            {
                id: "org-google",
                title: "Google",
                href: "/organisations/google",
                icon: "organisation",
                logoId: "google",
                badge: "New Release"
            },
            {
                id: "org-anthropic",
                title: "Anthropic",
                href: "/organisations/anthropic",
                icon: "organisation",
                logoId: "anthropic",
                badge: "New Release"
            },
            {
                id: "org-xai",
                title: "xAI",
                href: "/organisations/x-ai",
                icon: "organisation",
                logoId: "x-ai",
                badge: "New Release"
            },
            {
                id: "org-deepseek",
                title: "DeepSeek",
                href: "/organisations/deepseek",
                icon: "organisation",
                logoId: "deepseek",
            },
            {
                id: "org-minimax",
                title: "Minimax AI",
                href: "/organisations/minimax",
                icon: "organisation",
                logoId: "minimax",
            },
        ],
    },
    {
        type: "featured-models",
        label: "Models",
        items: [
            {
                id: "model-gemini",
                title: "Gemini 3.0 Pro Preview",
                href: "/models/gemini-3.0-pro-preview",
                icon: "model",
                logoId: "google",
                badge: "New",
            },
            {
                id: "model-gpt5.2",
                title: "GPT-5.2",
                href: "/models/gpt-5.2",
                icon: "model",
                logoId: "openai",
                badge: "New",
            },
            {
                id: "model-claude",
                title: "Claude 4.5 Opus",
                href: "/models/claude-4.5-opus-20251120",
                icon: "model",
                logoId: "anthropic",
                badge: "New",
            },
            {
                id: "model-grok",
                title: "Grok-4.1",
                href: "/models/grok-4.1",
                icon: "model",
                logoId: "x-ai",
                badge: "New",
            },
            {
                id: "model-deepseek",
                title: "DeepSeek V3.2",
                href: "/models/deepseek-v3.2",
                icon: "model",
                logoId: "deepseek",
            },
            {
                id: "model-minimax",
                title: "Minimax M2",
                href: "/models/minimax-m2.1",
                icon: "model",
                logoId: "minimax",
            },
        ],
    },
    {
        type: "featured-benchmarks",
        label: "Benchmarks",
        items: [
            {
                id: "bench-gpqa",
                title: "GPQA Diamond",
                href: "/benchmarks/gpqa-diamond",
                icon: "benchmark",
            },
            {
                id: "bench-arc",
                title: "ARC-AGI 2",
                href: "/benchmarks/arc-agi-2",
                icon: "benchmark",
            },
            {
                id: "bench-humanitys-last-exam",
                title: "Humanity's Last Exam",
                href: "/benchmarks/humanitys-last-exam",
                icon: "benchmark",
            },

            {
                id: "bench-swe",
                title: "SWE-Bench",
                href: "/benchmarks/swe-bench",
                icon: "benchmark",
            },
            {
                id: "bench-lm-arena",
                title: "LMArena",
                href: "/benchmarks/lm-arena",
                icon: "benchmark",
            },
            {
                id: "bench-simple-bench",
                title: "Simple Bench",
                href: "/benchmarks/simple-bench",
                icon: "benchmark",
            },
        ],
    },
    {
        type: "featured-providers",
        label: "API Providers",
        items: [
            {
                id: "prov-openai",
                title: "OpenAI",
                href: "/api-providers/openai",
                icon: "api-provider",
                logoId: "openai",
            },
            {
                id: "prov-anthropic",
                title: "Anthropic",
                href: "/api-providers/anthropic",
                icon: "api-provider",
                logoId: "anthropic",
            },
            {
                id: "prov-google",
                title: "Google AI Studio",
                href: "/api-providers/google",
                icon: "api-provider",
                logoId: "google",
            },
            {
                id: "prov-xai",
                title: "xAI",
                href: "/api-providers/x-ai",
                icon: "api-provider",
                logoId: "x-ai",
            },
            {
                id: "prov-deepseek",
                title: "Deepseek",
                href: "/api-providers/deepseek",
                icon: "api-provider",
                logoId: "deepseek",
            },
            {
                id: "prov-qwen",
                title: "Qwen",
                href: "/api-providers/qwen",
                icon: "api-provider",
                logoId: "qwen",
            },
        ],
    },
    {
        type: "featured-plans",
        label: "Subscription plans",
        items: [
            {
                id: "plan-chatgpt-plus",
                title: "ChatGPT Plus",
                href: "/subscription-plans/chatgpt-plus",
                icon: "plan",
                logoId: "openai",
            },
            {
                id: "plan-chatgpt-pro",
                title: "ChatGPT Pro",
                href: "/subscription-plans/chatgpt-pro",
                icon: "plan",
                logoId: "openai",
            },
            {
                id: "plan-claude-pro",
                title: "Claude Pro",
                href: "/subscription-plans/claude-pro",
                icon: "plan",
                logoId: "anthropic",
            },
            {
                id: "plan-claude-max",
                title: "Claude Max",
                href: "/subscription-plans/claude-max-5x",
                icon: "plan",
                logoId: "anthropic",
            },
            {
                id: "plan-google-pro",
                title: "Google AI Pro",
                href: "/subscription-plans/google-ai-pro",
                icon: "plan",
                logoId: "google",
            },
            {
                id: "plan-grok-max",
                title: "Grok Max",
                href: "/subscription-plans/grok-max",
                icon: "plan",
                logoId: "x-ai",
            },
        ],
    },
    {
        type: "featured-countries",
        label: "Countries",
        items: [
            {
                id: "country-us",
                title: "United States",
                href: "/countries/us",
                icon: "country",
                flagIso: "us",
            },
            {
                id: "country-cn",
                title: "China",
                href: "/countries/cn",
                icon: "country",
                flagIso: "cn",
            },
            {
                id: "country-fr",
                title: "France",
                href: "/countries/fr",
                icon: "country",
                flagIso: "fr",
            },
            {
                id: "country-ca",
                title: "Canada",
                href: "/countries/ca",
                icon: "country",
                flagIso: "ca",
            },
            {
                id: "country-kr",
                title: "South Korea",
                href: "/countries/kr",
                icon: "country",
                flagIso: "kr",
            },
            {
                id: "country-il",
                title: "Israel",
                href: "/countries/il",
                icon: "country",
                flagIso: "il",
            },
        ],
    },
    {
        type: "featured-comparisons",
        label: "Quick comparisons",
        items: [
            {
                id: "compare-gpt5-claude",
                title: "GPT-5 vs Claude 3.5",
                href: "/compare?models=openai_gpt-5-2025-08-07,anthropic_claude-3-5-sonnet-2024-10-22",
                icon: "compare",
                leftLogoId: "openai",
                rightLogoId: "anthropic",
            },
            {
                id: "compare-gemini-gpt",
                title: "Gemini 3.0 Pro vs GPT-5",
                href: "/compare?models=google_gemini-3-0-pro-preview-2025-11-18,openai_gpt-5-2025-08-07",
                icon: "compare",
                leftLogoId: "google",
                rightLogoId: "openai",
            },
            {
                id: "compare-grok-claude",
                title: "Grok-4 vs Claude 3.5",
                href: "/compare?models=x-ai_grok-4-2025-07-10,anthropic_claude-3-5-sonnet-2024-10-22",
                icon: "compare",
                leftLogoId: "x-ai",
                rightLogoId: "anthropic",
            },
            {
                id: "compare-open-mistral",
                title: "Mistral vs OpenAI",
                href: "/compare?models=mistral_mistral-large-2-2024-07-24,openai_gpt-4o-2024-05-13",
                icon: "compare",
                leftLogoId: "mistral",
                rightLogoId: "openai",
            },
            {
                id: "compare-coding",
                title: "Coding models showdown",
                href: "/compare?models=deepseek_deepseek-r1-2025-05-28,openai_gpt-4o-2024-05-13",
                icon: "compare",
                leftLogoId: "deepseek",
                rightLogoId: "openai",
            },
            {
                id: "compare-llama-gpt",
                title: "Llama 3.3 vs GPT-5",
                href: "/compare?models=meta_llama-3-3-70b-instruct-2024-12-06,openai_gpt-5-2025-08-07",
                icon: "compare",
                leftLogoId: "meta",
                rightLogoId: "openai",
            },
        ],
    },
];
