import type { PaletteItem } from "./Search.types";

export type GlobalNavigationItem = PaletteItem & { href: string };

export const GLOBAL_NAVIGATION_ITEMS: readonly GlobalNavigationItem[] = [
	{ id: "nav-home", title: "Home", subtitle: "Phaseo overview", href: "/", keywords: ["dashboard", "landing"], shortcut: ["G", "H"] },
	{ id: "nav-models", title: "Models", subtitle: "Browse the AI model catalogue", href: "/models", keywords: ["model catalogue", "llms", "ai models"], shortcut: ["G", "M"] },
	{ id: "nav-model-table", title: "Model Table", subtitle: "View models in a compact table", href: "/models/table", keywords: ["models", "catalogue", "data table"] },
	{ id: "nav-compare", title: "Compare Models", subtitle: "Compare model capabilities and performance", href: "/compare", keywords: ["comparison", "versus", "vs"] },
	{ id: "nav-providers", title: "API Providers", subtitle: "Browse gateway and inference providers", href: "/api-providers", keywords: ["providers", "inference", "gateway providers"], shortcut: ["G", "P"] },
	{ id: "nav-organisations", title: "Organisations", subtitle: "Browse AI labs and organisations", href: "/organisations", keywords: ["companies", "labs", "organizations"] },
	{ id: "nav-benchmarks", title: "Benchmarks", subtitle: "Explore model evaluation results", href: "/benchmarks", keywords: ["evals", "scores", "leaderboards"], shortcut: ["G", "B"] },
	{ id: "nav-families", title: "Model Families", subtitle: "Browse related model families", href: "/families", keywords: ["families", "model series"] },
	{ id: "nav-countries", title: "Countries", subtitle: "Explore models and labs by country", href: "/countries", keywords: ["regions", "geography"] },
	{ id: "nav-plans", title: "Subscription Plans", subtitle: "Compare consumer AI subscriptions", href: "/subscription-plans", keywords: ["plans", "subscriptions", "chatgpt plus"] },
	{ id: "nav-collections", title: "Collections", subtitle: "Browse curated model collections", href: "/models/collections", keywords: ["model collections", "curated"] },
	{ id: "nav-apps", title: "Apps", subtitle: "Discover applications using the gateway", href: "/apps", keywords: ["applications", "ecosystem"] },
	{ id: "nav-rankings", title: "Rankings", subtitle: "View model and provider rankings", href: "/rankings", keywords: ["leaderboard", "market share", "usage"] },
	{ id: "nav-monitor", title: "Model Monitor", subtitle: "Monitor catalogue and provider coverage", href: "/monitor", keywords: ["monitoring", "status", "coverage"] },
	{ id: "nav-performance", title: "Performance", subtitle: "Explore latency and throughput", href: "/performance", keywords: ["speed", "latency", "throughput"] },
	{ id: "nav-pricing", title: "Pricing", subtitle: "Compare model API pricing", href: "/pricing", keywords: ["cost", "prices", "tokens"] },
	{ id: "nav-works-with", title: "Works With", subtitle: "Browse compatible clients and SDKs", href: "/works-with", keywords: ["compatibility", "integrations", "clients"] },

	{ id: "nav-chat", title: "Chat", subtitle: "Open the Phaseo chat playground", href: "/chat", keywords: ["playground", "prompt", "conversation"] },
	{ id: "nav-gateway", title: "Gateway", subtitle: "Phaseo AI Gateway overview", href: "/gateway", keywords: ["api", "inference", "routing"] },
	{ id: "nav-marketplace", title: "Gateway Marketplace", subtitle: "Browse shared gateway presets", href: "/gateway/marketplace", keywords: ["presets", "routing", "marketplace"] },
	{ id: "nav-gateway-usage", title: "Gateway Usage", subtitle: "Inspect gateway activity and costs", href: "/gateway/usage", keywords: ["requests", "logs", "spend"] },
	{ id: "nav-migrate", title: "Migration Guides", subtitle: "Migrate models and platforms", href: "/migrate", keywords: ["migration", "upgrade", "openrouter"] },

	{ id: "nav-updates", title: "Updates", subtitle: "Browse model and ecosystem updates", href: "/updates", keywords: ["news", "releases", "changelog"] },
	{ id: "nav-update-calendar", title: "Release Calendar", subtitle: "View releases and retirements by date", href: "/updates/calendar", keywords: ["calendar", "release dates", "deprecations"] },
	{ id: "nav-model-updates", title: "Model Updates", subtitle: "Browse model release updates", href: "/updates/models", keywords: ["releases", "new models"] },
	{ id: "nav-web-updates", title: "Web Updates", subtitle: "Browse updates from provider websites", href: "/updates/web", keywords: ["provider news", "web watcher"] },
	{ id: "nav-youtube-updates", title: "YouTube Updates", subtitle: "Browse tracked AI video updates", href: "/updates/youtube", keywords: ["videos", "youtube watcher"] },

	{ id: "nav-tools", title: "Developer Tools", subtitle: "Open the Phaseo tools collection", href: "/tools", keywords: ["utilities", "developer"] },
	{ id: "nav-pricing-calculator", title: "Pricing Calculator", subtitle: "Estimate model request costs", href: "/tools/pricing-calculator", keywords: ["cost calculator", "tokens"] },
	{ id: "nav-latency-tool", title: "Latency Comparison", subtitle: "Compare provider response latency", href: "/tools/latency-comparison", keywords: ["speed", "performance tool"] },
	{ id: "nav-request-builder", title: "Request Builder", subtitle: "Build gateway API requests", href: "/tools/request-builder", keywords: ["api request", "curl", "json"] },
	{ id: "nav-json-formatter", title: "JSON Formatter", subtitle: "Format and inspect JSON", href: "/tools/json-formatter", keywords: ["developer utility", "pretty print"] },
	{ id: "nav-markdown-preview", title: "Markdown Preview", subtitle: "Preview rendered Markdown", href: "/tools/markdown-preview", keywords: ["md", "renderer"] },

	{ id: "nav-settings", title: "Settings", subtitle: "Manage your account and workspace", href: "/settings", keywords: ["account", "workspace", "preferences"], shortcut: ["G", "S"] },
	{ id: "nav-settings-profile", title: "Profile Settings", subtitle: "Manage your public profile", href: "/settings/profile", keywords: ["profile", "avatar", "name"] },
	{ id: "nav-settings-account", title: "Account Settings", subtitle: "Manage account details and security", href: "/settings/account", keywords: ["account", "security", "mfa", "passkeys"] },
	{ id: "nav-settings-billing", title: "Billing", subtitle: "Manage credits and payment details", href: "/settings/credits", keywords: ["credits", "payments", "transactions", "invoices"] },
	{ id: "nav-settings-usage", title: "Usage", subtitle: "Review gateway usage", href: "/settings/usage", keywords: ["requests", "spend", "analytics"] },
	{ id: "nav-settings-logs", title: "Request Logs", subtitle: "Inspect individual gateway requests", href: "/settings/usage/logs", keywords: ["logs", "requests", "debug"] },
	{ id: "nav-settings-alerts", title: "Usage Alerts", subtitle: "Configure spend and usage alerts", href: "/settings/usage/alerts", keywords: ["alerts", "budget", "notifications"] },
	{ id: "nav-settings-members", title: "Workspace Members", subtitle: "Manage workspace members", href: "/settings/workspaces/members", keywords: ["team", "members", "invitations"] },
	{ id: "nav-settings-access", title: "Workspace Access", subtitle: "Manage workspace access controls", href: "/settings/workspaces/access", keywords: ["roles", "permissions", "team"] },
	{ id: "nav-settings-keys", title: "API Keys", subtitle: "Create and manage gateway API keys", href: "/settings/keys", keywords: ["keys", "tokens", "credentials"] },
	{ id: "nav-settings-apps", title: "Workspace Apps", subtitle: "Manage gateway applications", href: "/settings/apps", keywords: ["apps", "applications"] },
	{ id: "nav-settings-management-keys", title: "Management Keys", subtitle: "Manage provisioning credentials", href: "/settings/management-api-keys", keywords: ["management api", "provisioning keys"] },
	{ id: "nav-settings-routing", title: "Routing Settings", subtitle: "Configure gateway routing", href: "/settings/routing", keywords: ["routing", "providers", "fallbacks"] },
	{ id: "nav-settings-byok", title: "Bring Your Own Key", subtitle: "Manage provider API credentials", href: "/settings/byok", keywords: ["byok", "provider keys", "credentials"] },
	{ id: "nav-settings-presets", title: "Routing Presets", subtitle: "Create reusable routing presets", href: "/settings/presets", keywords: ["presets", "routing profiles"] },
	{ id: "nav-settings-privacy", title: "Privacy Settings", subtitle: "Configure data handling preferences", href: "/settings/privacy", keywords: ["privacy", "retention", "zdr"] },
	{ id: "nav-settings-guardrails", title: "Guardrails", subtitle: "Manage request and response guardrails", href: "/settings/guardrails", keywords: ["safety", "validation", "policies"] },
	{ id: "nav-settings-oauth", title: "OAuth Apps", subtitle: "Manage OAuth applications and grants", href: "/settings/oauth-apps", keywords: ["oauth", "clients", "authorized apps"] },
	{ id: "nav-settings-broadcast", title: "Broadcast", subtitle: "Configure observability destinations", href: "/settings/broadcast", keywords: ["observability", "telemetry", "destinations"] },
	{ id: "nav-settings-webhooks", title: "Webhooks", subtitle: "Manage event webhooks", href: "/settings/webhooks", keywords: ["events", "callbacks", "notifications"] },
	{ id: "nav-settings-sdk", title: "SDKs", subtitle: "Configure and download SDK integrations", href: "/settings/sdk", keywords: ["typescript", "python", "client libraries"] },

	{ id: "nav-help", title: "Help Centre", subtitle: "Find help and support articles", href: "/help", keywords: ["support", "guides", "questions"] },
	{ id: "nav-blog", title: "Blog", subtitle: "Read Phaseo articles", href: "/blog", keywords: ["articles", "news"] },
	{ id: "nav-announcements", title: "Announcements", subtitle: "Read product announcements", href: "/announcements", keywords: ["news", "releases"] },
	{ id: "nav-methodology", title: "Methodology", subtitle: "Learn how Phaseo evaluates AI systems", href: "/methodology", keywords: ["methods", "evaluation", "research"] },
	{ id: "nav-roadmap", title: "Roadmap", subtitle: "See what Phaseo is building", href: "/roadmap", keywords: ["planned", "coming soon"] },
	{ id: "nav-about", title: "About", subtitle: "Learn about Phaseo", href: "/about", keywords: ["company", "mission"] },
	{ id: "nav-faq", title: "FAQ", subtitle: "Frequently asked questions", href: "/faq", keywords: ["questions", "help"] },
	{ id: "nav-contribute", title: "Contribute", subtitle: "Contribute data and improvements", href: "/contribute", keywords: ["github", "community", "submit"] },
	{ id: "nav-contact", title: "Contact", subtitle: "Contact the Phaseo team", href: "/contact", keywords: ["support", "email", "sales"] },
];
