export type ModelPerformancePoint = { bucket: string; avgThroughput: number | null; avgOutputSpeed?: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; avgPhaseoOverheadMs?: number | null; avgTpotMs?: number | null; avgItlMs?: number | null; cachedInputPct?: number | null; cacheTelemetryRequests?: number; requests: number; successPct: number | null };
export type ModelSuccessPoint = { bucket: string; overallSuccessPct: number | null; worstProviderSuccessPct: number | null; worstProviderRequests?: number; providerCount?: number; requests: number };
export type ModelTimeOfDayPoint = { hour: number; avgThroughput: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; sampleCount: number };
export type ModelProviderUptimeBucket = { start: string; end: string; successPct: number | null; errorPct?: number | null; requests?: number; successfulRequests?: number; failedRequests?: number };
export type ModelProviderPerformance = { provider: string; providerName: string; providerColor?: string | null; avgThroughput: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; requests: number; uptimePct: number | null; uptimeBuckets: ModelProviderUptimeBucket[] };
export type ModelProviderMetricPoint = { provider: string; providerName: string; providerColor: string | null; avgThroughput: number | null; avgOutputSpeed?: number | null; avgLatencyMs: number | null; avgEndToEndMs?: number | null; avgGenerationMs: number | null; avgPhaseoOverheadMs?: number | null; avgTpotMs?: number | null; avgItlMs?: number | null; cachedInputPct?: number | null; cachedInputTokens?: number | null; effectiveInputTokens?: number | null; cacheTelemetryRequests?: number; requests: number };
export type ModelProviderDailyPoint = ModelProviderMetricPoint & { day: string };
export type ModelProviderHourlyPoint = ModelProviderMetricPoint & { bucket: string };
export type ModelProviderTrendPoint = ModelProviderDailyPoint | ModelProviderHourlyPoint;
export type ModelProviderPercentileDailyPoint = ModelProviderDailyPoint & { percentile: number };
export type ModelPerformanceQualityPoint = { bucket: string; toolCallSuccessPct: number | null; toolCallErrorPct?: number | null; toolCallHistoricalDefault?: boolean; toolCallErrorCounts?: { invalidJson: number; schemaMismatch: number; unknownToolName: number }; structuredOutputSuccessPct: number | null; structuredOutputErrorPct?: number | null; structuredOutputHistoricalDefault?: boolean; structuredOutputErrorCounts?: { invalidJson: number; schemaMismatch: number; missingOutput: number }; cacheHitRatePct: number | null; requests: number };
export interface ModelPerformanceSummary { avgThroughput: number | null; avgOutputSpeed?: number | null; avgLatencyMs: number | null; avgGenerationMs: number | null; avgPhaseoOverheadMs?: number | null; avgTpotMs?: number | null; avgItlMs?: number | null; uptimePct: number | null; totalRequests: number; successfulRequests: number }
export interface ModelPerformanceRange { start: string; end: string }
export interface ModelPerformanceMetrics { cloudflareColo?: string | null; percentile?: number | null; rangeDays?: 1 | 3 | 7; streamMode?: "all" | "stream" | "non_stream"; contextBucket?: "all" | "lte_4k" | "4k_16k" | "16k_64k" | "gt_64k"; summary: ModelPerformanceSummary; prevSummary?: ModelPerformanceSummary | null; hourly: ModelPerformancePoint[]; successSeries: ModelSuccessPoint[]; timeOfDay: ModelTimeOfDayPoint[]; providerPerformance: ModelProviderPerformance[]; providerDaily7d: ModelProviderDailyPoint[]; providerHourly7d?: ModelProviderHourlyPoint[]; providerPercentileDaily7d?: ModelProviderPercentileDailyPoint[]; qualitySeries?: ModelPerformanceQualityPoint[]; dataRange: ModelPerformanceRange; cumulativeTokens?: number | null; releaseDate?: string | null }
export interface ModelPerformanceActivitySnapshot { summary: ModelPerformanceSummary; providerPerformance: ModelProviderPerformance[]; cumulativeTokens?: number | null }
