CREATE TABLE "private"."provider_health_refresh_queue" (
  "usage_date"        date                     NOT NULL,
  "model_slug"        text                     NOT NULL,
  "provider_model_id" text                     NOT NULL,
  "generation"        bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "requested_at"      timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  "retry_after"       timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  "last_error_code"   text,
  CONSTRAINT "provider_health_refresh_queue_pkey" PRIMARY KEY (usage_date, model_slug, provider_model_id)
);

ALTER TABLE "private"."provider_health_refresh_queue"
  ENABLE ROW LEVEL SECURITY;
