CREATE TABLE "private"."public_reporting_refresh_queue" (
  "report"          text                     NOT NULL,
  "bucket_start"    date                     NOT NULL,
  "generation"      bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "requested_at"    timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  "retry_after"     timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  "last_error_code" text,
  "transaction_id"  bigint                   NOT NULL DEFAULT txid_current(),
  "signal_shard"    integer                  NOT NULL DEFAULT (mod(txid_current(), (64)::bigint))::integer,
  CONSTRAINT "public_reporting_refresh_queue_pkey" PRIMARY KEY (generation),
  CONSTRAINT "public_reporting_refresh_queue_report_check" CHECK ((report = ANY (ARRAY['users_daily'::text, 'workspaces_weekly'::text]))),
  CONSTRAINT "public_reporting_signal_shard_check" CHECK (((signal_shard >= 0) AND (signal_shard < 64)))
);

ALTER TABLE "private"."public_reporting_refresh_queue"
  ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX public_reporting_refresh_shard_idx ON private.public_reporting_refresh_queue USING btree (report, bucket_start, signal_shard);

COMMENT ON TABLE "private"."public_reporting_refresh_queue" IS 'Dirty UTC periods with 64 transaction lanes each; repeated meters coalesce; one period per five minutes, ten-second run cap, two-hour failed-run backoff.';
