import { EventEmitter } from "node:events";
import { describe, expect, it, vi } from "vitest";
import type { BrowserWindow, DownloadItem } from "electron";
vi.mock("electron", () => ({ shell: { showItemInFolder: vi.fn() } }));
import { shell } from "electron";
import { BrowserDownloads } from "./browserDownloads";
function owner() { const events = new EventEmitter(); return Object.assign(events, { isDestroyed: () => false, webContents: { send: vi.fn() } }) as unknown as BrowserWindow; }
function item() { const events = new EventEmitter(); let paused = false; return Object.assign(events, { getFilename: () => "report.pdf", getURL: () => "https://owned.test/report", getTotalBytes: () => 100, getReceivedBytes: () => 40, getSavePath: () => "/owned/report.pdf", isPaused: () => paused, canResume: () => paused, pause: vi.fn(() => { paused = true; }), resume: vi.fn(() => { paused = false; }), cancel: vi.fn(() => events.emit("done", {}, "cancelled")) }) as unknown as DownloadItem; }
describe("browser downloads", () => {
 it("tracks native progress and saves the confirmed path on completion", () => { const service = new BrowserDownloads(), window = owner(), transfer = item(); service.accept(window, "chat:tab", transfer); transfer.emit("updated", {}, "progressing"); expect(service.command(window, { type: "list" })[0]).toMatchObject({ received: 40, path: "/owned/report.pdf", finished: false }); transfer.emit("done", {}, "completed"); const download = service.command(window, { type: "list" })[0]; expect(download).toMatchObject({ status: "completed", finished: true, resumable: false }); service.command(window, { type: "reveal", id: download.id }); expect(shell.showItemInFolder).toHaveBeenCalledWith("/owned/report.pdf"); expect(() => service.command(window, { type: "cancel", id: download.id })).toThrow("finished"); });
 it("isolates owners and guards active removal and incomplete reveal", () => { const service = new BrowserDownloads(), window = owner(); service.accept(window, "chat", item()); const download = service.command(window, { type: "list" })[0]; expect(() => service.command(owner(), { type: "cancel", id: download.id })).toThrow("available"); expect(() => service.command(window, { type: "dismiss", id: download.id })).toThrow("Cancel"); expect(() => service.command(window, { type: "reveal", id: download.id })).toThrow("completed"); });
 it("pauses, resumes, cancels and removes through native operations", () => { const service = new BrowserDownloads(), window = owner(), transfer = item(); service.accept(window, "chat", transfer); const id = service.command(window, { type: "list" })[0].id; expect(service.command(window, { type: "pause", id })[0].status).toBe("paused"); expect(service.command(window, { type: "resume", id })[0].status).toBe("progressing"); expect(transfer.resume).toHaveBeenCalledOnce(); expect(service.command(window, { type: "cancel", id })[0]).toMatchObject({ status: "cancelled", finished: true }); expect(service.command(window, { type: "dismiss", id })).toEqual([]); });
 it("bounds concurrent transfers, prunes finished metadata and cancels on owner shutdown", () => { const service = new BrowserDownloads(), window = owner(); for (let index=0; index<100; index++) { const transfer=item(); service.accept(window, "chat", transfer); transfer.emit("done", {}, "completed"); } service.accept(window, "chat", item()); expect(service.command(window, { type: "list" })).toHaveLength(100); const active=Array.from({length:20},item); for (const transfer of active) service.accept(window, "chat", transfer); expect(active[19].cancel).toHaveBeenCalledOnce(); expect(service.command(window,{type:"list"})[0]).toMatchObject({status:"cancelled",error:expect.stringContaining("Twenty downloads")}); window.emit("closed"); expect(active[0].cancel).toHaveBeenCalledOnce(); expect(service.command(window, { type: "list" })).toEqual([]); });
 it("rejects malformed and unsupported requests", () => { const service = new BrowserDownloads(), window = owner(); for(const request of [null, {}, {type:"open",id:"owned"}, {type:"pause",id:5}]) expect(() => service.command(window,request)).toThrow(); });
});
