import { describe, expect, it, vi } from "vitest";
const sdk = vi.hoisted(() => ({ query: vi.fn() }));
vi.mock("@anthropic-ai/claude-agent-sdk", () => ({ query: sdk.query }));
vi.mock("./nativeProcess", () => ({ resolveNativeCommand: async () => ({ executable: "claude", prefix: [] }) }));
import { claudeNativeActionCatalog, claudeNativeActions } from "./claudeNativeActions";
describe("Claude command catalogs", () => {
 it("preserves native slash names, aliases and bounded argument hints without inventing skill prefixes", () => { const actions = claudeNativeActionCatalog([{ name: "review", description: "Review", argumentHint: "<path>", aliases: ["inspect"] }]).actions; expect(actions).toEqual([{ kind: "command", id: "inspect", name: "inspect", description: "Review", argumentHint: "<path>" }, { kind: "command", id: "review", name: "review", description: "Review", argumentHint: "<path>" }]); });
 it.each([[{ name: "bad name" }], [{ name: "first", aliases: ["second"] }, { name: "second" }], [{ name: "review", aliases: [42] }], Array.from({ length: 1001 }, (_, id) => ({ name: "command" + id }))].map(commands => ({ commands })))("rejects invalid, ambiguous or oversized identities", ({ commands }) => { expect(() => claudeNativeActionCatalog(commands)).toThrow(); });
 it("holds input without inference, denies tools and uses the selected account environment", async () => { vi.stubEnv("ANTHROPIC_API_KEY", "foreign-fixture-key"); let iterator!: AsyncIterator<unknown>; const close = vi.fn(); sdk.query.mockImplementation(({ prompt }) => { iterator = prompt[Symbol.asyncIterator](); return { supportedCommands: async () => [{ name: "review", description: "Owned" }], close }; }); try { const catalog = await claudeNativeActions("/project", new AbortController().signal, { id: "owned", name: "Owned", harness: "claude", kind: "native", configured: true, configDirectory: "/account" }); expect(catalog.actions[0].id).toBe("review"); expect(await iterator.next()).toMatchObject({ done: true }); const options = sdk.query.mock.lastCall![0].options; expect(options).toMatchObject({ cwd: "/project", persistSession: false, tools: [], strictMcpConfig: true, mcpServers: {}, env: { CLAUDE_CONFIG_DIR: "/account", ANTHROPIC_API_KEY: undefined, CLAUDE_CODE_OAUTH_TOKEN: undefined } }); expect(await options.canUseTool("Bash", {})).toMatchObject({ behavior: "deny" }); expect(close).toHaveBeenCalledOnce(); } finally { vi.unstubAllEnvs(); } });
 it.each(["cancelled", "timed out"])("closes a stalled SDK query when discovery is %s without releasing input", async kind => { vi.useFakeTimers(); const close = vi.fn(); let iterator!: AsyncIterator<unknown>; sdk.query.mockImplementation(({ prompt }) => { iterator = prompt[Symbol.asyncIterator](); return { supportedCommands: () => new Promise(() => {}), close }; }); const controller = new AbortController(); try { const operation = claudeNativeActions("/project", controller.signal); const rejected = expect(operation).rejects.toThrow(kind); await Promise.resolve(); await Promise.resolve(); if (kind === "cancelled") controller.abort(); else await vi.advanceTimersByTimeAsync(15000); await rejected; expect(close).toHaveBeenCalled(); expect(await iterator.next()).toMatchObject({ done: true }); } finally { vi.useRealTimers(); } });
});
