import { describe, expect, it, vi } from "vitest";
import type { OpenCodeClient } from "@opencode/client";
import { OpenCodeCommandOutput } from "./openCodeCommandOutput";
import { openCodeNativeActions } from "./openCodeNativeActions";
import { nativeActionText, updateNativeActionText, validateNativeAction } from "../shared/nativeActions";
describe("explicit native actions", () => {
 it("uses the native 200-record ceiling and never combines a cursor with order", async () => {
  const rows = Array.from({ length: 200 }, (_, id) => ({ id: String(id), type: "assistant", content: [], finish: "stop" })); const list = vi.fn().mockResolvedValueOnce({ data: [{ id: "old" }] }).mockResolvedValueOnce({ data: rows, cursor: { next: "page-two" } }).mockResolvedValueOnce({ data: [{ id: "old" }] });
  const output = new OpenCodeCommandOutput({ message: { list } } as unknown as OpenCodeClient, "session", new AbortController().signal, vi.fn()); await output.start(); await output.finish();
  expect(list.mock.calls[1][0]).toEqual({ sessionID: "session", type: "assistant", limit: 200, order: "desc" }); expect(list.mock.calls[2][0]).toEqual({ sessionID: "session", type: "assistant", limit: 200, cursor: "page-two" });
 });

 it("keeps argument edits and drops invocation intent when the prefix changes", () => { const action = { kind: "command" as const, id: "review", name: "review", arguments: "old" }; expect(updateNativeActionText(action, "/review new")).toEqual({ ...action, arguments: "new" }); expect(updateNativeActionText(action, "/reviewer new")).toBeUndefined(); expect(nativeActionText(validateNativeAction({ ...action, extra: "ignored" }))).toBe("/review old"); expect(validateNativeAction({ ...action, extra: "ignored" })).not.toHaveProperty("extra"); expect(() => validateNativeAction({ ...action, id: "bad\n" })).toThrow(); });
 it("scopes both native catalogs and exposes metadata without skill content", async () => { const signal = new AbortController().signal; const command = vi.fn(async () => ({ data: [{ name: "review", description: "Review code" }] })); const skill = vi.fn(async () => ({ data: [{ id: "native-skill", name: "Review skill", path: "/project/skill.md", content: "Private instructions" }] })); const value = await openCodeNativeActions({ command: { list: command }, skill: { list: skill } } as unknown as OpenCodeClient, "/project", signal); expect(command).toHaveBeenCalledWith({ location: { directory: "/project" } }, { signal }); expect(skill).toHaveBeenCalledWith({ location: { directory: "/project" } }, { signal }); expect(value.actions).toHaveLength(2); expect(value.actions[1]).not.toHaveProperty("content"); });
 it("rejects duplicate native identities", async () => { const client = { command: { list: async () => ({ data: [{ name: "same" }, { name: "same" }] }) }, skill: { list: async () => ({ data: [] }) } }; await expect(openCodeNativeActions(client as unknown as OpenCodeClient, ".", new AbortController().signal)).rejects.toThrow("duplicate"); });
 it("recovers late text once and ignores late deltas after durable completion", async () => { const list = vi.fn().mockResolvedValueOnce({ data: [{ id: "old" }] }).mockResolvedValueOnce({ data: [{ id: "new", type: "assistant", content: [{ type: "text", text: "Full answer" }], finish: "stop" }, { id: "old" }] }); const delta = vi.fn(); const output = new OpenCodeCommandOutput({ message: { list } } as unknown as OpenCodeClient, "session", new AbortController().signal, delta); await output.start(); output.stream("new", "Full "); await output.finish(); output.stream("new", "answer"); expect(delta.mock.calls).toEqual([["new", "Full "], ["new", "answer"]]); });
 it.each(["missing", "divergent", "failed"])("does not report success for %s durable output", async kind => { const list = vi.fn().mockResolvedValueOnce({ data: [{ id: "old" }] }).mockResolvedValueOnce({ data: [{ id: "new", type: "assistant", content: [{ type: "text", text: "answer" }], finish: kind === "failed" ? "error" : "stop" }, ...(kind === "missing" ? [] : [{ id: "old" }])] }); const output = new OpenCodeCommandOutput({ message: { list } } as unknown as OpenCodeClient, "session", new AbortController().signal, vi.fn()); await output.start(); if (kind === "divergent") output.stream("new", "different"); await expect(output.finish()).rejects.toThrow(); });
});
