import { EventEmitter } from "node:events";
import { PassThrough } from "node:stream";
import { describe, expect, it, vi } from "vitest";
const native = vi.hoisted(() => ({ spawn: vi.fn() }));
vi.mock("./nativeProcess", () => ({ spawnNative: native.spawn }));
import { piNativeActionCatalog, piNativeActions } from "./piNativeActions";
describe("Pi native catalogs", () => {
 it("projects prompt, extension and skill metadata while preserving dispatch identities", () => { expect(piNativeActionCatalog({ commands: [{ name: "skill:research", source: "skill", description: "Research", sourceInfo: { path: "/project/SKILL.md" }, content: "private" }, { name: "review", source: "prompt" }, { name: "release", source: "extension" }] }).actions).toEqual([{ kind: "command", id: "release", name: "release", description: "" }, { kind: "command", id: "review", name: "review", description: "" }, { kind: "skill", id: "skill:research", name: "research", description: "Research", path: "/project/SKILL.md" }]); });
 it.each([{ commands: [{ name: "x", source: "unknown" }] }, { commands: [{ name: "missing-prefix", source: "skill" }] }, { commands: [{ name: "same", source: "prompt" }, { name: "same", source: "extension" }] }, { commands: Array.from({ length: 1001 }, () => ({ name: "x", source: "prompt" })) }])("rejects invalid, ambiguous and oversized catalogs", value => { expect(() => piNativeActionCatalog(value)).toThrow(); });
 it("discovers without a prompt/session and stops its owned RPC process", async () => { const child = Object.assign(new EventEmitter(), { stdin: new PassThrough(), stdout: new PassThrough(), stderr: new PassThrough(), kill: vi.fn() }); const packets: Record<string, unknown>[] = []; child.stdin.on("data", chunk => { const packet = JSON.parse(chunk.toString()); packets.push(packet); child.stdout.write(JSON.stringify({ type: "response", id: packet.id, success: true, data: { commands: [] } }) + "\n"); }); native.spawn.mockResolvedValue(child); expect(await piNativeActions("/project", new AbortController().signal)).toEqual({ actions: [] }); expect(native.spawn.mock.lastCall?.slice(0, 3)).toEqual(["pi", ["--mode", "rpc", "--no-tools", "--no-session"], "/project"]); expect(packets.map(packet => packet.type)).toEqual(["get_commands"]); expect(child.kill).toHaveBeenCalledOnce(); });
 it("cancels a pending catalog without sending a prompt", async () => { const child = Object.assign(new EventEmitter(), { stdin: new PassThrough(), stdout: new PassThrough(), stderr: new PassThrough(), kill: vi.fn() }); native.spawn.mockResolvedValue(child); const controller = new AbortController(); const operation = piNativeActions("/project", controller.signal); await vi.waitFor(() => expect(child.stdin.readableLength).toBeGreaterThan(0)); const rejected = expect(operation).rejects.toThrow("cancelled"); controller.abort(); await rejected; expect(child.kill).toHaveBeenCalled(); });
});
