import { beforeEach, describe, expect, it, vi } from "vitest";
const ports=vi.hoisted(()=>({detail:vi.fn(),resolve:vi.fn(),execute:vi.fn()}));
vi.mock("./projectPullRequests",()=>({projectPullRequest:ports.detail}));vi.mock("./nativeProcess",()=>({resolveNativeCommand:ports.resolve}));vi.mock("node:util",()=>({promisify:()=>ports.execute}));
import { parsePullRequestFiles, projectPullRequestFiles } from "./projectPullRequestFiles";
const query={number:12,page:1,headOid:"a".repeat(40),baseOid:"b".repeat(40)};
const detail={...query,repository:"owned/repo",changedFiles:1};const file={filename:"src/世界 file.ts",status:"modified",additions:1,deletions:1,sha:"c".repeat(40),patch:"@@ -1 +1 @@\n-before\n+after"};
describe("PR changed files",()=>{
 beforeEach(()=>{vi.clearAllMocks();ports.detail.mockResolvedValue(detail);ports.resolve.mockResolvedValue({executable:"/owned/gh",prefix:[]});ports.execute.mockResolvedValue({stdout:JSON.stringify([file])});});
 it("uses literal bounded GET arguments and checks both commit identities before and after",async()=>{const result=await projectPullRequestFiles("/owned",query);expect(result).toMatchObject({page:1,total:1,hasNext:false,files:[{filename:file.filename,preview:"available",blobOid:file.sha}]});expect(ports.detail).toHaveBeenCalledTimes(2);expect(ports.execute).toHaveBeenCalledWith("/owned/gh",expect.arrayContaining(["--method","GET","repos/owned/repo/pulls/12/files","-F","per_page=100","-F","page=1"]),expect.objectContaining({cwd:"/owned",windowsHide:true,timeout:20000,maxBuffer:8388608}));});
 it.each([null,{}, {...query,page:0},{...query,page:31},{...query,number:"12"},{...query,headOid:"bad"}])("rejects invalid inputs before any native read",async value=>{await expect(projectPullRequestFiles("/owned",value)).rejects.toThrow("Invalid");expect(ports.detail).not.toHaveBeenCalled();expect(ports.execute).not.toHaveBeenCalled();});
 it.each(["headOid","baseOid"])("rejects an obsolete %s before fetching files",async key=>{ports.detail.mockResolvedValue({...detail,[key]:"d".repeat(40)});await expect(projectPullRequestFiles("/owned",query)).rejects.toThrow("changed");expect(ports.execute).not.toHaveBeenCalled();});
 it.each([{headOid:"d".repeat(40)},{baseOid:"d".repeat(40)},{repository:"other/repo"},{changedFiles:2}])("rejects changes while files load",async patch=>{ports.detail.mockResolvedValueOnce(detail).mockResolvedValueOnce({...detail,...patch});await expect(projectPullRequestFiles("/owned",query)).rejects.toThrow("changed while");});
 it("returns bounded terminal pages and discloses the native 3000-file ceiling",async()=>{ports.detail.mockResolvedValue({...detail,changedFiles:3001});ports.execute.mockResolvedValue({stdout:JSON.stringify(Array.from({length:100},(_,index)=>({...file,filename:String(index)})))});expect(await projectPullRequestFiles("/owned",{...query,page:30})).toMatchObject({limitReached:true,hasNext:false,total:3001,page:30});});
 it("rejects missing page records and pages outside the confirmed total",async()=>{ports.execute.mockResolvedValue({stdout:"[]"});await expect(projectPullRequestFiles("/owned",query)).rejects.toThrow("incomplete");await expect(projectPullRequestFiles("/owned",{...query,page:2})).rejects.toThrow("no longer available");});
 it.each([null,[file,file],[{...file,sha:"bad"}],[{...file,filename:""}],[{...file,filename:"bad\0path"}],[{...file,additions:-1}],[{...file,patch:{}}]])("rejects malformed or repeated files",value=>{expect(()=>parsePullRequestFiles(value)).toThrow("invalid");});
 it("retains metadata for omitted, binary, oversized and over-budget previews",()=>{expect(parsePullRequestFiles([{...file,patch:null,preview_limited:true}])[0].preview).toBe("too-large");expect(parsePullRequestFiles([{...file,patch:null}])[0]).toMatchObject({preview:"unavailable",patch:undefined});expect(parsePullRequestFiles([{...file,patch:"x".repeat(200001)}])[0].preview).toBe("too-large");const result=parsePullRequestFiles(Array.from({length:6},(_,index)=>({...file,filename:String(index),patch:"x".repeat(200000)})));expect(result.filter(value=>value.preview==="available")).toHaveLength(5);expect(result[5].preview).toBe("too-large");});
 it("keeps native failure diagnostics private",async()=>{ports.execute.mockRejectedValue(Error("private token"));await expect(projectPullRequestFiles("/owned",query)).rejects.toThrow("Check GitHub CLI sign-in");});
});
