import { createHash } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";
const ports=vi.hoisted(()=>({files:vi.fn(),detail:vi.fn(),resolve:vi.fn(),execute:vi.fn()}));
vi.mock("./projectPullRequestFiles",()=>({projectPullRequestFiles:ports.files}));vi.mock("./projectPullRequests",()=>({projectPullRequest:ports.detail}));vi.mock("./nativeProcess",()=>({resolveNativeCommand:ports.resolve}));vi.mock("node:util",()=>({promisify:()=>ports.execute}));
import { decodePullRequestBlob, projectPullRequestContents } from "./projectPullRequestContents";
const query={number:12,page:1,headOid:"a".repeat(40),baseOid:"b".repeat(40),filename:"new file.ts"};
function blob(text:string){const bytes=Buffer.from(text);return {sha:createHash("sha1").update(`blob ${bytes.length}\0`).update(bytes).digest("hex"),size:bytes.length,encoding:"base64",content:bytes.toString("base64")};}
const old=blob("before\n"),next=blob("after\n");
function metadata(value:ReturnType<typeof blob>){return {data:{repository:{object:{__typename:"Blob",oid:value.sha,byteSize:value.size,isBinary:false}}}};}
const page={repository:"owned/repo",...query,files:[{filename:query.filename,previousFilename:"old file.ts",status:"renamed",blobOid:next.sha}]};
describe("immutable PR full context",()=>{
 beforeEach(()=>{vi.clearAllMocks();ports.files.mockResolvedValue(page);ports.detail.mockResolvedValue(page);ports.resolve.mockResolvedValue({executable:"owned-gh",prefix:[]});ports.execute.mockImplementation(async(_cmd,args:string[])=>({stdout:JSON.stringify(args.includes("{oid:.merge_base_commit.sha}")?{oid:"c".repeat(40)}:args.includes(`expression=${query.headOid}:${query.filename}`)?metadata(next):args.some(arg=>arg.startsWith("expression="))?metadata(old):args.includes(`repos/owned/repo/git/blobs/${next.sha}`)?next:old)}));});
 it("reads rename sides at merge base and head, verifies bytes, and keeps paths literal",async()=>{expect(await projectPullRequestContents("owned-root",query)).toMatchObject({mergeBaseOid:"c".repeat(40),oldFile:{name:"old file.ts",contents:"before\n"},newFile:{name:query.filename,contents:"after\n"}});expect(ports.execute).toHaveBeenCalledWith("owned-gh",expect.arrayContaining([`expression=${query.headOid}:${query.filename}`]),expect.objectContaining({timeout:20000,maxBuffer:2097152,windowsHide:true}));});
 it("rejects filenames absent from the confirmed page before reading context",async()=>{await expect(projectPullRequestContents("root",{...query,filename:"other"})).rejects.toThrow("confirmed");expect(ports.execute).not.toHaveBeenCalled();});
 it.each([null,{...query,page:31},{...query,filename:"bad\0name"}])("rejects invalid selectors",async value=>{await expect(projectPullRequestContents("root",value)).rejects.toThrow("Invalid");expect(ports.files).not.toHaveBeenCalled();});
 it("does not interpret an unreadable side as an added or removed file",async()=>{ports.execute.mockResolvedValue({stdout:"null"});await expect(projectPullRequestContents("root",query)).rejects.toThrow("merge base");});
 it("rejects a branch update during the immutable read",async()=>{ports.detail.mockResolvedValue({...page,headOid:"d".repeat(40)});await expect(projectPullRequestContents("root",query)).rejects.toThrow("changed while context");});
 it.each(["added","removed"])("loads only the existing %s side",async status=>{ports.files.mockResolvedValue({...page,files:[{...page.files[0],status,blobOid:status==="removed"?old.sha:next.sha}]});const result=await projectPullRequestContents("root",query);expect(status==="added"?result.oldFile:result.newFile).toBeNull();expect(ports.execute).toHaveBeenCalledTimes(3);});
 it("rejects content whose Git identity fails",()=>{expect(()=>decodePullRequestBlob({...next,content:old.content},next.sha,next.size)).toThrow("match the reviewed blob");});
 it("preserves Unicode and BOM bytes without replacement",()=>{const value=blob("\ufeff世界\n");expect(decodePullRequestBlob(value,value.sha,value.size)).toBe("\ufeff世界\n");});
 it.each([{...next,encoding:"utf-8"},{...next,content:"???"},{...next,size:0}])("rejects malformed blob responses",value=>{expect(()=>decodePullRequestBlob(value,next.sha,next.size)).toThrow();});
 it("rejects binary text and excessive line counts",()=>{for(const text of ["a\0b","\n".repeat(10000)]){const value=blob(text);expect(()=>decodePullRequestBlob(value,value.sha,value.size)).toThrow();}});
 it.each([{object:null},{object:{__typename:"Tree"}},{object:{__typename:"Blob",oid:next.sha,byteSize:1048577,isBinary:false}},{object:{__typename:"Blob",oid:next.sha,byteSize:next.size,isBinary:true}},{object:{__typename:"Blob",oid:"invalid",byteSize:1,isBinary:false}}])("rejects missing, unsupported or bounded metadata before fetching bytes",async repository=>{ports.execute.mockImplementation(async(_cmd,args:string[])=>({stdout:JSON.stringify(args.includes("{oid:.merge_base_commit.sha}")?{oid:"c".repeat(40)}:{data:{repository}})}));await expect(projectPullRequestContents("root",query)).rejects.toThrow();expect(ports.execute).toHaveBeenCalledTimes(2);});
 it("rejects a head blob identity different from the file page",async()=>{ports.files.mockResolvedValue({...page,files:[{...page.files[0],status:"added",blobOid:old.sha}]});await expect(projectPullRequestContents("root",query)).rejects.toThrow("does not match");expect(ports.execute).toHaveBeenCalledTimes(2);});
 it("rejects partial GraphQL errors even with a readable blob",async()=>{ports.execute.mockImplementation(async(_cmd,args:string[])=>({stdout:JSON.stringify(args.includes("{oid:.merge_base_commit.sha}")?{oid:"c".repeat(40)}:{...metadata(old),errors:[{message:"unreadable"}]})}));await expect(projectPullRequestContents("root",query)).rejects.toThrow("could not confirm");});
 it.each([-1,1048577,1.5])("rejects invalid byte sizes: %s",size=>{expect(()=>decodePullRequestBlob(next,next.sha,size)).toThrow();});
 it("rejects non-UTF-8 bytes despite their valid blob identity",()=>{const bytes=Buffer.from([0xff]);const oid=createHash("sha1").update("blob 1\0").update(bytes).digest("hex");expect(()=>decodePullRequestBlob({sha:oid,size:1,encoding:"base64",content:bytes.toString("base64")},oid,1)).toThrow("UTF-8");});
 it("keeps CLI failures private",async()=>{ports.execute.mockRejectedValue(Error("private token"));await expect(projectPullRequestContents("root",query)).rejects.toThrow("Check GitHub CLI");});
});
