import { useEffect, useState } from "react";
import type { Mission, MissionCommand, MissionSchedule } from "../../shared/missions";
import { missionScheduleLabel } from "../../shared/missions";
import { emptyWorkspace } from "../../shared/workspace";

export function Missions({ onOpenTask, onNewTask }: { onOpenTask: (id: string) => void; onNewTask: () => void }) {
	const [workspace, setWorkspace] = useState(emptyWorkspace); const [missions, setMissions] = useState<Mission[]>([]);
	const [editing, setEditing] = useState<string>(); const [title, setTitle] = useState(""); const [prompt, setPrompt] = useState(""); const [templateTaskId, setTemplateTaskId] = useState("");
	const [scheduleType, setScheduleType] = useState<MissionSchedule["type"]>("interval"); const [minutes, setMinutes] = useState(60); const [time, setTime] = useState("09:00"); const [weekdays, setWeekdays] = useState<number[]>([]);
	const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const api = window.phaseoDesktop?.workspace;
	useEffect(() => { if (!api) return; let active = true; void Promise.all([api.get(), api.missions()]).then(([state, values]) => { if (active) { setWorkspace(state); setMissions(values); } }, reason => { if (active) setError(String(reason)); }); const unsubscribeWorkspace = api.onChange(setWorkspace); const unsubscribeMissions = api.onMissionsChange(setMissions); return () => { active = false; unsubscribeWorkspace(); unsubscribeMissions(); }; }, [api]);
	async function command(value: MissionCommand) { if (!api) return; setBusy(true); setError(""); try { setMissions(await api.mission(value)); return true; } catch (reason) { setError(String(reason)); return false; } finally { setBusy(false); } }
	function edit(mission: Mission) { setEditing(mission.id); setTitle(mission.title); setPrompt(mission.prompt); setTemplateTaskId(mission.templateTaskId); setScheduleType(mission.schedule.type); if (mission.schedule.type === "interval") setMinutes(mission.schedule.minutes); else { setTime(mission.schedule.time); setWeekdays(mission.schedule.weekdays); } }
	function reset() { setEditing(undefined); setTitle(""); setPrompt(""); setTemplateTaskId(""); }
	const templates = workspace.tasks.filter(task => !task.archived && (!task.projectId || workspace.projects.some(project => project.id === task.projectId && !project.worktree?.removedAt)));
	return <div className="page workspace-home"><section className="page-heading"><div><h1>Missions</h1><p>Runs while Phaseo is open. Missed runs are skipped.</p></div></section>{error && <p className="task-error" role="alert">{error}</p>}
		<section className="panel mission-editor"><div className="panel-heading"><h2>{editing ? "Edit mission" : "New mission"}</h2></div>{!templates.length ? <div className="empty-state compact-empty"><p>Create a task to choose its account, harness, model and project.</p><button type="button" className="secondary-button" onClick={onNewTask}>New task</button></div> : <form className="task-setup mission-form" aria-label="Mission configuration" onSubmit={event => { event.preventDefault(); void command({ type: "save", ...(editing ? { id: editing } : {}), title, prompt, templateTaskId, schedule: scheduleType === "interval" ? { type: "interval", minutes } : { type: "daily", time, weekdays } }).then(saved => { if (saved) reset(); }); }}>
			<label>Title<input aria-label="Mission title" required maxLength={200} value={title} onChange={event => setTitle(event.target.value)} /></label><label>Task configuration<select aria-label="Mission task configuration" required value={templateTaskId} onChange={event => setTemplateTaskId(event.target.value)}><option value="">Choose a task</option>{templates.map(task => <option key={task.id} value={task.id}>{task.title} · {task.harness} · {task.mode}</option>)}</select></label><p className="task-muted">Each run starts a fresh task with this task's current account, harness, model and project.</p>
			<label>Instructions<textarea aria-label="Mission instructions" required maxLength={100000} rows={5} value={prompt} onChange={event => setPrompt(event.target.value)} /></label><label>Schedule<select aria-label="Mission schedule" value={scheduleType} onChange={event => setScheduleType(event.target.value as MissionSchedule["type"])}><option value="interval">Interval</option><option value="daily">Local time</option></select></label>
			{scheduleType === "interval" ? <label>Every (minutes)<input aria-label="Mission interval" type="number" min={1} max={10080} required value={minutes} onChange={event => setMinutes(Number(event.target.value))} /></label> : <><label>Time<input aria-label="Mission local time" type="time" required value={time} onChange={event => setTime(event.target.value)} /></label><fieldset><legend>Days (none means daily)</legend>{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day, index) => <label key={day}><input type="checkbox" checked={weekdays.includes(index)} onChange={event => setWeekdays(values => event.target.checked ? [...values, index] : values.filter(value => value !== index))} />{day}</label>)}</fieldset><p className="task-muted">Uses this computer's timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}.</p></>}
			<button type="submit" className="primary-button" disabled={busy}>{editing ? "Save mission" : "Create paused mission"}</button>{editing && <button type="button" disabled={busy} onClick={reset}>Cancel</button>}
		</form>}</section>
		<section className="panel mission-list"><div className="panel-heading"><h2>Recurring work</h2></div><div className="attention-list">{missions.length ? missions.map(mission => <article className="attention-item" key={mission.id}><div><h3>{mission.title}</h3><p>{missionScheduleLabel(mission.schedule)} · {mission.enabled ? "Enabled" : "Paused"} · {mission.lastStatus} · {mission.runCount} runs</p>{mission.nextRunAt && <p>Next: {new Date(mission.nextRunAt).toLocaleString()}</p>}{mission.error && <p className="task-error">{mission.error}</p>}<div className="task-controls"><button type="button" disabled={busy} onClick={() => void command({ type: "enable", id: mission.id, enabled: !mission.enabled })}>{mission.enabled ? "Pause" : "Enable"}</button><button type="button" disabled={busy || mission.lastStatus === "running"} onClick={() => void command({ type: "run", id: mission.id })}>Run now</button><button type="button" disabled={busy || mission.lastStatus === "running"} onClick={() => edit(mission)}>Edit</button><button type="button" disabled={busy || mission.lastStatus === "running"} onClick={() => void command({ type: "delete", id: mission.id })}>Delete</button>{mission.lastTaskId && <button type="button" onClick={() => onOpenTask(mission.lastTaskId!)}>Latest run</button>}</div><details><summary>Run history</summary>{workspace.tasks.filter(task => task.missionId === mission.id).map(task => <button className="home-task-row" key={task.id} type="button" onClick={() => onOpenTask(task.id)}><strong>{new Date(task.createdAt).toLocaleString()}</strong><small>{task.status}</small></button>)}</details></div></article>) : <p className="task-muted">No missions yet.</p>}</div></section>
	</div>;
}
