import { useEffect, useRef, useState } from "react";
import type { PullRequestDetails } from "../../shared/pullRequests";
import type { PullRequestFilesPage } from "../../shared/pullRequestFiles";
import { DiffView } from "../components/DiffView";
import { pullRequestPatch } from "../lib/pullRequestPatch";
import { pullRequestPatchCoversChanges } from "../lib/pullRequestPatchCoverage";
export function PullRequestFiles({ projectId, request }: { projectId: string; request: PullRequestDetails }) {
 const api=window.phaseoDesktop?.workspace;const [page,setPage]=useState(1),[attempt,setAttempt]=useState(0);const [result,setResult]=useState<PullRequestFilesPage>();const [loading,setLoading]=useState(true),[error,setError]=useState("");const [filename,setFilename]=useState("");const [layout,setLayout]=useState<"unified"|"split">("unified");const pending=useRef(true);const root=useRef<HTMLElement>(null);
 useEffect(()=>{let active=true;pending.current=true;setLoading(true);setError("");if(!api){pending.current=false;setLoading(false);setError("Open the desktop app to load changed files.");return;}void api.pullRequestFiles(projectId,{number:request.number,page,headOid:request.headOid,baseOid:request.baseOid}).then(value=>{if(active){setResult(value);setFilename(current=>value.files.some(file=>file.filename===current)?current:value.files[0]?.filename??"");}},reason=>{if(active)setError((reason instanceof Error?reason.message:String(reason)).replace(/^Error invoking remote method '[^']+': (?:Error: )?/,""));}).finally(()=>{if(active){pending.current=false;setLoading(false);}});return()=>{active=false;};},[api,projectId,request.number,request.headOid,request.baseOid,page,attempt]);
 useEffect(()=>{if(!result||loading)return;const frame=requestAnimationFrame(()=>root.current?.scrollIntoView({block:"start"}));return()=>cancelAnimationFrame(frame);},[result,loading]);
 function load(next:number){if(pending.current)return;pending.current=true;setLoading(true);setPage(next);setAttempt(value=>value+1);}
 const file=result?.files.find(value=>value.filename===filename);const patch=file?pullRequestPatch(file):undefined;
 return <section ref={root} className="proposal-files" aria-label="Changed files" aria-busy={loading}><div className="proposal-detail-actions"><h3>Changed files</h3><button type="button" disabled={loading||!api} onClick={()=>load(page)}>{loading?"Loading…":error?"Retry files":"Refresh files"}</button></div><p className="proposal-file-revision">Reviewing commit {request.headOid.slice(0,12)}</p>{loading&&<p role="status">Loading changed files…</p>}{error&&<p role="alert" className="proposal-error">{error}</p>}{result&&<><nav className="proposal-pagination" aria-label="Changed-file pages"><span>Page {result.page} · {result.files.length} of {result.total} files</span><button type="button" disabled={loading||result.page<=1} onClick={()=>load(result.page-1)}>Previous files</button><button type="button" disabled={loading||!result.hasNext} onClick={()=>load(result.page+1)}>Next files</button></nav>{result.limitReached&&<p role="status">GitHub exposes at most 3,000 files through this API. Additional files are unavailable here.</p>}<div className="proposal-file-list" aria-label="Changed-file list">{result.files.map(value=><button type="button" key={value.filename} aria-pressed={filename===value.filename} onClick={()=>setFilename(value.filename)}><strong>{value.filename}</strong><span>{value.status} · +{value.additions} −{value.deletions}</span>{value.previousFilename&&<small>From {value.previousFilename}</small>}</button>)}</div>{!result.files.length&&<p>No changed files.</p>}{file&&<section className="proposal-file-preview" aria-label="GitHub patch preview"><div className="proposal-detail-actions"><h3>{file.filename}</h3>{patch&&<select aria-label="PR diff layout" value={layout} onChange={event=>setLayout(event.target.value as "unified"|"split")}><option value="unified">Unified</option><option value="split">Side by side</option></select>}</div><p>GitHub patch preview; unchanged context and full file contents are not loaded.</p>{patch&&!pullRequestPatchCoversChanges(file)&&<p role="status">This preview does not cover all reported changes. Review the complete diff on GitHub.</p>}{patch?<DiffView patch={patch} copyText={file.patch} layout={layout}/>:<p>{file.preview==="too-large"?"Patch exceeds the preview limit.":"GitHub did not provide a text patch for this file."}</p>}</section>}</>}</section>;
}
