import { useEffect, useRef, useState } from "react";
import type { PullRequestFile, PullRequestFilesPage } from "../../shared/pullRequestFiles";
import type { PullRequestContents } from "../../shared/pullRequestContents";
import { DiffView } from "../components/DiffView";
import { pullRequestPatch } from "../lib/pullRequestPatch";
import { pullRequestPatchCoversChanges } from "../lib/pullRequestPatchCoverage";
export function PullRequestFilePreview({projectId,page,file}:{projectId:string;page:PullRequestFilesPage;file:PullRequestFile}) {
 const [layout,setLayout]=useState<"unified"|"split">("unified"),[contents,setContents]=useState<PullRequestContents>(),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const active=useRef(true),pending=useRef(false);useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 const patch=pullRequestPatch(file);
 async function load(){const api=window.phaseoDesktop?.workspace;if(!api||pending.current)return;pending.current=true;setLoading(true);setError("");try{const value=await api.pullRequestContents(projectId,{number:page.number,page:page.page,headOid:page.headOid,baseOid:page.baseOid,filename:file.filename});if(active.current)setContents(value);}catch(reason){if(active.current)setError((reason instanceof Error?reason.message:String(reason)).replace(/^Error invoking remote method '[^']+': (?:Error: )?/,""));}finally{if(active.current){pending.current=false;setLoading(false);}}}
 return <section className="proposal-file-preview" aria-label={contents?"Full PR file diff":"GitHub patch preview"}><div className="proposal-detail-actions"><h3>{file.filename}</h3>{(patch||contents)&&<select aria-label="PR diff layout" value={layout} onChange={event=>setLayout(event.target.value as "unified"|"split")}><option value="unified">Unified</option><option value="split">Side by side</option></select>}</div>{contents?<p>Full text · merge base {contents.mergeBaseOid.slice(0,12)} → {contents.headOid.slice(0,12)}</p>:<><p>GitHub patch preview; unchanged context and full file contents are not loaded.</p><button type="button" disabled={loading||!window.phaseoDesktop?.workspace} onClick={()=>void load()}>{loading?"Loading full context…":error?"Retry full context":"Load full context"}</button></>}{error&&<p role="alert">{error}</p>}{!contents&&patch&&!pullRequestPatchCoversChanges(file)&&<p role="status">This preview does not cover all reported changes. Review the complete diff on GitHub.</p>}{contents||patch?<DiffView patch={patch??""} contents={contents} copyText={contents?(contents.newFile?.contents??contents.oldFile?.contents??""):file.patch} layout={layout}/>:<p>{file.preview==="too-large"?"Patch exceeds the preview limit.":"GitHub did not provide a text patch for this file."}</p>}</section>;
}
