/**
 * Organisation identifier.
 */
export type OrganisationId =
  | "ai21"
  | "aion-labs"
  | "allenai"
  | "amazon"
  | "anthropic"
  | "arcee-ai"
  | "baidu"
  | "black-forest-labs"
  | "bytedance"
  | "cohere"
  | "cursor"
  | "deepseek"
  | "eleven-labs"
  | "essential-ai"
  | "google"
  | "ibm"
  | "inception"
  | "inclusionai"
  | "lg"
  | "liquid-ai"
  | "meta"
  | "microsoft"
  | "minimax"
  | "mistral"
  | "moonshot-ai"
  | "naver-hyperclova"
  | "nous"
  | "nvidia"
  | "openai"
  | "perplexity"
  | "prime-intellect"
  | "qwen"
  | "relace"
  | "sourceful"
  | "stepfun"
  | "suno"
  | "upstage"
  | "vercel"
  | "voyage"
  | "x-ai"
  | "xiaomi"
  | "z-ai";
