CREATE VIEW "private"."v2_rpc_gateway_requests_compat" WITH (security_invoker=true) AS  SELECT fact.request_event_id AS id,
    fact.occurred_at AS created_at,
    fact.workspace_id AS team_id,
    fact.workspace_id,
    fact.request_id,
    fact.app_id,
    fact.endpoint,
    COALESCE(fact.routed_model_slug, fact.requested_model_slug, fact.requested_model_input) AS model_id,
    fact.requested_model_input AS requested_model_id,
    fact.routed_model_slug AS routed_model_id,
    COALESCE(fact.routed_model_slug, fact.requested_model_slug) AS canonical_model_id,
    route.provider_slug AS provider,
    fact.native_response_id,
    fact.stream,
    fact.byok,
    fact.status_code,
    fact.success,
    fact.error_code,
    (fact.safe_metadata ->> 'error_message'::text) AS error_message,
    fact.latency_ms,
    fact.generation_ms,
    fact.gateway_total_ms AS e2e_latency_ms,
    COALESCE(usage.payload, '{}'::jsonb) AS usage,
    (COALESCE(usage.total_tokens, (0)::numeric))::bigint AS usage_total_tokens,
    (COALESCE(((usage.payload ->> 'input_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_input_tokens,
    (COALESCE(((usage.payload ->> 'output_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_output_tokens,
    (COALESCE(((usage.payload ->> 'reasoning_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_reasoning_tokens,
    (COALESCE(((usage.payload ->> 'input_text_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_input_text_tokens,
    (COALESCE(((usage.payload ->> 'output_text_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_output_text_tokens,
    (COALESCE(((usage.payload ->> 'input_image_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_input_image_tokens,
    (COALESCE(((usage.payload ->> 'output_image_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_output_image_tokens,
    (COALESCE(((usage.payload ->> 'input_audio_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_input_audio_tokens,
    (COALESCE(((usage.payload ->> 'output_audio_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_output_audio_tokens,
    (COALESCE(((usage.payload ->> 'input_video_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_input_video_tokens,
    (COALESCE(((usage.payload ->> 'output_video_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_output_video_tokens,
    (COALESCE(((usage.payload ->> 'image_inputs'::text))::numeric, (0)::numeric))::bigint AS usage_image_inputs,
    (COALESCE(((usage.payload ->> 'image_outputs'::text))::numeric, (0)::numeric))::bigint AS usage_image_outputs,
    (COALESCE(((usage.payload ->> 'audio_inputs'::text))::numeric, (0)::numeric))::bigint AS usage_audio_inputs,
    (COALESCE(((usage.payload ->> 'audio_outputs'::text))::numeric, (0)::numeric))::bigint AS usage_audio_outputs,
    (COALESCE(((usage.payload ->> 'video_inputs'::text))::numeric, (0)::numeric))::bigint AS usage_video_inputs,
    (COALESCE(((usage.payload ->> 'video_outputs'::text))::numeric, (0)::numeric))::bigint AS usage_video_outputs,
    (COALESCE(((usage.payload ->> 'cached_read_tokens'::text))::numeric, ((usage.payload ->> 'cached_input_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_read_tokens,
    (COALESCE(((usage.payload ->> 'cached_write_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_write_tokens,
    (COALESCE(((usage.payload ->> 'cached_read_text_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_read_text_tokens,
    (COALESCE(((usage.payload ->> 'cached_write_text_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_write_text_tokens,
    (COALESCE(((usage.payload ->> 'cached_write_text_tokens_5m'::text))::numeric, (0)::numeric))::bigint AS usage_cached_write_text_tokens_5m,
    (COALESCE(((usage.payload ->> 'cached_write_text_tokens_1h'::text))::numeric, (0)::numeric))::bigint AS usage_cached_write_text_tokens_1h,
    (COALESCE(((usage.payload ->> 'cached_read_image_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_read_image_tokens,
    (COALESCE(((usage.payload ->> 'cached_write_image_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_write_image_tokens,
    (COALESCE(((usage.payload ->> 'cached_read_audio_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_read_audio_tokens,
    (COALESCE(((usage.payload ->> 'cached_write_audio_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_write_audio_tokens,
    (COALESCE(((usage.payload ->> 'cached_read_video_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_read_video_tokens,
    (COALESCE(((usage.payload ->> 'cached_write_video_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_cached_write_video_tokens,
    (COALESCE(((usage.payload ->> 'input_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_input_quad_tokens,
    (COALESCE(((usage.payload ->> 'output_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_output_quad_tokens,
    (COALESCE(((usage.payload ->> 'total_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_total_quad_tokens,
    (COALESCE(((usage.payload ->> 'text_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_text_quad_tokens,
    (COALESCE(((usage.payload ->> 'rerank_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_rerank_quad_tokens,
    (COALESCE(((usage.payload ->> 'embedding_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_embedding_quad_tokens,
    (COALESCE(((usage.payload ->> 'moderation_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_moderation_quad_tokens,
    (COALESCE(((usage.payload ->> 'ocr_quad_tokens'::text))::numeric, (0)::numeric))::bigint AS usage_ocr_quad_tokens,
    COALESCE(((usage.payload ->> 'image_megapixels'::text))::numeric, (0)::numeric) AS usage_image_megapixels,
    COALESCE(((usage.payload ->> 'audio_seconds'::text))::numeric, (0)::numeric) AS usage_audio_seconds,
    COALESCE(((usage.payload ->> 'video_pixel_seconds'::text))::numeric, (0)::numeric) AS usage_video_pixel_seconds,
    (COALESCE(((usage.payload ->> 'input_characters'::text))::numeric, (0)::numeric))::bigint AS usage_input_characters,
    (COALESCE(((usage.payload ->> 'output_characters'::text))::numeric, (0)::numeric))::bigint AS usage_output_characters,
    (COALESCE(((usage.payload ->> 'total_characters'::text))::numeric, (0)::numeric))::bigint AS usage_total_characters,
    fact.occurred_at AS usage_normalized_at,
    fact.cost_nanos,
    fact.currency,
    COALESCE(pricing.payload, '[]'::jsonb) AS pricing_lines,
    fact.key_id,
    fact.throughput,
    COALESCE(fact.cloudflare_colo, fact.region) AS location,
    fact.auth_method,
    (fact.safe_metadata ->> 'oauth_client_id'::text) AS oauth_client_id,
    (NULLIF((fact.safe_metadata ->> 'oauth_user_id'::text), ''::text))::uuid AS oauth_user_id,
    fact.end_user_id,
    fact.session_id,
    (fact.safe_metadata -> 'trace_data'::text) AS trace_data,
    COALESCE(attempts.payload, '[]'::jsonb) AS provider_attempts,
    fact.stop_reason,
    fact.stop_reason AS finish_reason,
    fact.tool_call_count,
    fact.structured_output_attempted,
    fact.structured_output_succeeded,
    fact.cloudflare_colo
   FROM ((((public.v2_request_facts fact
     LEFT JOIN public.v2_model_provider_routes route ON ((route.provider_model_id = fact.provider_model_id)))
     LEFT JOIN LATERAL ( SELECT jsonb_object_agg(grouped_usage.meter_key, grouped_usage.quantity) AS payload,
            sum(grouped_usage.quantity) FILTER (WHERE (grouped_usage.meter_key = ANY (ARRAY['input_tokens'::text, 'output_tokens'::text]))) AS total_tokens
           FROM ( SELECT request_usage.meter_key,
                    sum(request_usage.quantity) AS quantity
                   FROM public.v2_request_usage request_usage
                  WHERE (request_usage.request_event_id = fact.request_event_id)
                  GROUP BY request_usage.meter_key) grouped_usage) usage ON (true))
     LEFT JOIN LATERAL ( SELECT jsonb_agg(jsonb_build_object('sku_id', line.sku_id, 'sku_meter_id', line.sku_meter_id, 'meter', line.meter_key, 'quantity', line.quantity, 'unit', line.unit, 'unit_price_nanos', line.unit_price_nanos, 'cost_nanos', line.charged_nanos) ORDER BY line.created_at, line.pricing_line_id) AS payload
           FROM public.v2_request_pricing_lines line
          WHERE (line.request_event_id = fact.request_event_id)) pricing ON (true))
     LEFT JOIN LATERAL ( SELECT jsonb_agg(jsonb_build_object('attempt', attempt.attempt_number, 'provider_model_id', attempt.provider_model_id, 'provider', attempt_route.provider_slug, 'started_at', attempt.started_at, 'completed_at', attempt.completed_at, 'status_code', attempt.status_code, 'success', attempt.success, 'error_code', attempt.error_code, 'failure_class', attempt.failure_class, 'latency_ms', attempt.latency_ms) ORDER BY attempt.attempt_number) AS payload
           FROM (public.v2_request_attempts attempt
             LEFT JOIN public.v2_model_provider_routes attempt_route ON ((attempt_route.provider_model_id = attempt.provider_model_id)))
          WHERE (attempt.request_event_id = fact.request_event_id)) attempts ON (true));

GRANT SELECT ON TABLE "private"."v2_rpc_gateway_requests_compat" TO "service_role";
