CREATE VIEW "private"."v2_rpc_models_compat" WITH (security_invoker=true) AS  SELECT model_slug,
    lab_slug,
    name,
    description,
    status,
    hidden,
    input_modalities,
    output_modalities,
    family_slug,
    announced_at,
    released_at,
    deprecated_at,
    retired_at,
    metadata,
    created_at,
    updated_at,
    license,
    license_url,
    previous_model_slug,
    removal_date,
    replacement_model_slug,
    variant_kind,
    base_model_slug,
    model_slug AS model_id,
    model_slug AS api_model_id,
    lab_slug AS organisation_id,
    previous_model_slug AS previous_model_id,
    announced_at AS announcement_date,
    released_at AS release_date,
    deprecated_at AS deprecation_date,
    retired_at AS retirement_date,
    array_to_string(input_modalities, ','::text) AS input_types,
    array_to_string(output_modalities, ','::text) AS output_types,
    family_slug AS family_id,
    (metadata -> 'timeline'::text) AS timeline
   FROM public.v2_models model;

GRANT SELECT ON TABLE "private"."v2_rpc_models_compat" TO "service_role";
