CREATE VIEW "private"."v2_rpc_providers_compat" AS  SELECT provider_slug,
    lab_slug,
    name,
    status,
    routing_enabled,
    routable,
    country_code,
    base_url,
    metadata,
    created_at,
    updated_at,
    provider_family_slug,
    offer_scope,
    offer_label,
    residency_mode,
    default_execution_regions,
    default_data_regions,
    zero_data_retention,
    prompt_training_policy,
    data_policy_tier,
    data_policy_confidence,
    data_policy_contract_mode,
    data_policy_variant,
    stream_cancellation_support,
    stream_cancellation_stops_provider_billing,
    stream_cancellation_usage_recovery,
    stream_cancellation_evidence_kind,
    stream_cancellation_source_url,
    stream_cancellation_verified_at,
    provider_slug AS api_provider_id,
    name AS api_provider_name,
    lab_slug AS organisation_id,
        CASE
            WHEN routing_enabled THEN 'active'::text
            ELSE 'disabled'::text
        END AS routing_status,
    (metadata ->> 'description'::text) AS description,
    COALESCE((metadata ->> 'link'::text), base_url) AS link,
    (metadata ->> 'colour'::text) AS colour,
    (metadata ->> 'pricing_source_url'::text) AS pricing_source_url,
    (metadata ->> 'privacy_policy_url'::text) AS privacy_policy_url,
    (metadata ->> 'terms_of_service_url'::text) AS terms_of_service_url
   FROM public.v2_providers provider;

GRANT SELECT ON TABLE "private"."v2_rpc_providers_compat" TO "service_role";
