CREATE VIEW "private"."v2_rpc_routes_compat" WITH (security_invoker=true) AS  SELECT provider_model_id,
    model_slug,
    provider_slug,
    provider_model_slug,
    status,
    routing_enabled,
    input_modalities,
    output_modalities,
    regions,
    context_length,
    max_output_tokens,
    effective_from,
    effective_to,
    metadata,
    created_at,
    updated_at,
    provider_model_id AS provider_api_model_id,
    provider_slug AS provider_id,
    model_slug AS api_model_id,
    model_slug AS model_id,
    model_slug AS internal_model_id,
    routing_enabled AS is_active_gateway,
    status AS routing_status,
    (metadata ->> 'quantization_scheme'::text) AS quantization_scheme,
    (metadata ->> 'prompt_training_policy_override'::text) AS prompt_training_policy_override,
    (metadata ->> 'prompt_training_override_notes'::text) AS prompt_training_override_notes,
    (metadata ->> 'prompt_training_override_source_url'::text) AS prompt_training_override_source_url
   FROM public.v2_model_provider_routes route;

GRANT SELECT ON TABLE "private"."v2_rpc_routes_compat" TO "service_role";
