import { describe, expect, it } from "vitest";
import { browserViewportToRestore, browserTabs, updateBrowserTab, openBrowserTab } from "./browserTabs";
describe("chat browser tabs", () => {
 it("restores known device modes and repairs invalid saved modes", () => {const group=browserTabs({tabs:[{id:"chat",viewport:"phone-landscape"},{id:"chat:other",viewport:"bad"}]},"chat");expect(group.tabs.map(tab=>tab.viewport)).toEqual(["phone-landscape","desktop"]);});
 it("routes foreground and background requests without altering the source tab", () => {const group=browserTabs(null,"chat");const request={sourceId:"chat",url:"https://example.com/page",background:false};const foreground=openBrowserTab(group,request,"chat:new");expect(foreground.active).toBe("chat:new");expect(foreground.tabs[0]).toEqual(group.tabs[0]);expect(foreground.tabs[1].url).toBe(request.url);expect(openBrowserTab(group,{...request,background:true},"chat:new").active).toBe("chat");});
 it("ignores requests belonging to another chat", () => {const group=browserTabs(null,"chat");expect(openBrowserTab(group,{sourceId:"other",url:"https://example.com",background:false},"chat:new")).toBe(group);});
 it("rejects unsafe popup targets and enforces the tab bound", () => {const group=browserTabs(null,"chat");expect(()=>openBrowserTab(group,{sourceId:"chat",url:"file:///private",background:false},"chat:new")).toThrow();const full=browserTabs({active:"chat:0",tabs:Array.from({length:20},(_,i)=>({id:"chat:"+i,url:"",title:"Tab"}))},"chat");expect(()=>openBrowserTab(full,{sourceId:"chat:0",url:"https://example.com",background:false},"chat:new")).toThrow("Close a browser tab");});
 it.each([null, 1, [], {}, {tabs:null}])("recovers malformed state %j", value => expect(browserTabs(value,"chat")).toEqual({active:"chat",tabs:[{id:"chat",title:"New tab",url:"",viewport:"desktop"}]}));
 it("rejects foreign and duplicate IDs, unsafe saved URLs and missing active tabs", () => {
  expect(browserTabs({active:"missing",tabs:[{id:"other",url:"https://example.com"},{id:"chat",url:"file:///private",title:"Saved"},{id:"chat",url:"https://example.com"},{id:"chat:second",url:"https://example.com",title:"x".repeat(200)}]},"chat")).toEqual({active:"chat",tabs:[{id:"chat",url:"",title:"Saved",viewport:"desktop"},{id:"chat:second",url:"https://example.com/",title:"x".repeat(120),viewport:"desktop"}]});
 });
 it("bounds persisted tabs and preserves valid active selection", () => {const tabs=Array.from({length:30},(_,index)=>({id:"chat:"+index,title:"Tab",url:""}));const group=browserTabs({active:"chat:5",tabs},"chat");expect(group.tabs).toHaveLength(20);expect(group.active).toBe("chat:5");});
 it("retains the last confirmed address while a native load has no committed URL", () => {const group=browserTabs({active:"chat",tabs:[{id:"chat",title:"Confirmed",url:"https://example.com/"}]},"chat");expect(updateBrowserTab(group,{id:"chat",title:"",url:"",loading:true,canGoBack:false,canGoForward:false,devToolsOpen:false,configured:true,viewport:"desktop"}).tabs[0]).toEqual(group.tabs[0]);});
 it("updates the native source tab without changing selection or another tab", () => {const group=browserTabs({active:"chat:second",tabs:[{id:"chat",url:"",title:"First"},{id:"chat:second",url:"",title:"Second"}]},"chat");const next=updateBrowserTab(group,{id:"chat",url:"https://example.com/",title:"Native",loading:false,canGoBack:false,canGoForward:false,devToolsOpen: false, configured: true, viewport:"desktop"});expect(next.active).toBe("chat:second");expect(next.tabs[0]).toEqual({id:"chat",title:"Native",url:"https://example.com/",viewport:"desktop"});expect(next.tabs[1]).toEqual(group.tabs[1]);expect(group.tabs[0].title).toBe("First");});
});

it.each([[true,"tablet-landscape","tablet","tablet-landscape"],[true,"desktop","phone","desktop"],[true,"phone-landscape","phone","phone-landscape"],[false,"desktop","tablet-landscape","tablet-landscape"]] as const)("restores viewport from authoritative native or fresh saved state",(configured,viewport,saved,expected)=>{expect(browserViewportToRestore({configured,viewport},saved)).toBe(expected);});
