import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { watchLiveRefresh } from "./liveRefresh";
let page: EventTarget & { visibilityState: string }, surface: EventTarget;
beforeEach(() => { vi.useFakeTimers(); vi.setSystemTime(0); page = Object.assign(new EventTarget(), { visibilityState: "visible" }); surface = new EventTarget(); vi.stubGlobal("document", page); vi.stubGlobal("window", surface); });
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });
describe("foreground live refresh", () => {
 it.each([45000,60000])("does not duplicate mount reads and polls at %i", interval => { const read=vi.fn(()=>true),stop=watchLiveRefresh(read,interval); expect(read).not.toHaveBeenCalled(); vi.advanceTimersByTime(interval-1); expect(read).not.toHaveBeenCalled(); vi.advanceTimersByTime(1); expect(read).toHaveBeenCalledTimes(1); stop(); });
 it("deduplicates focus and visibility arrivals within ten seconds", () => { const read=vi.fn(()=>true),stop=watchLiveRefresh(read,45000); vi.advanceTimersByTime(10000); surface.dispatchEvent(new Event("focus")); page.dispatchEvent(new Event("visibilitychange")); expect(read).toHaveBeenCalledTimes(1); vi.advanceTimersByTime(9999); surface.dispatchEvent(new Event("focus")); expect(read).toHaveBeenCalledTimes(1); stop(); });
 it("stops hidden polling and refreshes once on return", () => { const read=vi.fn(()=>true),stop=watchLiveRefresh(read,45000); page.visibilityState="hidden"; page.dispatchEvent(new Event("visibilitychange")); vi.advanceTimersByTime(300000); expect(read).not.toHaveBeenCalled(); page.visibilityState="visible"; page.dispatchEvent(new Event("visibilitychange")); surface.dispatchEvent(new Event("focus")); expect(read).toHaveBeenCalledTimes(1); stop(); });
 it("pauses after six idle minutes and resumes on interaction", () => { const read=vi.fn(()=>true),stop=watchLiveRefresh(read,45000); vi.advanceTimersByTime(360000); const count=read.mock.calls.length; vi.advanceTimersByTime(360000); expect(read).toHaveBeenCalledTimes(count); surface.dispatchEvent(new Event("keydown")); expect(read).toHaveBeenCalledTimes(count+1); vi.advanceTimersByTime(45000); expect(read).toHaveBeenCalledTimes(count+2); stop(); });
 it("does not turn every interaction into a read", () => { const read=vi.fn(()=>true),stop=watchLiveRefresh(read,45000); vi.advanceTimersByTime(10000); for(const name of ["pointerdown","pointermove","keydown","wheel"])surface.dispatchEvent(new Event(name)); expect(read).not.toHaveBeenCalled(); stop(); });
 it("does not consume the refresh interval when the caller is busy", () => { const read=vi.fn().mockReturnValueOnce(false).mockReturnValue(true),stop=watchLiveRefresh(read,45000); vi.advanceTimersByTime(10000); surface.dispatchEvent(new Event("focus")); surface.dispatchEvent(new Event("focus")); surface.dispatchEvent(new Event("focus")); expect(read).toHaveBeenCalledTimes(2); stop(); });
 it("cleans up timers and listeners on navigation", () => { const read=vi.fn(()=>true),stop=watchLiveRefresh(read,45000); stop(); vi.advanceTimersByTime(600000); surface.dispatchEvent(new Event("focus")); page.dispatchEvent(new Event("visibilitychange")); surface.dispatchEvent(new Event("wheel")); expect(read).not.toHaveBeenCalled(); expect(vi.getTimerCount()).toBe(0); });
});
