import { build } from "esbuild";
import { readFile, mkdir, writeFile } from "node:fs/promises";

const result = await build({
  entryPoints: ["ui/main.tsx"],
  bundle: true,
  write: false,
  format: "iife",
  target: "es2022",
  minify: true,
  jsx: "automatic",
  loader: { ".svg": "text" },
  define: { "process.env.NODE_ENV": '"production"' },
});
const font = await readFile("ui/assets/montserrat-latin-wght-normal.woff2");
const fontLicense = (await readFile("ui/assets/LICENSE", "utf8"))
  .replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
const css = (await readFile("ui/style.css", "utf8")).replace(
  "./assets/montserrat-latin-wght-normal.woff2",
  `data:font/woff2;base64,${font.toString("base64")}`,
);
const icon = (await readFile("plugin/phaseo/assets/logo_light.svg", "utf8"))
  .replace(
    'width="64" height="64" viewBox="0 0 64 64"',
    'width="20" height="20" viewBox="0 0 20 20"',
  )
  .replace("<path ", '<path transform="scale(0.3125)" ')
  .replace('fill="black"', 'fill="currentColor"');
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phaseo models</title><style>${css}</style></head><body><div id="root"></div><details class="font-license"><summary>Font license</summary><pre>${fontLicense}</pre></details><script>${result.outputFiles[0].text.replaceAll("</script", "<\\/script")}</script></body></html>`;
await mkdir("src/generated", { recursive: true });
await writeFile(
  "src/generated/modelExplorerHtml.ts",
  `// Generated by pnpm build:ui. Do not edit.\nexport const modelExplorerHtml = ${JSON.stringify(html)};\nexport const modelExplorerIcon = ${JSON.stringify("data:image/svg+xml;base64," + Buffer.from(icon).toString("base64"))};\n`,
);
await mkdir("dist/ui", { recursive: true });
await writeFile("dist/ui/index.html", html);
