import { build } from "esbuild";
import { readFile, mkdir, writeFile } from "node:fs/promises";

const result = await build({
  entryPoints: ["ui/main.tsx"],
  bundle: true,
  write: false,
  format: "iife",
  target: "es2022",
  minify: true,
  jsx: "automatic",
  loader: { ".svg": "text" },
  define: { "process.env.NODE_ENV": '"production"' },
});
const css = await readFile("ui/style.css", "utf8");
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phaseo models</title><style>${css}</style></head><body><div id="root"></div><script>${result.outputFiles[0].text.replaceAll("</script", "<\\/script")}</script></body></html>`;
await mkdir("src/generated", { recursive: true });
await writeFile(
  "src/generated/modelExplorerHtml.ts",
  `// Generated by pnpm build:ui. Do not edit.\nexport const modelExplorerHtml = ${JSON.stringify(html)};\n`,
);
await mkdir("dist/ui", { recursive: true });
await writeFile("dist/ui/index.html", html);
