-- phaseo:allow-destructive-migration reason: Replaces only bounded derived reporting buckets; request facts, billing, and existing historical reports are preserved.
-- Replace repeated historical scans with coalesced dirty UTC days/weeks.
set local lock_timeout = '500ms';
set local statement_timeout = '10s';
create table private.public_reporting_refresh_queue (
  report text not null check (report in ('users_daily', 'workspaces_weekly')),
  bucket_start date not null,
  generation bigint generated by default as identity,
  requested_at timestamptz not null default clock_timestamp(),
  retry_after timestamptz not null default clock_timestamp(),
  last_error_code text,
  primary key (report, bucket_start)
);
alter table private.public_reporting_refresh_queue enable row level security;
revoke all on private.public_reporting_refresh_queue from public, anon, authenticated, service_role;

create function private.enqueue_public_reporting_refresh(p_occurred_at timestamptz)
returns void language sql security definer set search_path = '' as $$
  insert into private.public_reporting_refresh_queue(report, bucket_start)
  select 'users_daily', (p_occurred_at at time zone 'utc')::date
  where p_occurred_at is not null
  union all
  select 'workspaces_weekly', date_trunc('week', p_occurred_at at time zone 'utc')::date
  where p_occurred_at is not null
  on conflict (report, bucket_start) do update
  set generation = excluded.generation, requested_at = excluded.requested_at;
$$;
revoke all on function private.enqueue_public_reporting_refresh(timestamptz) from public, anon, authenticated, service_role;

create function private.enqueue_public_reporting_for_fact()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'UPDATE' and old is not distinct from new then return new; end if;
  if tg_op <> 'INSERT' then
    perform private.enqueue_public_reporting_refresh(old.occurred_at);
  end if;
  if tg_op <> 'DELETE' then
    if tg_op = 'INSERT' or new.occurred_at is distinct from old.occurred_at then
      perform private.enqueue_public_reporting_refresh(new.occurred_at);
    end if;
    return new;
  end if;
  return old;
end;
$$;
revoke all on function private.enqueue_public_reporting_for_fact() from public, anon, authenticated, service_role;
create trigger v2_request_facts_public_reporting_refresh
before insert or update or delete on public.v2_request_facts
for each row execute function private.enqueue_public_reporting_for_fact();

create function private.enqueue_public_reporting_for_usage()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op <> 'INSERT' then
    perform private.enqueue_public_reporting_refresh(f.occurred_at)
    from public.v2_request_facts f where f.request_event_id = old.request_event_id;
  end if;
  if tg_op <> 'DELETE' then
    if tg_op = 'INSERT' or new.request_event_id is distinct from old.request_event_id then
      perform private.enqueue_public_reporting_refresh(f.occurred_at)
      from public.v2_request_facts f where f.request_event_id = new.request_event_id;
    end if;
    return new;
  end if;
  return old;
end;
$$;
revoke all on function private.enqueue_public_reporting_for_usage() from public, anon, authenticated, service_role;
create trigger v2_request_usage_public_reporting_refresh
before insert or update or delete on public.v2_request_usage
for each row execute function private.enqueue_public_reporting_for_usage();

-- Free-variant metadata is owned by the authoritative request, not the fact.
create function private.enqueue_public_reporting_for_request()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if row(old.api_model_id, old.pricing_plan, old.is_free_variant)
    is distinct from row(new.api_model_id, new.pricing_plan, new.is_free_variant) then
    perform private.enqueue_public_reporting_refresh(f.occurred_at)
    from public.v2_request_facts f
    where f.gateway_request_id = new.id and f.gateway_request_created_at = new.created_at;
  end if;
  return new;
end;
$$;
revoke all on function private.enqueue_public_reporting_for_request() from public, anon, authenticated, service_role;
create trigger gateway_requests_public_reporting_refresh
after update of api_model_id, pricing_plan, is_free_variant on public.gateway_requests
for each row execute function private.enqueue_public_reporting_for_request();

-- Retain the exact actor/model/token contract without serializing the full
-- compatibility row or aggregating unused pricing lines and provider attempts.
create or replace function public.refresh_public_model_user_usage_daily(
  p_since timestamptz default now() - interval '2 days',
  p_until timestamptz default now()
)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_since date := (p_since at time zone 'utc')::date;
  v_until date := ((p_until - interval '1 microsecond') at time zone 'utc')::date;
begin
  delete from public.public_model_user_usage_daily
  where day_bucket >= v_since and day_bucket <= v_until;
  insert into public.public_model_user_usage_daily
    (day_bucket, model_id, provider_id, actor_hash, requests, tokens, refreshed_at)
  with normalized as (
    select (fact.occurred_at at time zone 'utc')::date as day_bucket,
      public.public_leaderboard_model_id(
        coalesce(fact.routed_model_slug, fact.requested_model_slug),
        coalesce(fact.routed_model_slug, fact.requested_model_slug, fact.requested_model_input),
        fact.requested_model_input, fact.routed_model_slug, request.api_model_id,
        route.provider_slug, request.pricing_plan, request.is_free_variant
      ) as model_id,
      coalesce(nullif(route.provider_slug, ''), 'unknown') as provider_id,
      coalesce(
        nullif(fact.safe_metadata->>'oauth_user_id', '')::uuid::text,
        nullif(fact.end_user_id, ''), fact.workspace_id::text, fact.key_id::text
      ) as actor_key,
      public.gateway_usage_nonnegative_bigint(coalesce(
        public.gateway_usage_total_tokens(usage.payload), usage.total_tokens, 0
      )) as total_tokens
    from public.v2_request_facts fact
    left join public.v2_model_provider_routes route on route.provider_model_id = fact.provider_model_id
    left join public.gateway_requests request
      on request.id = fact.gateway_request_id and request.created_at = fact.gateway_request_created_at
    left join lateral (
      select jsonb_object_agg(meter_key, quantity) as payload,
        sum(quantity) filter (where meter_key in ('input_tokens','output_tokens')) as total_tokens
      from (
        select meter.meter_key, sum(meter.quantity) as quantity
        from public.v2_request_usage meter
        where meter.request_event_id = fact.request_event_id
        group by meter.meter_key
      ) meters
    ) usage on true
    where fact.occurred_at >= (v_since::timestamp at time zone 'utc')
      and fact.occurred_at < p_until and fact.success is true
  )
  select day_bucket, model_id, provider_id, md5('public-model-user:' || actor_key),
    count(*)::bigint, sum(total_tokens)::bigint, now()
  from normalized
  where actor_key is not null and model_id is not null and model_id <> ''
    and lower(model_id) not in ('unknown', 'other')
  group by day_bucket, model_id, provider_id, md5('public-model-user:' || actor_key);
end;
$$;
revoke all on function public.refresh_public_model_user_usage_daily(timestamptz,timestamptz) from public, anon, authenticated;
grant execute on function public.refresh_public_model_user_usage_daily(timestamptz,timestamptz) to service_role;

-- Weekly refreshes must also preserve the following week at an exact boundary.
create or replace function public.refresh_public_model_workspace_usage_weekly(
  p_since timestamptz default now() - interval '12 weeks', p_until timestamptz default now()
)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_since_week date := date_trunc('week', p_since at time zone 'utc')::date;
  v_until_week date := date_trunc('week', (p_until - interval '1 microsecond') at time zone 'utc')::date;
begin
  delete from public.public_model_workspace_usage_weekly
  where week_start >= v_since_week and week_start <= v_until_week;
  insert into public.public_model_workspace_usage_weekly
    (week_start, model_id, workspace_hash, requests, refreshed_at)
  select date_trunc('week', fact.occurred_at at time zone 'utc')::date,
    coalesce(nullif(fact.routed_model_slug,''),nullif(fact.requested_model_slug,'')),
    md5('public-model-workspace:' || fact.workspace_id::text), count(*)::bigint, now()
  from public.v2_request_facts fact
  where fact.occurred_at >= p_since and fact.occurred_at < p_until
    and fact.success is true and fact.workspace_id is not null
    and coalesce(nullif(fact.routed_model_slug,''),nullif(fact.requested_model_slug,'')) is not null
    and lower(coalesce(nullif(fact.routed_model_slug,''),nullif(fact.requested_model_slug,''))) not in ('unknown','other')
  group by 1,2,3;
end;
$$;
revoke all on function public.refresh_public_model_workspace_usage_weekly(timestamptz,timestamptz) from public, anon, authenticated;
grant execute on function public.refresh_public_model_workspace_usage_weekly(timestamptz,timestamptz) to service_role;

create function private.drain_public_reporting_refresh()
returns integer language plpgsql security definer set search_path = '' as $$
declare
  item record;
begin
  if not pg_try_advisory_xact_lock(hashtextextended('public-reporting-refresh-worker', 0)) then return 0; end if;
  -- Do not hold an ingestion queue row lock while scanning the source tables.
  select * into item from private.public_reporting_refresh_queue
  where retry_after <= clock_timestamp()
  order by retry_after, report, bucket_start limit 1;
  if not found then return 0; end if;
  begin
    if item.report = 'users_daily' then
      -- Half-open UTC windows preserve the next day's existing result.
      perform public.refresh_public_model_user_usage_daily(
        item.bucket_start::timestamp at time zone 'utc',
        (item.bucket_start + 1)::timestamp at time zone 'utc'
      );
    else
      perform public.refresh_public_model_workspace_usage_weekly(
        item.bucket_start::timestamp at time zone 'utc',
        (item.bucket_start + 7)::timestamp at time zone 'utc'
      );
    end if;
  exception when query_canceled or lock_not_available or others then
    update private.public_reporting_refresh_queue
    set retry_after = clock_timestamp() + interval '2 hours', last_error_code = sqlstate
    where report = item.report and bucket_start = item.bucket_start;
    return 0;
  end;
  delete from private.public_reporting_refresh_queue
  where report = item.report and bucket_start = item.bucket_start and generation = item.generation;
  -- Continuous new writes retain a newer generation, but rotate this bucket to
  -- the back so historical corrections and the other report are not starved.
  update private.public_reporting_refresh_queue set retry_after = clock_timestamp()
  where report = item.report and bucket_start = item.bucket_start;
  return 1;
end;
$$;
revoke all on function private.drain_public_reporting_refresh() from public, anon, authenticated, service_role;

-- Disable obsolete wide scans. Leaderboards already use the gateway's bounded
-- V2 outbox worker; this job must never requeue all completed historical facts.
do $$
declare job record;
begin
  for job in select jobid from cron.job where jobname in (
    'refresh-public-leaderboard-rollups', 'refresh-public-model-user-usage-daily',
    'refresh-public-model-workspace-usage-weekly'
  ) loop
    perform cron.alter_job(job.jobid, active := false);
  end loop;
end;
$$;
select cron.schedule('public-reporting-refresh-queue', '2-59/5 * * * *',
  $job$set statement_timeout = '10s'; set lock_timeout = '500ms'; select private.drain_public_reporting_refresh();$job$);

-- Catch up the known outage window without scanning or requeuing history.
select private.enqueue_public_reporting_refresh(now());
select private.enqueue_public_reporting_refresh(now() - interval '1 day');
comment on table private.public_reporting_refresh_queue is
  'Changed UTC reporting buckets; one bucket per five minutes, 10s timeout, two-hour failed-run backoff. Existing results survive failures.';
