-- Surface Tev's model-card links and enable its choice-only Decisions route.
-- The Tev model and Together route are managed catalogue rows, so these
-- inserts are conditional and leave unrelated Together models untouched.

insert into public.v2_model_links (model_slug, link_kind, title, url, metadata)
select
  model.model_slug,
  link.link_kind,
  link.title,
  link.url,
  jsonb_build_object('source', 'together', 'model_card', 'https://huggingface.co/togethercomputer/Tev1-4B-experimental')
from public.v2_models as model
cross join (
  values
    (
      'weights',
      'Hugging Face weights',
      'https://huggingface.co/togethercomputer/Tev1-4B-experimental/tree/main'
    ),
    (
      'license',
      'Hugging Face license information',
      'https://huggingface.co/togethercomputer/Tev1-4B-experimental#license'
    )
) as link(link_kind, title, url)
where model.model_slug = 'together/tev1-4b-experimental'
on conflict (model_slug, link_kind, url) do update set
  title = excluded.title,
  metadata = public.v2_model_links.metadata || excluded.metadata,
  updated_at = now();

update public.v2_models
set license_url = 'https://huggingface.co/togethercomputer/Tev1-4B-experimental#license',
    metadata = metadata || jsonb_build_object('open_weights', true),
    updated_at = now()
where model_slug = 'together/tev1-4b-experimental';

insert into public.v2_route_capabilities (
  provider_model_id,
  capability_id,
  status,
  max_input_tokens,
  max_output_tokens,
  params,
  metadata
)
select
  route.provider_model_id,
  'decisions.make',
  'active',
  32768,
  8,
  jsonb_build_object('model', true, 'state', true, 'questions', true),
  jsonb_build_object(
    'source', 'together',
    'capability_evidence', jsonb_build_object(
      'status', 'documented',
      'source_url', 'https://api.together.ai/models/together/Tev1-4B-experimental',
      'question_types', jsonb_build_array('choice'),
      'min_options', 2,
      'max_options', 24,
      'response_format', 'single_option_label'
    )
  )
from public.v2_model_provider_routes as route
where route.provider_model_id = 'together:together/tev1-4b-experimental'
  and route.provider_slug = 'together'
  and route.model_slug = 'together/tev1-4b-experimental'
on conflict (provider_model_id, capability_id) do update set
  status = excluded.status,
  max_input_tokens = excluded.max_input_tokens,
  max_output_tokens = excluded.max_output_tokens,
  params = excluded.params,
  metadata = public.v2_route_capabilities.metadata || excluded.metadata,
  updated_at = now();

insert into public.v2_meter_definitions (
  meter_key,
  display_name,
  modality,
  direction,
  unit,
  default_unit_quantity,
  description,
  status,
  metadata
)
values
  (
    'input_tokens',
    'Input tokens',
    'text',
    'input',
    'token',
    1000000,
    'Tokens sent to Together Tev.',
    'active',
    jsonb_build_object('source', 'together')
  ),
  (
    'output_tokens',
    'Output tokens',
    'text',
    'output',
    'token',
    1000000,
    'Tokens generated by Together Tev.',
    'active',
    jsonb_build_object('source', 'together')
  )
on conflict (meter_key) do nothing;

insert into public.v2_pricing_skus (
  provider_model_id,
  sku_code,
  version,
  operation,
  status,
  service_tier_slug,
  display_name,
  description,
  currency,
  effective_from,
  route_variant_id,
  metadata
)
select
  route.provider_model_id,
  'together-tev1-decisions',
  1,
  'decisions.make',
  'active',
  'standard',
  'Tev1 Experimental Decisions',
  '$0.042 per million input tokens; output tokens are free.',
  'USD',
  '2026-09-23T20:45:00Z'::timestamptz,
  (
    select variant.variant_id
    from public.v2_route_variants as variant
    where variant.provider_model_id = route.provider_model_id
      and variant.variant_key = 'global:standard'
  ),
  jsonb_build_object(
    'source_url', 'https://www.linkedin.com/company/togethercomputer',
    'pricing_basis', 'Together AI published serverless pricing',
    'price_per_million_input_tokens_usd', 0.042,
    'price_per_million_output_tokens_usd', 0
  )
from public.v2_model_provider_routes as route
where route.provider_model_id = 'together:together/tev1-4b-experimental'
  and route.provider_slug = 'together'
  and route.model_slug = 'together/tev1-4b-experimental'
on conflict (provider_model_id, sku_code, version) do update set
  operation = excluded.operation,
  status = excluded.status,
  service_tier_slug = excluded.service_tier_slug,
  display_name = excluded.display_name,
  description = excluded.description,
  currency = excluded.currency,
  effective_from = excluded.effective_from,
  route_variant_id = excluded.route_variant_id,
  metadata = public.v2_pricing_skus.metadata || excluded.metadata,
  updated_at = now();

insert into public.v2_pricing_sku_meters (
  sku_id,
  meter_key,
  modality,
  direction,
  unit,
  unit_quantity,
  price_nanos,
  display_label,
  display_unit,
  billable,
  meter_order,
  metadata
)
select
  sku.sku_id,
  meter.meter_key,
  meter.modality,
  meter.direction,
  meter.unit,
  meter.unit_quantity,
  meter.price_nanos,
  meter.display_label,
  meter.display_unit,
  meter.billable,
  meter.meter_order,
  meter.metadata
from public.v2_pricing_skus as sku
cross join (
  values
    (
      'input_tokens', 'text', 'input', 'token', 1000000::numeric,
      42000000::numeric, 'Input tokens', '1M tokens', true, 100,
      jsonb_build_object('source', 'together', 'price_per_million_usd', 0.042)
    ),
    (
      'output_tokens', 'text', 'output', 'token', 1000000::numeric,
      0::numeric, 'Output tokens', '1M tokens', true, 110,
      jsonb_build_object('source', 'together', 'price_per_million_usd', 0)
    )
) as meter(
  meter_key,
  modality,
  direction,
  unit,
  unit_quantity,
  price_nanos,
  display_label,
  display_unit,
  billable,
  meter_order,
  metadata
)
where sku.provider_model_id = 'together:together/tev1-4b-experimental'
  and sku.sku_code = 'together-tev1-decisions'
  and sku.version = 1
on conflict (sku_id, meter_key) do update set
  modality = excluded.modality,
  direction = excluded.direction,
  unit = excluded.unit,
  unit_quantity = excluded.unit_quantity,
  price_nanos = excluded.price_nanos,
  display_label = excluded.display_label,
  display_unit = excluded.display_unit,
  billable = excluded.billable,
  meter_order = excluded.meter_order,
  metadata = public.v2_pricing_sku_meters.metadata || excluded.metadata,
  updated_at = now();
