-- Provider-health reporting is derived data, not the live routing circuit breaker.
-- Coalesce repeated attempt writes into one bounded refresh per dirty daily key.
-- phaseo:allow-destructive-migration reason: Removes obsolete derived health rows and completed refresh signals; authoritative request and billing data remain intact.
set local lock_timeout = '500ms';
set local statement_timeout = '15s';

create table private.provider_health_refresh_queue (
  usage_date date not null,
  model_slug text not null,
  provider_model_id text not null,
  generation bigint generated by default as identity,
  requested_at timestamptz not null default clock_timestamp(),
  retry_after timestamptz not null default clock_timestamp(),
  last_error_code text,
  primary key (usage_date, model_slug, provider_model_id)
);
alter table private.provider_health_refresh_queue enable row level security;
revoke all on private.provider_health_refresh_queue from public, anon, authenticated, service_role;

create function private.enqueue_provider_health_refresh(p_date date, p_model text, p_provider text)
returns void language sql security definer set search_path = '' as $$
  insert into private.provider_health_refresh_queue (usage_date, model_slug, provider_model_id)
  select p_date, p_model, p_provider
  where p_date is not null and p_model is not null and p_provider is not null
  on conflict (usage_date, model_slug, provider_model_id) do update
    set generation = excluded.generation, requested_at = excluded.requested_at;
$$;
revoke all on function private.enqueue_provider_health_refresh(date,text,text) from public, anon, authenticated, service_role;

create or replace function public.refresh_v2_provider_health_for_attempt()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  fact_row record;
begin
  if tg_op <> 'INSERT' then
    select occurred_at::date usage_date, coalesce(routed_model_slug, requested_model_slug) model_slug
      into fact_row from public.v2_request_facts where request_event_id = old.request_event_id;
    perform private.enqueue_provider_health_refresh(fact_row.usage_date, fact_row.model_slug, old.provider_model_id);
  end if;
  if tg_op <> 'DELETE' then
    select occurred_at::date usage_date, coalesce(routed_model_slug, requested_model_slug) model_slug
      into fact_row from public.v2_request_facts where request_event_id = new.request_event_id;
    perform private.enqueue_provider_health_refresh(fact_row.usage_date, fact_row.model_slug, new.provider_model_id);
  end if;
  return null;
end;
$$;
revoke all on function public.refresh_v2_provider_health_for_attempt() from public, anon, authenticated;

drop trigger if exists v2_request_attempts_health_refresh on public.v2_request_attempts;
create trigger v2_request_attempts_health_refresh after insert or update or delete
  on public.v2_request_attempts for each row
  execute function public.refresh_v2_provider_health_for_attempt();

-- Replays may move a request to another day/model before replacing its attempts.
-- Capture old buckets before cascading deletes remove the fact/attempt linkage.
create function private.enqueue_provider_health_for_fact()
returns trigger language plpgsql security definer set search_path = '' as $$
declare provider_value text;
begin
  if tg_op = 'UPDATE' and old.occurred_at::date is not distinct from new.occurred_at::date
    and coalesce(old.routed_model_slug, old.requested_model_slug) is not distinct from
        coalesce(new.routed_model_slug, new.requested_model_slug) then
    return new;
  end if;
  for provider_value in select distinct provider_model_id from public.v2_request_attempts
    where request_event_id = old.request_event_id and provider_model_id is not null
    order by provider_model_id
  loop
    perform private.enqueue_provider_health_refresh(old.occurred_at::date,
      coalesce(old.routed_model_slug, old.requested_model_slug), provider_value);
    if tg_op = 'UPDATE' then
      perform private.enqueue_provider_health_refresh(new.occurred_at::date,
        coalesce(new.routed_model_slug, new.requested_model_slug), provider_value);
    end if;
  end loop;
  if tg_op = 'UPDATE' then return new; end if;
  return old;
end;
$$;
revoke all on function private.enqueue_provider_health_for_fact() from public, anon, authenticated, service_role;
create trigger v2_request_facts_health_refresh before update or delete
  on public.v2_request_facts for each row execute function private.enqueue_provider_health_for_fact();

create function private.drain_provider_health_refresh(p_limit integer default 2)
returns integer language plpgsql security definer set search_path = '' as $$
declare
  item record;
  provider_value text;
  completed integer := 0;
  started_at timestamptz := clock_timestamp();
begin
  -- Only workers take this lock. Ingestion never waits for a reporting scan.
  if not pg_try_advisory_xact_lock(hashtextextended('provider_health_refresh_worker', 0)) then return 0; end if;
  for item in select * from private.provider_health_refresh_queue
    where retry_after <= clock_timestamp()
    order by retry_after, usage_date, model_slug, provider_model_id
    limit greatest(1, least(coalesce(p_limit, 2), 5))
  loop
    exit when clock_timestamp() - started_at > interval '5 seconds';
    begin
      select provider_slug into provider_value from public.v2_model_provider_routes
        where provider_model_id = item.provider_model_id;
      -- Remove old provider-slug rows as well when route metadata was corrected.
      delete from public.v2_public_provider_health_daily
        where usage_date = item.usage_date and model_slug = item.model_slug
          and provider_model_id = item.provider_model_id;
      if provider_value is not null then
        insert into public.v2_public_provider_health_daily (
          usage_date, model_slug, provider_model_id, provider_slug, request_count,
          successful_request_count, attempt_count, successful_attempts, failed_attempts,
          fallback_attempts, latency_sum_ms, latency_count, updated_at
        )
        select item.usage_date, item.model_slug, item.provider_model_id, provider_value,
          count(distinct fact.request_event_id), count(distinct fact.request_event_id) filter (where attempt.success),
          count(*), count(*) filter (where attempt.success), count(*) filter (where not attempt.success),
          count(*) filter (where attempt.attempt_number > 1),
          coalesce(sum(attempt.latency_ms), 0), count(attempt.latency_ms), clock_timestamp()
        from public.v2_request_facts fact
        join public.v2_request_attempts attempt on attempt.request_event_id = fact.request_event_id
        where fact.occurred_at >= item.usage_date::timestamptz
          and fact.occurred_at < (item.usage_date + 1)::timestamptz
          and (fact.routed_model_slug = item.model_slug
            or (fact.routed_model_slug is null and fact.requested_model_slug = item.model_slug))
          and attempt.provider_model_id = item.provider_model_id
        having count(*) > 0;
      end if;
      -- A new write during the scan changes generation; keep its signal queued.
      -- No queue row lock is held during the expensive scan.
      delete from private.provider_health_refresh_queue
        where usage_date = item.usage_date and model_slug = item.model_slug
          and provider_model_id = item.provider_model_id and generation = item.generation;
      completed := completed + 1;
    exception when query_canceled or lock_not_available or others then
      update private.provider_health_refresh_queue
        set retry_after = clock_timestamp() + interval '5 minutes', last_error_code = sqlstate
        where usage_date = item.usage_date and model_slug = item.model_slug
          and provider_model_id = item.provider_model_id;
    end;
  end loop;
  return completed;
end;
$$;
revoke all on function private.drain_provider_health_refresh(integer) from public, anon, authenticated;
grant execute on function private.drain_provider_health_refresh(integer) to service_role;

-- A single SQL statement per run, capped independently of request ingestion.
select cron.schedule('provider-health-refresh-queue', '* * * * *',
  $$set statement_timeout = '10s'; select private.drain_provider_health_refresh(2);$$);
