-- Internal diagnostics for auth signup trigger flow.
-- Goal: identify the exact failing stage without exposing logs publicly.

create table if not exists public.auth_signup_trigger_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default (now() at time zone 'utc'),
  user_id uuid not null references auth.users(id) on delete cascade,
  email text null,
  stage text not null,
  status text not null,
  error_message text null,
  error_sqlstate text null,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists auth_signup_trigger_log_user_created_idx
  on public.auth_signup_trigger_log (user_id, created_at desc);
create index if not exists auth_signup_trigger_log_created_idx
  on public.auth_signup_trigger_log (created_at desc);
revoke all on public.auth_signup_trigger_log from anon, authenticated;
grant select on public.auth_signup_trigger_log to service_role;
create or replace function public.log_auth_signup_trigger_event(
  p_user_id uuid,
  p_email text,
  p_stage text,
  p_status text,
  p_error_message text default null,
  p_error_sqlstate text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.auth_signup_trigger_log (
    user_id,
    email,
    stage,
    status,
    error_message,
    error_sqlstate,
    metadata
  )
  values (
    p_user_id,
    p_email,
    p_stage,
    p_status,
    left(p_error_message, 2000),
    p_error_sqlstate,
    coalesce(p_metadata, '{}'::jsonb)
  );
exception when others then
  -- Never allow diagnostics writes to break auth signup.
  null;
end;
$$;
create or replace function public.enqueue_welcome_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted integer := 0;
  v_webhook_url text;
  v_request_id bigint;
  v_created_at text;
  v_stage text := 'start';
  v_error_message text;
  v_error_sqlstate text;
  v_error_detail text;
begin
  perform public.log_auth_signup_trigger_event(
    p_user_id := new.id,
    p_email := new.email,
    p_stage := 'start',
    p_status := 'ok',
    p_metadata := jsonb_build_object('auth_created_at', new.created_at)
  );

  v_stage := 'public_users_upsert';
  begin
    insert into public.users (user_id)
    values (new.id)
    on conflict (user_id) do nothing;

    perform public.log_auth_signup_trigger_event(
      p_user_id := new.id,
      p_email := new.email,
      p_stage := v_stage,
      p_status := 'ok'
    );
  exception when others then
    get stacked diagnostics
      v_error_message = message_text,
      v_error_sqlstate = returned_sqlstate,
      v_error_detail = pg_exception_detail;

    perform public.log_auth_signup_trigger_event(
      p_user_id := new.id,
      p_email := new.email,
      p_stage := v_stage,
      p_status := 'error',
      p_error_message := coalesce(v_error_message, sqlerrm),
      p_error_sqlstate := v_error_sqlstate,
      p_metadata := jsonb_build_object('detail', coalesce(v_error_detail, ''))
    );
  end;

  v_stage := 'email_outbox_insert';
  if new.email is not null and new.email <> '' then
    begin
      insert into public.email_outbox (kind, template, to_email, subject, user_id, payload)
      values (
        'welcome',
        'welcome',
        new.email,
        'Welcome to AI Stats',
        new.id,
        jsonb_build_object('user_id', new.id)
      );

      perform public.log_auth_signup_trigger_event(
        p_user_id := new.id,
        p_email := new.email,
        p_stage := v_stage,
        p_status := 'ok'
      );
    exception when others then
      get stacked diagnostics
        v_error_message = message_text,
        v_error_sqlstate = returned_sqlstate,
        v_error_detail = pg_exception_detail;

      perform public.log_auth_signup_trigger_event(
        p_user_id := new.id,
        p_email := new.email,
        p_stage := v_stage,
        p_status := 'error',
        p_error_message := coalesce(v_error_message, sqlerrm),
        p_error_sqlstate := v_error_sqlstate,
        p_metadata := jsonb_build_object('detail', coalesce(v_error_detail, ''))
      );
    end;
  else
    perform public.log_auth_signup_trigger_event(
      p_user_id := new.id,
      p_email := new.email,
      p_stage := v_stage,
      p_status := 'skip',
      p_metadata := jsonb_build_object('reason', 'missing_email')
    );
  end if;

  v_stage := 'signup_discord_notification_insert';
  begin
    insert into public.signup_discord_notifications (user_id, email, payload)
    values (
      new.id,
      new.email,
      jsonb_build_object(
        'user_id', new.id,
        'email', new.email,
        'auth_created_at', new.created_at
      )
    )
    on conflict (user_id) do nothing;
    get diagnostics v_inserted = row_count;

    perform public.log_auth_signup_trigger_event(
      p_user_id := new.id,
      p_email := new.email,
      p_stage := v_stage,
      p_status := 'ok',
      p_metadata := jsonb_build_object('inserted_rows', v_inserted)
    );
  exception when others then
    get stacked diagnostics
      v_error_message = message_text,
      v_error_sqlstate = returned_sqlstate,
      v_error_detail = pg_exception_detail;

    perform public.log_auth_signup_trigger_event(
      p_user_id := new.id,
      p_email := new.email,
      p_stage := v_stage,
      p_status := 'error',
      p_error_message := coalesce(v_error_message, sqlerrm),
      p_error_sqlstate := v_error_sqlstate,
      p_metadata := jsonb_build_object('detail', coalesce(v_error_detail, ''))
    );

    return new;
  end;

  if v_inserted = 1 then
    v_stage := 'discord_webhook_url_resolve';
    v_webhook_url := nullif(trim(current_setting('app.settings.discord_signup_webhook_url', true)), '');
    if v_webhook_url is null then
      begin
        update public.signup_discord_notifications
        set last_error = 'discord_signup_webhook_url_not_configured'
        where user_id = new.id;
      exception when others then
        null;
      end;

      perform public.log_auth_signup_trigger_event(
        p_user_id := new.id,
        p_email := new.email,
        p_stage := v_stage,
        p_status := 'skip',
        p_metadata := jsonb_build_object('reason', 'discord_signup_webhook_url_not_configured')
      );

      return new;
    end if;

    perform public.log_auth_signup_trigger_event(
      p_user_id := new.id,
      p_email := new.email,
      p_stage := v_stage,
      p_status := 'ok'
    );

    v_created_at := coalesce(new.created_at::text, (now() at time zone 'utc')::text);

    v_stage := 'discord_webhook_request';
    begin
      select net.http_post(
        url := v_webhook_url,
        headers := jsonb_build_object('Content-Type', 'application/json'),
        body := jsonb_build_object(
          'content',
          'New AI Stats signup' || E'\n' ||
          '- user_id: `' || new.id::text || '`' || E'\n' ||
          '- email: `' || coalesce(new.email, 'unknown') || '`' || E'\n' ||
          '- created_at: `' || v_created_at || '`',
          'allowed_mentions',
          jsonb_build_object('parse', jsonb_build_array())
        )
      )
      into v_request_id;

      begin
        update public.signup_discord_notifications
        set sent_at = (now() at time zone 'utc'),
            webhook_request_id = v_request_id,
            last_error = null
        where user_id = new.id;
      exception when others then
        null;
      end;

      perform public.log_auth_signup_trigger_event(
        p_user_id := new.id,
        p_email := new.email,
        p_stage := v_stage,
        p_status := 'ok',
        p_metadata := jsonb_build_object('request_id', v_request_id)
      );
    exception when others then
      get stacked diagnostics
        v_error_message = message_text,
        v_error_sqlstate = returned_sqlstate,
        v_error_detail = pg_exception_detail;

      begin
        update public.signup_discord_notifications
        set last_error = left(coalesce(v_error_message, sqlerrm), 2000)
        where user_id = new.id;
      exception when others then
        null;
      end;

      perform public.log_auth_signup_trigger_event(
        p_user_id := new.id,
        p_email := new.email,
        p_stage := v_stage,
        p_status := 'error',
        p_error_message := coalesce(v_error_message, sqlerrm),
        p_error_sqlstate := v_error_sqlstate,
        p_metadata := jsonb_build_object('detail', coalesce(v_error_detail, ''))
      );
    end;
  else
    perform public.log_auth_signup_trigger_event(
      p_user_id := new.id,
      p_email := new.email,
      p_stage := 'discord_webhook_request',
      p_status := 'skip',
      p_metadata := jsonb_build_object('reason', 'notification_already_exists')
    );
  end if;

  return new;
exception when others then
  get stacked diagnostics
    v_error_message = message_text,
    v_error_sqlstate = returned_sqlstate,
    v_error_detail = pg_exception_detail;

  perform public.log_auth_signup_trigger_event(
    p_user_id := new.id,
    p_email := new.email,
    p_stage := coalesce(v_stage, 'unknown'),
    p_status := 'fatal',
    p_error_message := coalesce(v_error_message, sqlerrm),
    p_error_sqlstate := v_error_sqlstate,
    p_metadata := jsonb_build_object('detail', coalesce(v_error_detail, ''))
  );

  return new;
end;
$$;
