import { Hono } from "hono";
import type Stripe from "stripe";
import type { Env } from "@/env";
import { PRIVATE_NO_STORE_HEADERS } from "@/http/cache";
import { activeStripeCustomer, ensureWorkspaceStripeCustomer, getStripe } from "@/billing/stripe";
import {
	deriveFirstName,
	sendBillingDiscordWebhook,
	sendCheckoutStartedEvent,
	type CheckoutStartedPayload,
} from "@/billing/notifications";
import { requireAccountWorkspace } from "./context";

const TOP_UP_KINDS = new Set(["top_up", "top_up_one_off", "auto_top_up"]);
const REFUND_REASON_LABELS: Record<string, string> = { no_comment: "No comment", accidental_purchase: "Accidental purchase", duplicate_purchase: "Duplicate purchase", wrong_amount: "Wrong amount selected", testing_only: "Testing / sandbox use", no_longer_needed: "No longer needed", other: "Other" };

async function context(c: any, workspaceId: unknown) { const value = String(workspaceId ?? "").trim(); return requireAccountWorkspace({ request: c.req.raw, env: c.env, workspaceId: value || null }); }
function methodCustomer(value: Stripe.PaymentMethod["customer"]): string | null { return typeof value === "string" ? value : value && typeof value === "object" && "id" in value ? String(value.id) : null; }
async function methods(env: Env, customerId: string) {
	const stripe = getStripe(env); const [customerResponse, list] = await Promise.all([stripe.customers.retrieve(customerId), stripe.paymentMethods.list({ customer: customerId, type: "card", limit: 100 })]); const customer = activeStripeCustomer(customerResponse); const rawDefault = customer?.invoice_settings.default_payment_method;
	return { customer: { id: customerId, email: customer?.email ?? null }, defaultPaymentMethodId: typeof rawDefault === "string" ? rawDefault : rawDefault?.id ?? null, paymentMethods: list.data.map((method) => ({ id: method.id, brand: method.card?.brand ?? null, last4: method.card?.last4 ?? null, expMonth: method.card?.exp_month ?? null, expYear: method.card?.exp_year ?? null, funding: method.card?.funding ?? null, created: method.created ?? null })) };
}
function safeReturnUrl(request: Request, candidate: unknown, fallbackPath = "/settings/payment-methods"): string { const siteOrigin = new URL(request.url).origin; const fallback = new URL(fallbackPath, siteOrigin).toString(); if (typeof candidate !== "string") return fallback; try { const url = new URL(candidate, siteOrigin); return url.origin === siteOrigin ? url.toString() : fallback; } catch { return fallback; } }
async function notifyCheckoutStarted(env: Env, email: string | null, payload: CheckoutStartedPayload) {
	if (email) await sendCheckoutStartedEvent(env, { email, payload }).catch((error) => console.error("checkout_started_resend_failed", error));
	await sendBillingDiscordWebhook(env, { event: "checkout_started", email, payload }).catch((error) => console.error("checkout_started_discord_failed", error));
}

export const accountSettingsBillingRouter = new Hono<{ Bindings: Env }>();
accountSettingsBillingRouter.get("/billing/payment-methods", async (c) => { const loaded = await context(c, c.req.query("workspaceId")); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); try { const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); return c.json(await methods(c.env, customerId), 200, PRIVATE_NO_STORE_HEADERS); } catch { return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); } });
accountSettingsBillingRouter.post("/billing/payment-methods", async (c) => { const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); try { const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); const session = await getStripe(c.env).checkout.sessions.create({ mode: "setup", payment_method_types: ["card", "link"], customer: customerId, success_url: safeReturnUrl(c.req.raw, body.returnUrl), cancel_url: safeReturnUrl(c.req.raw, body.returnUrl), setup_intent_data: { metadata: { purpose: "auto_topup_setup", workspace_id: loaded.workspaceId } } }); return c.json({ url: session.url }, 200, PRIVATE_NO_STORE_HEADERS); } catch { return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); } });
accountSettingsBillingRouter.patch("/billing/payment-methods", async (c) => { const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const paymentMethodId = String(body.paymentMethodId ?? "").trim(); if (!paymentMethodId) return c.json({ error: "Missing paymentMethodId" }, 400, PRIVATE_NO_STORE_HEADERS); try { const stripe = getStripe(c.env); const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); const paymentMethod = await stripe.paymentMethods.retrieve(paymentMethodId); const owner = methodCustomer(paymentMethod.customer); if (owner && owner !== customerId) return c.json({ error: "Payment method does not belong to this customer" }, 403, PRIVATE_NO_STORE_HEADERS); if (!owner) await stripe.paymentMethods.attach(paymentMethodId, { customer: customerId }); await stripe.customers.update(customerId, { invoice_settings: { default_payment_method: paymentMethodId } }); return c.json(await methods(c.env, customerId), 200, PRIVATE_NO_STORE_HEADERS); } catch { return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); } });
accountSettingsBillingRouter.delete("/billing/payment-methods", async (c) => { const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const paymentMethodId = String(body.paymentMethodId ?? "").trim(); if (!paymentMethodId) return c.json({ error: "Missing paymentMethodId" }, 400, PRIVATE_NO_STORE_HEADERS); try { const stripe = getStripe(c.env); const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); const before = await methods(c.env, customerId); if (!before.paymentMethods.some((method) => method.id === paymentMethodId)) return c.json({ error: "Payment method not found" }, 404, PRIVATE_NO_STORE_HEADERS); const nextDefault = before.paymentMethods.find((method) => method.id !== paymentMethodId)?.id ?? null; if (before.defaultPaymentMethodId === paymentMethodId) await stripe.customers.update(customerId, { invoice_settings: { default_payment_method: nextDefault ?? undefined } }); await stripe.paymentMethods.detach(paymentMethodId); const wallet = await loaded.client.from("wallets").select("auto_top_up_enabled,auto_top_up_account_id").eq("workspace_id", loaded.workspaceId).maybeSingle(); if (wallet.error) throw wallet.error; if (wallet.data?.auto_top_up_account_id === paymentMethodId) { const updated = await loaded.client.from("wallets").update({ auto_top_up_account_id: nextDefault, auto_top_up_enabled: nextDefault ? Boolean(wallet.data.auto_top_up_enabled) : false }).eq("workspace_id", loaded.workspaceId); if (updated.error) throw updated.error; } return c.json(await methods(c.env, customerId), 200, PRIVATE_NO_STORE_HEADERS); } catch { return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); } });

accountSettingsBillingRouter.post("/billing/invoice-document", async (c) => {
	const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const invoiceId = String(body.stripeInvoiceId ?? body.stripe_invoice_id ?? "").trim(); if (!invoiceId.startsWith("in_")) return c.json({ error: "Invalid stripe invoice id" }, 400, PRIVATE_NO_STORE_HEADERS);
	const row = await loaded.client.from("workspace_invoices").select("stripe_invoice_id").eq("workspace_id", loaded.workspaceId).eq("stripe_invoice_id", invoiceId).maybeSingle(); if (row.error) return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); if (!row.data) return c.json({ error: "Invoice not found" }, 404, PRIVATE_NO_STORE_HEADERS);
	try { const invoice = await getStripe(c.env).invoices.retrieve(invoiceId); const url = invoice.hosted_invoice_url ?? invoice.invoice_pdf ?? null; return url ? c.json({ ok: true, type: "invoice", url }, 200, PRIVATE_NO_STORE_HEADERS) : c.json({ error: "Invoice document unavailable" }, 404, PRIVATE_NO_STORE_HEADERS); } catch { return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); }
});

accountSettingsBillingRouter.post("/billing/purchase-document", async (c) => {
	const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const paymentIntentId = String(body.paymentIntentId ?? body.payment_intent_id ?? "").trim(); if (!paymentIntentId.startsWith("pi_")) return c.json({ error: "Invalid payment intent id" }, 400, PRIVATE_NO_STORE_HEADERS);
	const purchase = await loaded.client.from("credit_ledger").select("kind").eq("workspace_id", loaded.workspaceId).eq("ref_type", "Stripe_Payment_Intent").eq("ref_id", paymentIntentId).maybeSingle(); if (purchase.error) return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); if (!purchase.data || !["top_up", "top_up_one_off", "auto_top_up"].includes(String(purchase.data.kind ?? ""))) return c.json({ error: "Purchase not found" }, 404, PRIVATE_NO_STORE_HEADERS);
	try { const stripe = getStripe(c.env); const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); const intent = await stripe.paymentIntents.retrieve(paymentIntentId, { expand: ["latest_charge", "latest_charge.invoice"] }); let charge = intent.latest_charge; if (typeof charge === "string") charge = await stripe.charges.retrieve(charge, { expand: ["invoice"] }); if (!charge || typeof charge === "string") return c.json({ error: "Document not available yet" }, 404, PRIVATE_NO_STORE_HEADERS); const chargeCustomer = typeof charge.customer === "string" ? charge.customer : charge.customer?.id ?? null; if (chargeCustomer !== customerId) return c.json({ error: "Customer mismatch" }, 403, PRIVATE_NO_STORE_HEADERS); const invoice = (charge as Stripe.Charge & { invoice?: string | Stripe.Invoice | null }).invoice; if (invoice && typeof invoice !== "string") { const url = invoice.hosted_invoice_url ?? invoice.invoice_pdf; if (url) return c.json({ ok: true, type: "invoice", url, message: "Invoice ready" }, 200, PRIVATE_NO_STORE_HEADERS); } if (charge.receipt_url) return c.json({ ok: true, type: "receipt", url: charge.receipt_url, message: "Receipt ready" }, 200, PRIVATE_NO_STORE_HEADERS); return c.json({ error: "Document not available yet" }, 404, PRIVATE_NO_STORE_HEADERS); } catch { return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); }
});

accountSettingsBillingRouter.post("/billing/portal", async (c) => {
	const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS);
	try { const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); const session = await getStripe(c.env).billingPortal.sessions.create({ customer: customerId, return_url: safeReturnUrl(c.req.raw, body.returnUrl, "/settings/credits") }); return c.json({ url: session.url }, 200, PRIVATE_NO_STORE_HEADERS); } catch { return c.json({ error: "billing_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); }
});

accountSettingsBillingRouter.post("/billing/refund", async (c) => {
	const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const paymentIntentId = String(body.paymentIntentId ?? body.payment_intent_id ?? "").trim(); if (!paymentIntentId.startsWith("pi_")) return c.json({ error: "Invalid payment intent id" }, 400, PRIVATE_NO_STORE_HEADERS); const reasonCode = Object.hasOwn(REFUND_REASON_LABELS, String(body.reason ?? "")) ? String(body.reason) : "no_comment";
	try {
		const purchase = await loaded.client.from("credit_ledger").select("event_time,kind,amount_nanos,before_balance_nanos,status").eq("workspace_id", loaded.workspaceId).eq("ref_type", "Stripe_Payment_Intent").eq("ref_id", paymentIntentId).maybeSingle(); if (purchase.error) throw purchase.error; if (!purchase.data) return c.json({ error: "Purchase not found" }, 404, PRIVATE_NO_STORE_HEADERS); if (!TOP_UP_KINDS.has(String(purchase.data.kind ?? ""))) return c.json({ error: "Only credit top-ups can be refunded here" }, 400, PRIVATE_NO_STORE_HEADERS); if (!["paid", "succeeded"].includes(String(purchase.data.status ?? "").toLowerCase())) return c.json({ error: "This purchase is not in a refundable state" }, 409, PRIVATE_NO_STORE_HEADERS);
		const purchasedAt = Date.parse(String(purchase.data.event_time ?? "")); if (!Number.isFinite(purchasedAt) || Date.now() - purchasedAt > 86_400_000) return c.json({ error: "Self-serve refunds are only available for 24 hours after purchase." }, 409, PRIVATE_NO_STORE_HEADERS); const amountNanos = Number(purchase.data.amount_nanos ?? 0); const beforeBalance = Number(purchase.data.before_balance_nanos ?? 0); if (!(amountNanos > 0)) return c.json({ error: "Invalid purchase amount" }, 400, PRIVATE_NO_STORE_HEADERS);
		const [existing, usage] = await Promise.all([loaded.client.from("credit_ledger").select("status").eq("workspace_id", loaded.workspaceId).eq("kind", "refund").eq("source_ref_type", "Stripe_Payment_Intent").eq("source_ref_id", paymentIntentId), loaded.client.from("gateway_requests").select("cost_nanos").eq("workspace_id", loaded.workspaceId).eq("success", true).gte("created_at", new Date(purchasedAt).toISOString())]); if (existing.error || usage.error) throw existing.error ?? usage.error; if ((existing.data ?? []).some((row) => ["pending", "applying", "processing", "succeeded"].includes(String(row.status ?? "").toLowerCase()))) return c.json({ error: "A refund for this purchase is already in progress or completed." }, 409, PRIVATE_NO_STORE_HEADERS); const usageNanos = (usage.data ?? []).reduce((sum, row) => sum + Math.max(0, Number(row.cost_nanos ?? 0) || 0), 0); if (usageNanos > beforeBalance) return c.json({ error: "This top-up has already been used, so it is not eligible for self-serve refund." }, 409, PRIVATE_NO_STORE_HEADERS);
		const stripe = getStripe(c.env); const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); const intent = await stripe.paymentIntents.retrieve(paymentIntentId, { expand: ["latest_charge"] }); let gross = Number(intent.amount ?? 0) || 0; let refunded = 0; let charge = intent.latest_charge; if (typeof charge === "string") charge = await stripe.charges.retrieve(charge); if (charge && typeof charge !== "string") { gross = Number(charge.amount ?? gross) || gross; refunded = Number(charge.amount_refunded ?? 0) || 0; } const refundable = Math.max(0, gross - refunded); if (!refundable) return c.json({ error: "This payment no longer has a refundable amount." }, 409, PRIVATE_NO_STORE_HEADERS);
		const refund = await stripe.refunds.create({ payment_intent: paymentIntentId, amount: refundable, reason: "requested_by_customer", metadata: { purpose: "self_serve_unused_lot_refund", workspace_id: loaded.workspaceId, user_id: loaded.user.id, stripe_customer_id: customerId, user_reason: REFUND_REASON_LABELS[reasonCode], user_reason_code: reasonCode } }, { idempotencyKey: `self_serve_refund:${loaded.workspaceId}:${paymentIntentId}` }); const refundNanos = -Math.max(0, Math.round(amountNanos * (gross > 0 ? Math.min(1, Number(refund.amount ?? refundable) / gross) : 1))); const wallet = await loaded.client.from("wallets").select("balance_nanos").eq("workspace_id", loaded.workspaceId).maybeSingle(); if (wallet.error) throw wallet.error; const balance = Number(wallet.data?.balance_nanos ?? 0);
		const ledger = await loaded.client.from("credit_ledger").upsert({ workspace_id: loaded.workspaceId, kind: "refund", amount_nanos: refundNanos, before_balance_nanos: balance, after_balance_nanos: balance, ref_type: "Stripe_Refund", ref_id: refund.id, status: String(refund.status ?? "pending"), event_time: new Date().toISOString(), source_ref_type: "Stripe_Payment_Intent", source_ref_id: paymentIntentId }, { onConflict: "ref_type,ref_id" }); if (ledger.error) throw ledger.error; let claimState = "Requested"; const status = String(refund.status ?? "pending").toLowerCase(); if (status === "succeeded" && refundNanos < 0) { const delta = await loaded.client.rpc("wallet_apply_delta", { p_workspace_id: loaded.workspaceId, p_delta_nanos: refundNanos }); if (!delta.error) { claimState = "Succeeded"; const row = delta.data?.[0] ?? {}; await loaded.client.from("credit_ledger").update({ before_balance_nanos: Number(row.before_balance_nanos ?? balance), after_balance_nanos: Number(row.after_balance_nanos ?? balance), status: "Succeeded", event_time: new Date().toISOString() }).eq("ref_type", "Stripe_Refund").eq("ref_id", refund.id); } }
		await loaded.client.from("credit_ledger").update({ refund_claim_state: claimState, refund_claim_reason: REFUND_REASON_LABELS[reasonCode], refund_claimed_at: new Date().toISOString(), refund_claimed_by_user_id: loaded.user.id }).eq("workspace_id", loaded.workspaceId).eq("ref_type", "Stripe_Payment_Intent").eq("ref_id", paymentIntentId); return c.json({ ok: true, refundId: refund.id, status, message: status === "succeeded" ? "Your refund is confirmed. Most banks post refunds in 5-10 business days." : "Your refund request is processing. Once confirmed, most banks post refunds in 5-10 business days." }, 200, PRIVATE_NO_STORE_HEADERS);
	} catch (error) { return c.json({ error: error instanceof Error ? error.message : "refund_request_failed" }, 503, PRIVATE_NO_STORE_HEADERS); }
});

accountSettingsBillingRouter.post("/billing/charge-saved", async (c) => {
	const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId ?? body.workspace_id); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const amount = Number(body.amount_pence); if (!Number.isFinite(amount) || amount < 50) return c.json({ error: "Invalid amount" }, 400, PRIVATE_NO_STORE_HEADERS);
	try { const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); const purpose = ["top_up", "top_up_one_off", "auto_top_up", "credits_topup_offsession"].includes(String(body.event_type ?? "")) ? String(body.event_type) : "auto_top_up"; const intent = await getStripe(c.env).paymentIntents.create({ amount: Math.round(amount), currency: String(body.currency ?? "usd"), customer: customerId, payment_method: String(body.paymentMethodId ?? body.payment_method_id ?? "").trim() || undefined, off_session: true, confirm: true, metadata: { purpose, workspace_id: loaded.workspaceId } }); return c.json({ status: intent.status, clientSecret: intent.client_secret }, 200, PRIVATE_NO_STORE_HEADERS); } catch (error: any) { if (error?.code === "requires_action" && error?.payment_intent?.client_secret) return c.json({ status: "requires_action", clientSecret: error.payment_intent.client_secret, error: error.message }, 402, PRIVATE_NO_STORE_HEADERS); return c.json({ error: error instanceof Error ? error.message : "payment_failed" }, 503, PRIVATE_NO_STORE_HEADERS); }
});

accountSettingsBillingRouter.post("/billing/checkout", async (c) => {
	const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const loaded = await context(c, body.workspaceId ?? body.workspace_id); if (!loaded) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const kind = String(body.kind ?? ""); if (!["oneoff", "pay_and_save", "save_only"].includes(kind)) return c.json({ error: "Unknown kind" }, 400, PRIVATE_NO_STORE_HEADERS); const amount = Number(body.amount_pence ?? body.purchase_amount_cents); if (kind !== "save_only" && (!Number.isFinite(amount) || amount < 500)) return c.json({ error: "Invalid amount" }, 400, PRIVATE_NO_STORE_HEADERS);
	try { const stripe = getStripe(c.env); const customerId = await ensureWorkspaceStripeCustomer(c.env, loaded); const base = new URL(safeReturnUrl(c.req.raw, body.returnUrl, "/settings/credits")); base.pathname = "/settings/credits"; base.search = ""; const success = new URL(base); success.searchParams.set("checkout", "success"); success.searchParams.set("kind", kind); success.searchParams.set("payment_attempt", String(Date.now())); const cancel = new URL(base); cancel.searchParams.set("checkout", "cancelled"); let session;
		if (kind === "save_only") session = await stripe.checkout.sessions.create({ mode: "setup", payment_method_types: ["card", "link"], customer: customerId, success_url: success.toString(), cancel_url: cancel.toString(), setup_intent_data: { metadata: { purpose: "auto_topup_setup", workspace_id: loaded.workspaceId } } });
		else session = await stripe.checkout.sessions.create({ mode: "payment", payment_method_types: ["card", "link"], payment_method_options: { card: { request_three_d_secure: "automatic" } }, customer: customerId, line_items: [{ quantity: 1, price_data: { currency: String(body.currency ?? "usd"), unit_amount: Math.round(amount), product_data: { name: kind === "pay_and_save" ? "AI Credits top-up (save card)" : "AI Credits top-up (one-off)" } } }], payment_intent_data: { ...(kind === "pay_and_save" ? { setup_future_usage: "off_session" as const } : {}), metadata: { purpose: kind === "oneoff" ? "top_up_one_off" : "top_up", workspace_id: loaded.workspaceId } }, success_url: success.toString(), cancel_url: cancel.toString(), ...(kind === "oneoff" ? { allow_promotion_codes: false, billing_address_collection: "auto" as const } : {}) });
		if (kind !== "save_only") {
			const metadata = loaded.user.userMetadata;
			await notifyCheckoutStarted(c.env, loaded.user.email, {
				workspaceId: loaded.workspaceId,
				userId: loaded.user.id,
				firstName: deriveFirstName(typeof metadata.full_name === "string" ? metadata.full_name : typeof metadata.name === "string" ? metadata.name : loaded.user.email),
				checkoutSessionId: session.id,
				checkoutKind: body.notificationCheckoutKind === "legacy_checkout" ? "legacy_checkout" : kind === "oneoff" ? "oneoff" : "pay_and_save",
				currency: String(body.currency ?? "usd"),
				amountPence: Math.round(amount),
				startedAtIso: new Date().toISOString(),
			});
		}
		return c.json({ url: session.url }, 200, PRIVATE_NO_STORE_HEADERS); } catch (error) { return c.json({ error: error instanceof Error ? error.message : "checkout_failed" }, 503, PRIVATE_NO_STORE_HEADERS); }
});
