import { Hono } from "hono";
import type { Env } from "@/env";
import { PRIVATE_NO_STORE_HEADERS } from "@/http/cache";
import { requireAccountWorkspace } from "./context";

const DEFAULT_EVENTS = ["video.completed", "video.failed", "video.cancelled", "batch.completed", "batch.failed", "batch.cancelled"];
function text(value: unknown): string | null { const normalized = typeof value === "string" ? value.trim() : ""; return normalized || null; }
function events(value: unknown): string[] { const source = Array.isArray(value) ? value : DEFAULT_EVENTS; const normalized = [...new Set(source.map((entry) => text(entry)?.toLowerCase()).filter((entry): entry is string => Boolean(entry)))]; return normalized.length ? normalized : DEFAULT_EVENTS; }
function privateAddress(host: string): boolean { const value = host.toLowerCase().replace(/^\[|\]$/g, ""); return !value || value === "localhost" || value.endsWith(".localhost") || /^(0|10|127|169\.254|192\.168)\./.test(value) || /^172\.(1[6-9]|2\d|3[01])\./.test(value) || value === "::" || value === "::1" || /^(fc|fd|fe8|fe9|fea|feb|ff)/.test(value); }
async function endpoint(value: unknown): Promise<string> { const input = text(value); if (!input) throw new Error("Webhook URL is required"); let url: URL; try { url = new URL(input); } catch { throw new Error("Webhook URL must be a valid URL"); } if (url.protocol !== "https:") throw new Error("Webhook URL must use https"); if (url.username || url.password || privateAddress(url.hostname)) throw new Error("Webhook URL must not target a private network"); url.hash = ""; return url.toString(); }
function bytes(value: Uint8Array): ArrayBuffer { return Uint8Array.from(value).buffer; }
function base64(value: Uint8Array): string { let binary = ""; for (const byte of value) binary += String.fromCharCode(byte); return btoa(binary); }
function secretMaterial(env: Env): string { const value = text(env.ASYNC_WEBHOOK_SECRET_ENCRYPTION_KEY) ?? text(env.WEBHOOK_SECRET_ENCRYPTION_KEY) ?? text(env.KEY_PEPPER_ACTIVE); if (!value) throw new Error("Webhook secret encryption key is missing"); return value; }
function signingSecret(): string { const value = crypto.getRandomValues(new Uint8Array(32)); return `whsec_${base64(value).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "")}`; }
async function encrypt(env: Env, secret: string) { const material = new TextEncoder().encode(secretMaterial(env)); const digest = await crypto.subtle.digest("SHA-256", material); const key = await crypto.subtle.importKey("raw", digest, "AES-GCM", false, ["encrypt"]); const iv = crypto.getRandomValues(new Uint8Array(12)); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv: bytes(iv) }, key, new TextEncoder().encode(secret)); const hmacKey = await crypto.subtle.importKey("raw", bytes(material), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const hash = new Uint8Array(await crypto.subtle.sign("HMAC", hmacKey, new TextEncoder().encode(secret))); return { secret_ciphertext: base64(new Uint8Array(ciphertext)), secret_iv: base64(iv), secret_hash: [...hash].map((byte) => byte.toString(16).padStart(2, "0")).join("") }; }
async function adminContext(c: any, workspaceId: unknown) { const context = await requireAccountWorkspace({ request: c.req.raw, env: c.env, workspaceId: String(workspaceId ?? "") }); return context && ["owner", "admin"].includes(context.role.toLowerCase()) ? context : null; }

export const accountSettingsWebhooksRouter = new Hono<{ Bindings: Env }>();

accountSettingsWebhooksRouter.get("/webhooks", async (c) => { const context = await adminContext(c, c.req.query("workspaceId")); if (!context) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const result = await context.client.from("gateway_webhook_endpoints").select("id,name,url,status,events,secret_ciphertext,created_at,updated_at").eq("workspace_id", context.workspaceId).neq("status", "deleted").order("created_at", { ascending: false }); if (result.error) return c.json({ error: "webhooks_unavailable" }, 503, PRIVATE_NO_STORE_HEADERS); return c.json({ endpoints: (result.data ?? []).map((row) => ({ id: String(row.id), name: String(row.name ?? "Async webhooks"), url: String(row.url ?? ""), status: String(row.status ?? "active"), events: Array.isArray(row.events) ? row.events.map(String) : [], hasSecret: Boolean(row.secret_ciphertext), createdAt: row.created_at ?? null, updatedAt: row.updated_at ?? null })) }, 200, PRIVATE_NO_STORE_HEADERS); });
accountSettingsWebhooksRouter.post("/webhooks", async (c) => { const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const context = await adminContext(c, body.workspaceId); if (!context) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); try { const secret = signingSecret(); const encrypted = await encrypt(c.env, secret); const result = await context.client.from("gateway_webhook_endpoints").insert({ workspace_id: context.workspaceId, name: text(body.name) ?? "Async webhooks", url: await endpoint(body.url), events: events(body.events), status: "active", ...encrypted, created_by: context.user.id }).select("id").single(); if (result.error) throw result.error; return c.json({ ok: true, id: String(result.data.id), signingSecret: secret }, 200, PRIVATE_NO_STORE_HEADERS); } catch (error) { return c.json({ error: error instanceof Error ? error.message : "webhook_write_failed" }, 409, PRIVATE_NO_STORE_HEADERS); } });
accountSettingsWebhooksRouter.put("/webhooks/:endpointId/status", async (c) => { const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const context = await adminContext(c, body.workspaceId); if (!context) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); if (!["active", "disabled"].includes(body.status)) return c.json({ error: "invalid_status" }, 400, PRIVATE_NO_STORE_HEADERS); const result = await context.client.from("gateway_webhook_endpoints").update({ status: body.status, updated_at: new Date().toISOString() }).eq("id", c.req.param("endpointId")).eq("workspace_id", context.workspaceId).neq("status", "deleted"); if (result.error) return c.json({ error: "webhook_write_failed" }, 503, PRIVATE_NO_STORE_HEADERS); return c.json({ ok: true }, 200, PRIVATE_NO_STORE_HEADERS); });
accountSettingsWebhooksRouter.post("/webhooks/:endpointId/rotate", async (c) => { const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const context = await adminContext(c, body.workspaceId); if (!context) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); try { const secret = signingSecret(); const result = await context.client.from("gateway_webhook_endpoints").update({ ...await encrypt(c.env, secret), updated_at: new Date().toISOString() }).eq("id", c.req.param("endpointId")).eq("workspace_id", context.workspaceId).neq("status", "deleted").select("id").maybeSingle(); if (result.error) throw result.error; if (!result.data) return c.json({ error: "Webhook endpoint not found" }, 404, PRIVATE_NO_STORE_HEADERS); return c.json({ ok: true, signingSecret: secret }, 200, PRIVATE_NO_STORE_HEADERS); } catch (error) { return c.json({ error: error instanceof Error ? error.message : "webhook_write_failed" }, 409, PRIVATE_NO_STORE_HEADERS); } });
accountSettingsWebhooksRouter.delete("/webhooks/:endpointId", async (c) => { const body: Record<string, any> = await c.req.json<Record<string, any>>().catch(() => ({})); const context = await adminContext(c, body.workspaceId); if (!context) return c.json({ error: "forbidden" }, 403, PRIVATE_NO_STORE_HEADERS); const now = new Date().toISOString(); const result = await context.client.from("gateway_webhook_endpoints").update({ status: "deleted", deleted_at: now, updated_at: now }).eq("id", c.req.param("endpointId")).eq("workspace_id", context.workspaceId).neq("status", "deleted"); if (result.error) return c.json({ error: "webhook_write_failed" }, 503, PRIVATE_NO_STORE_HEADERS); return c.json({ ok: true }, 200, PRIVATE_NO_STORE_HEADERS); });
