import type { ProviderOfferScope } from "@/lib/providers/providerOffers";
import type { CapabilityParamsById } from "@/lib/chat/roomModelSettings";

export type GatewaySupportedModel = {
	modelId: string;
	internalModelId: string | null;
	selectorModelId: string;
	providerId: string;
	capabilities: string[];
	capabilityParamsById?: CapabilityParamsById;
	inputModalities?: string[];
	outputModalities?: string[];
	effectiveFrom: string | null;
	effectiveTo: string | null;
	providerName: string | null;
	providerFamilyId: string | null;
	providerOfferLabel: string | null;
	providerOfferScope: ProviderOfferScope | null;
	providerPromptTrainingPolicy: string | null;
	modelName: string | null;
	modelStatus: string | null;
	organisationId: string | null;
	organisationName: string | null;
	previousModelId: string | null;
	releaseDate: string | null;
	announcementDate: string | null;
	inputPricePerMillion?: number | null;
	outputPricePerMillion?: number | null;
	isAvailable: boolean;
	chatBlockedReasons?: Array<{ source: "workspace" | "guardrail"; label: string; settingsHref: string }>;
};
